import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nimport math, random\nimport matplotlib.pyplot as plt\nprint('Ready ✅')")

def algo_10():
    return [
cell("markdown","# Algorithms 10: Single Variable Gradient Descent\n\n**Learning Objectives:**\n1. Understand the geometric intuition of Gradient Descent\n2. Implement the gradient descent update rule computationally\n3. Tune the learning rate $\\alpha$ to prevent divergence\n4. Handle Local Minima by testing multiple initial guesses\n\n**Prerequisites:** Math 02 (Derivatives)\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 10"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Intuition\n> 📖 *From Algorithms Ch. 10:* Gradient descent is a technique for minimizing differentiable functions. We take an initial guess, and repeatedly use the gradient to nudge that guess further and further “downhill” into an actual minimum.\n\nIf the derivative $f'(x)$ is positive, the function is sloping *up*. To go downhill, we must move left (decrease $x$).\nIf the derivative is negative, the function is sloping *down*. To go downhill, we must move right (increase $x$).\n\n### The Update Rule\n$$x_{n+1} = x_n - \\alpha f'(x_n)$$\n\nWhere:\n- $x_n$ is the current guess\n- $f'(x_n)$ tells us the direction and steepness of the slope\n- $\\alpha$ is the **learning rate** (usually $\\approx 0.01$), controlling how large of a step we take.\nWe subtract $\\alpha f'(x_n)$ because we always want to move in the *opposite* direction of the slope."),
cell("markdown","### Comprehension Check ✅\n1. What happens if $\\alpha$ is too large (e.g. 1.5)?\n2. What happens if $\\alpha$ is too small (e.g. 0.000001)?\n\n<details><summary>💡 Answers</summary>\n\n1. The guess will \"overshoot\" the minimum, jumping back and forth across the valley, potentially diverging to infinity.\n2. The guess will update by a miniscule amount each time, requiring an excessive number of iterations to converge.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: A Manual Step\nGiven $f(x) = x^2$. We know the minimum is at $x=0$.\nLet the initial guess be $x_0 = 1$. Let $\\alpha = 0.1$. \nCompute $x_1$ and $x_2$ by hand, then verify using Python."),
cell("code","def test_manual():\n    # f(x) = x^2, so f'(x) = 2x\n    # Replace with your manual values\n    x1 = None\n    x2 = None\n    \n    # assert round(x1, 2) == 0.80\n    # assert round(x2, 2) == 0.64\n    pass\ntest_manual()"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Gradient Descent Implementation\nWrite a function to perform gradient descent. Loop until the difference between consecutive guesses is smaller than `epsilon`, or until `max_iters` is reached."),
cell("code","def gradient_descent(f_prime, x0, alpha=0.01, epsilon=1e-5, max_iters=10000):\n    '''Return the x-value that minimizes f(x).'''\n    x = x0\n    # YOUR CODE HERE\n    return x\n\n# Test on f(x) = x^2 + x + 1, f'(x) = 2x + 1. True minimum is at x = -0.5\n# def f_prime(x): return 2*x + 1\n# min_x = gradient_descent(f_prime, 0)\n# print(\"Found minimum at:\", min_x)"),
cell("markdown","### Step 2: Global vs Local Minima\nLet's minimize $f(x) = x^4 + x^3 - 2x^2$. The derivative is $f'(x) = 4x^3 + 3x^2 - 4x$.\nThis function has *two* valleys. Run gradient descent starting from $x_0 = 1$ and then from $x_0 = -1$."),
cell("code","def f(x): return x**4 + x**3 - 2*x**2\ndef f_prime_complex(x): return 4*x**3 + 3*x**2 - 4*x\n\n# YOUR CODE HERE to run GD from x0=1 and x0=-1\n# Print the final x and the corresponding f(x) for each.\n# Which one is the global minimum?"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Visualizing Divergence\nIf we use a learning rate of $\\alpha = 1.5$ on $f(x) = x^2$, the guesses will diverge. Let's record the guesses and plot them."),
cell("code","import matplotlib.pyplot as plt\n\ndef record_gradient_descent(f_prime, x0, alpha, iters):\n    xs = [x0]\n    x = x0\n    for _ in range(iters):\n        x = x - alpha * f_prime(x)\n        xs.append(x)\n    return xs\n\n# Change alpha to 0.1 to see it converge properly, \n# or leave it at 1.05 to see it spiral out of control!\nx_history = record_gradient_descent(lambda x: 2*x, x0=1, alpha=1.05, iters=10)\n\n# plt.plot(x_history, 'o-')\n# plt.title(\"Gradient Descent Guesses over Time\")\n# plt.xlabel(\"Iteration\"); plt.ylabel(\"x value\"); plt.grid(True)\n# plt.show()"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Multi-Start Gradient Descent\nBecause we can get stuck in local minima, standard practice is to run GD from many random starting points, and keep the best result.\nWrite `multi_start_gd(f, f_prime, num_starts=10)` that randomly picks 10 initial guesses between -5 and 5, runs GD on each, and returns the absolute best `x`."),
cell("code","import random\ndef multi_start_gd(f, f_prime, num_starts=10):\n    '''Return the best global minimum x found from multiple random starts.'''\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Chalkboard Defense\nExplain how Gradient Ascent is different from Gradient Descent. If you wanted to *maximize* $f(x) = \\sin(x)$, what would the update rule be?\n\n<details><summary>💡 Sketch</summary>\nGradient Ascent seeks the maximum. You change the subtraction to addition: $x_{n+1} = x_n + \\alpha f'(x_n)$. \nBy adding the gradient, you move *uphill* instead of downhill.\n</details>\n\n---\n📚 **Next:** Algorithms 11 (Multivariable Gradient Descent)")
    ]

def algo_11():
    return [
cell("markdown","# Algorithms 11: Multivariable Gradient Descent\n\n**Learning Objectives:**\n1. Understand gradients as vectors of partial derivatives\n2. Apply the multivariable update rule computationally\n3. Optimize functions of two or more variables\n\n**Prerequisites:** Algorithms 10\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 11"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Multivariable Gradient Descent\n> 📖 *From Algorithms Ch. 11:* Multivariable gradient descent is similar to single-variable, except we replace the scalar derivative $f'(x)$ with the **gradient vector** $\\nabla f(\\vec{x})$.\n\n$$\\vec{x}_{n+1} = \\vec{x}_n - \\alpha \\nabla f(\\vec{x}_n)$$\n\nIf $f$ is a function of $(x, y)$, the gradient is a vector containing the partial derivatives:\n$$\\nabla f(x, y) = \\left\\langle \\frac{\\partial f}{\\partial x}, \\frac{\\partial f}{\\partial y} \\right\\rangle$$\n\nFor example, if $f(x, y) = x \\sin(y) + x^2$:\n- $\\frac{\\partial f}{\\partial x} = \\sin(y) + 2x$\n- $\\frac{\\partial f}{\\partial y} = x \\cos(y)$\n\nOur update rule becomes two simultaneous equations:\n$$x_{n+1} = x_n - \\alpha (\\sin(y_n) + 2x_n)$$\n$$y_{n+1} = y_n - \\alpha (x_n \\cos(y_n))$$"),
cell("markdown","### Comprehension Check ✅\n1. What does the vector $\\nabla f(x,y)$ geometrically represent on a 3D surface $z = f(x,y)$?\n2. If $\\nabla f(x,y) = \\langle 0, 0 \\rangle$, what do we know about the point $(x,y)$?\n\n<details><summary>💡 Answers</summary>\n\n1. It points in the direction of steepest *ascent* (steepest uphill slope). That's why we subtract it to go downhill.\n2. It is a critical point (a local minimum, local maximum, or saddle point). The surface is completely flat there.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Partial Derivatives\nGiven $f(x, y) = (x - 1)^2 + 3y^2$.\n1. Find $\\frac{\\partial f}{\\partial x}$\n2. Find $\\frac{\\partial f}{\\partial y}$\n\n*(Work it out on paper, then check the code below)*"),
cell("code","# The gradient should be <2(x-1), 6y>\n\ndef grad_f(x, y):\n    return (2*(x-1), 6*y)\n\nprint(\"Gradient at (2, 1) is:\", grad_f(2, 1)) # Should be (2, 6)"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Multivariable GD Implementation\nWrite a gradient descent function for 2 variables. Represent $\\vec{x}$ as a tuple `(x, y)`. The gradient function `grad_f` will return a tuple `(dx, dy)`."),
cell("code","def gradient_descent_2d(grad_f, x0, y0, alpha=0.01, iters=1000):\n    '''Return the (x, y) tuple that minimizes f(x, y).'''\n    x, y = x0, y0\n    # Loop `iters` times. In each loop:\n    # 1. Get dx, dy from grad_f(x, y)\n    # 2. Update x and y simultaneously\n    # YOUR CODE HERE\n    pass\n\n# Test on f(x, y) = (x - 1)^2 + 3y^2. True minimum is at (1, 0).\n# best_x, best_y = gradient_descent_2d(grad_f, 0, 5)\n# print(f\"Found minimum at: ({best_x:.4f}, {best_y:.4f})\")"),
cell("markdown","### Step 2: Optimizing a 3D Function\nGeneralize your logic to 3 variables $(x, y, z)$.\nMinimize $f(x, y, z) = (x - 1)^2 + 3(y - 2)^2 + 4(z + 1)^2$.\nFirst, compute the partial derivatives by hand. Then implement the solver."),
cell("code","def grad_f_3d(x, y, z):\n    # YOUR CODE HERE\n    pass\n\ndef gradient_descent_3d(grad_f, x0, y0, z0, alpha=0.01, iters=1000):\n    '''Return (x, y, z) that minimizes f(x, y, z).'''\n    x, y, z = x0, y0, z0\n    # YOUR CODE HERE\n    pass\n\n# Test. True minimum should be (1, 2, -1).\n# print(\"Found minimum at:\", gradient_descent_3d(grad_f_3d, 0, 0, 0))"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Sanity Checking the Function Value\nIn 3D, we can't easily visualize the graph to see if we are trapped in a local minimum. But we *can* track the function value $f(x, y, z)$ at each step to ensure it is decreasing.\nModify your GD function to print $f$ every 100 iterations."),
cell("code","def f_3d(x, y, z):\n    return (x - 1)**2 + 3*(y - 2)**2 + 4*(z + 1)**2\n\n# YOUR CODE HERE to verify f_3d is strictly decreasing during gradient descent."),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: N-Dimensional Vectorized Gradient Descent\nWriting `x, y, z` is tedious. If we have 100 variables, we need to use Arrays/Vectors.\nWrite `gradient_descent_nd(grad_f, start_vector)` where `start_vector` is a list of $N$ numbers, and `grad_f` returns a list of $N$ partial derivatives. Use a `for` loop to update all variables."),
cell("code","def gradient_descent_nd(grad_f, start_vector, alpha=0.01, iters=1000):\n    '''Return an N-dimensional vector that minimizes f.'''\n    vec = list(start_vector) # make a copy\n    for _ in range(iters):\n        # Get the gradient vector\n        # Update each element in `vec`\n        # YOUR CODE HERE\n        pass\n    return vec"),
cell("markdown","### Chalkboard Defense\nIf one partial derivative $\\frac{\\partial f}{\\partial x}$ is generally huge (e.g. 1000) and another $\\frac{\\partial f}{\\partial y}$ is tiny (e.g. 0.01), why might standard gradient descent struggle? (Hint: think about the single learning rate $\\alpha$).\n\n<details><summary>💡 Sketch</summary>\nBecause we use a single learning rate $\\alpha$, a value that is small enough to keep $x$ from diverging might be so microscopic that $y$ takes millions of iterations to converge. This is why advanced optimizers (like Adam) maintain separate, adaptive learning rates for every single variable!\n</details>\n\n---\n📚 **Next:** Algorithms 12 (Basic Sorting)")
    ]

def algo_12():
    return [
cell("markdown","# Algorithms 12: Basic Sorting\n\n**Learning Objectives:**\n1. Implement Selection Sort, Bubble Sort, and Insertion Sort from scratch\n2. Implement Counting Sort and understand its memory tradeoffs\n3. Analyze $O(n^2)$ time complexity\n\n**Prerequisites:** Algorithms 01\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 12"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### $O(n^2)$ Sorting Algorithms\n> 📖 *From Algorithms Ch. 12:* There are many methods for sorting arrays. The simplest are Selection, Bubble, and Insertion sort. They all take $O(n^2)$ time.\n\n- **Selection Sort:** Find the minimum element in the remaining array, and move it to the end of the sorted array.\n- **Bubble Sort:** Repeatedly swap adjacent elements if they are out of order. In each pass, the largest remaining element \"bubbles\" to the top. Stop when a full pass makes 0 swaps.\n- **Insertion Sort:** Take the next out-of-order element and swap it backwards until it sits in its correct sorted position among the already-processed elements.\n\n### Counting Sort: An $O(N+K)$ Alternative\nCounting sort does not compare elements! It counts occurrences of each number, then generates a new array directly from the counts. It is extremely fast but can use a massive amount of memory if the range of numbers is very large."),
cell("markdown","### Comprehension Check ✅\n1. Why is Bubble Sort $O(n^2)$?\n2. If an array contains the numbers `[1, 1000000]`, why is Counting Sort a terrible idea?\n\n<details><summary>💡 Answers</summary>\n\n1. In the worst case (a reverse-sorted array), it takes $n$ passes, and each pass performs $n$ comparisons/swaps. $n \\times n = n^2$.\n2. Counting sort requires a `counts` array of size `max - min + 1`. You would allocate an array of 1,000,000 integers just to sort 2 numbers!\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Minimum Helper\nSelection sort needs a helper function to find the minimum. Write `calc_min(arr)` without using Python's built in `min()`."),
cell("code","def calc_min(arr):\n    '''Return the minimum element of an array.'''\n    if not arr: return None\n    # YOUR CODE HERE\n    pass\n\n# assert calc_min([5, 2, 8, 1]) == 1"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Selection Sort\nUsing your `calc_min` function (or a similar loop), implement selection sort. Be careful to actually *remove* the element from the original list as you build the sorted list!"),
cell("code","def selection_sort(arr):\n    original = list(arr) # copy so we don't mutate the input\n    sorted_arr = []\n    # YOUR CODE HERE\n    return sorted_arr\n\n# print(selection_sort([3, 5, 8, 2, 5]))"),
cell("markdown","### Step 2: Bubble Sort\nImplement Bubble Sort. Keep track of whether a swap occurred in the current pass. If not, break the outer loop."),
cell("code","def bubble_sort(arr):\n    a = list(arr)\n    # YOUR CODE HERE\n    return a\n\n# print(bubble_sort([3, 5, 8, 2, 5]))"),
cell("markdown","### Step 3: Insertion Sort\nLoop through the array. When you find an element out of order (smaller than the one before it), use a `while` loop to swap it backwards until it's correctly placed."),
cell("code","def insertion_sort(arr):\n    a = list(arr)\n    for i in range(1, len(a)):\n        # Check a[i] and swap backwards if needed\n        # YOUR CODE HERE\n        pass\n    return a\n\n# print(insertion_sort([3, 5, 8, 2, 5]))"),
cell("markdown","### Step 4: Counting Sort\n1. Find `min` and subtract it from all elements.\n2. Find `max` (of the shifted elements) and create a `counts` array of size `max + 1`.\n3. Count frequencies.\n4. Rebuild the array and add `min` back."),
cell("code","def counting_sort(arr):\n    if not arr: return []\n    # YOUR CODE HERE\n    pass\n\n# print(counting_sort([3, 5, 8, 2, 5]))"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Performance Race\nLet's generate an array of 5,000 random integers and time Selection, Bubble, Insertion, and Counting sort."),
cell("code","import time, random\narr = [random.randint(0, 1000) for _ in range(5000)]\n\nfor name, func in [(\"Selection\", selection_sort), (\"Bubble\", bubble_sort), \n                   (\"Insertion\", insertion_sort), (\"Counting\", counting_sort)]:\n    start = time.time()\n    # res = func(arr)\n    # print(f\"{name:10} took {time.time() - start:.4f} seconds\")\n    pass"),
cell("markdown","### 🔍 Reflection\nCounting sort should have finished in 0.00something seconds, while the others took seconds. The difference between $O(N)$ and $O(N^2)$ is astronomical!"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: In-Place Selection Sort\nOur `selection_sort` created a brand new `sorted_arr`, taking $O(N)$ extra memory.\nCan you modify selection sort to be **in-place**? (Find the minimum of the unsorted portion of the array, and swap it with the first element of the unsorted portion. $O(1)$ extra memory)."),
cell("code","def selection_sort_inplace(arr):\n    a = list(arr)\n    # YOUR CODE HERE\n    return a"),
cell("markdown","### Chalkboard Defense\nExplain why Insertion Sort is extraordinarily fast ($O(N)$) if the input array is *already sorted*, whereas Selection Sort remains $O(N^2)$ even if the input is perfectly sorted.\n\n<details><summary>💡 Sketch</summary>\nIn Insertion Sort, if the array is already sorted, the inner `while` loop (which swaps backwards) never executes. The outer loop just does 1 check per element and moves on, taking $O(N)$ time.\nSelection Sort, however, blindly scans the entire remaining array to find the minimum *every single time*, regardless of order. It does $\\frac{N(N-1)}{2}$ comparisons no matter what.\n</details>\n\n---\n📚 **Next:** Algorithms 13 (Advanced Sorting: Merge & Quicksort)")
    ]

def algo_13():
    return [
cell("markdown","# Algorithms 13: Advanced Sorting\n\n**Learning Objectives:**\n1. Understand \"Divide and Conquer\" algorithms\n2. Implement Merge Sort recursively\n3. Implement Quicksort recursively\n4. Understand $O(n \\log n)$ time complexity\n\n**Prerequisites:** Algorithms 12\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 13"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Need for Speed\n> 📖 *From Algorithms Ch. 13:* With an average-case time complexity of $O(n \\log n)$, Merge Sort and Quicksort are generally faster than selection, bubble, and insertion sort. And unlike counting sort, they don't blow up in memory on large numbers.\n\n### Merge Sort (Divide & Conquer)\n1. Break the array in half.\n2. Recursively call Merge Sort on each half.\n3. Merge the two sorted halves back together.\nBase Case: Arrays of length 0 or 1 are already sorted.\n\n### Quicksort\n1. Pick a random `pivot` element.\n2. Split the rest of the array into three arrays: elements `< pivot`, `== pivot`, and `> pivot`.\n3. Recursively call Quicksort on the `<` array and `>` array.\n4. Concatenate the sorted `<` array, the `==` array, and the sorted `>` array."),
cell("markdown","### Comprehension Check ✅\n1. If we have two sorted arrays `A=[2, 5]` and `B=[3, 8]`, how do we merge them in $O(N)$ time?\n2. What happens to Quicksort if we accidentally always pick the absolute largest element as our pivot?\n\n<details><summary>💡 Answers</summary>\n\n1. Look at the first element of both (2 vs 3). 2 is smaller, pop it. Then look at 5 vs 3. 3 is smaller, pop it. Repeat until empty.\n2. The `<` array gets everything, and the `>` array gets nothing. We only reduced the problem size by 1! The time complexity degrades to $O(n^2)$.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: The Merge Helper\nWrite a function that takes two *already sorted* arrays and merges them into one sorted array in $O(N)$ time. \nDo not just concatenate and call `.sort()`! Use two pointers (or `pop(0)`)."),
cell("code","def merge(arr1, arr2):\n    '''Merge two sorted arrays into a single sorted array.'''\n    merged = []\n    a1 = list(arr1)\n    a2 = list(arr2)\n    # YOUR CODE HERE: while both arrays have elements, compare the first elements.\n    # Append the smaller one to `merged` and pop it.\n    # After the loop, append any remaining elements from either array.\n    return merged\n\n# assert merge([2, 5], [3, 8]) == [2, 3, 5, 8]\n# print('Phase 0 passed ✅')"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Merge Sort\nNow implement the recursive `merge_sort(arr)` function. Use array slicing `arr[:mid]` to split the array."),
cell("code","def merge_sort(arr):\n    '''Return a sorted array using Merge Sort.'''\n    # Base case\n    if len(arr) <= 1: \n        return arr\n    \n    # Divide\n    mid = len(arr) // 2\n    left = arr[:mid]\n    right = arr[mid:]\n    \n    # Conquer (Recursion)\n    # YOUR CODE HERE\n    \n    # Combine\n    # YOUR CODE HERE (use your merge helper)\n    pass\n\n# print(merge_sort([3, 5, 8, 2, 5, 1, 9, 0]))"),
cell("markdown","### Step 2: Quicksort\nImplement `quicksort(arr)`. Choose `arr[0]` or `random.choice(arr)` as your pivot."),
cell("code","import random\ndef quicksort(arr):\n    '''Return a sorted array using Quicksort.'''\n    # Base case\n    if len(arr) <= 1:\n        return arr\n        \n    pivot = random.choice(arr)\n    less = []\n    equal = []\n    greater = []\n    \n    # Partition\n    # YOUR CODE HERE\n    \n    # Conquer & Combine\n    # YOUR CODE HERE\n    pass\n\n# print(quicksort([3, 5, 8, 2, 5, 1, 9, 0]))"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Final Race: $O(N \\log N)$ vs $O(N^2)$\nLet's race Merge Sort against your Bubble Sort from the previous notebook on 5,000 items."),
cell("code","import time\narr = [random.randint(0, 1000) for _ in range(5000)]\n\nstart = time.time()\n# quicksort(arr)\nprint(f\"Quicksort took {time.time() - start:.4f} seconds\")\n\n# Try running your bubble_sort code here if you brought it over, \n# you'll see Quicksort finishes almost instantly!"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: In-Place Quicksort (Hoare Partitioning)\nOur Quicksort allocated three new arrays (`less`, `equal`, `greater`), using $O(N)$ extra memory.\nReal Quicksort is done **in-place** using two pointers that scan from the left and right, swapping elements that are on the wrong side of the pivot. \nImplement an in-place `quicksort_inplace(arr, low, high)`.\n*(This is very tricky!)*"),
cell("code","def quicksort_inplace(arr, low=0, high=None):\n    if high is None: high = len(arr) - 1\n    if low >= high: return\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Chalkboard Defense\nExplain conceptually why Merge Sort takes $O(N \\log N)$ time. \n\n<details><summary>💡 Sketch</summary>\nThe recursive splitting forms a tree. An array of size $N$ can be split in half $\\log_2 N$ times before hitting size 1. So the tree has $\\log_2 N$ levels.\nAt each level, we merge sub-arrays. Merging two arrays of size $K$ takes $O(K)$ time. If you sum up the merge times across an entire level of the tree, you are merging $N$ total elements, which takes $O(N)$ time.\nSince there are $\\log N$ levels, and each level does $O(N)$ work, the total time is $O(N \\log N)$.\n</details>\n\n---\n📚 **Next:** Algorithms 14 (Basic Matrix Arithmetic)")
    ]

if __name__=="__main__":
    save(algo_10(),os.path.join(OUT,"10_single_variable_gd.ipynb"))
    save(algo_11(),os.path.join(OUT,"11_multivariable_gd.ipynb"))
    save(algo_12(),os.path.join(OUT,"12_basic_sorting.ipynb"))
    save(algo_13(),os.path.join(OUT,"13_advanced_sorting.ipynb"))
    print("Notebooks 10, 11, 12, 13 done. Batch 2 is complete!")
