import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nimport random\nimport matplotlib.pyplot as plt\nprint('Ready ✅')")

def algo_04():
    return [
cell("markdown","# Algorithms 04: Simulating Randomness\n\n**Learning Objectives:**\n1. Understand Monte Carlo simulation\n2. Simulate events using random number generators\n3. Estimate complex probabilities computationally\n4. Verify results using high-level sanity checks (distributions)\n\n**Prerequisites:** Algorithms 01\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 4"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Monte Carlo Simulation\n> 📖 *From Algorithms Ch. 4:* It’s often possible to estimate probabilities of events by simulating a large number of random experiments and measuring the proportion of trials in which the desired outcome occurred. This technique is known as **Monte Carlo simulation**.\n\nTo simulate a coin flip, we can generate a random decimal $r$ between 0 and 1:\n- if $r < 0.5$, it's heads\n- otherwise, it's tails"),
cell("markdown","### High-Level Sanity Checks\nWhen simulating complex probabilities that you can't work out by hand, you should verify your code using **high-level sanity checks**:\n1. The probabilities of all possible outcomes should add up to exactly 1.\n2. The distribution should match qualitative expectations (e.g., flipping 10 coins should form a symmetric bell curve peaking at 5 heads)."),
cell("markdown","### Comprehension Check ✅\n1. If we use `r < 0.8` instead of `r < 0.5`, what kind of coin are we simulating?\n2. Why do we need to run *many* trials (e.g., 10,000) instead of just 10?\n\n<details><summary>💡 Answers</summary>\n\n1. A biased coin that lands on heads 80% of the time.\n2. The Law of Large Numbers states that experimental probabilities converge to theoretical probabilities as the number of trials approaches infinity. 10 trials is too few to get an accurate estimate due to high variance.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: A Single Coin Flip\nWrite a function to simulate a single coin flip using Python's `random.random()` which returns a float between 0.0 and 1.0."),
cell("code","import random\ndef flip_coin():\n    '''Return \"H\" or \"T\" with 50% probability.'''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# print(flip_coin())"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Simulating Multiple Flips\nWrite a function to simulate `num_flips` coins and return the total number of heads."),
cell("code","def simulate_trial(num_flips):\n    '''Return the number of heads obtained in `num_flips` coin flips.'''\n    # YOUR CODE HERE\n    pass\n\n# assert 0 <= simulate_trial(10) <= 10\n# print('Step 1 passed ✅')"),
cell("markdown","### Step 2: Monte Carlo Probability\nUse Monte Carlo simulation to estimate the probability of getting *exactly* `target_heads` in `num_flips`."),
cell("code","def sim_probability(target_heads, num_flips, trials=10000):\n    '''Return the estimated probability of getting target_heads.'''\n    # YOUR CODE HERE\n    pass\n\n# Test: Probability of getting exactly 5 heads in 10 flips is ≈ 0.246\n# prob = sim_probability(5, 10)\n# print(f\"P(5 heads in 10 flips) ≈ {prob:.4f}\")"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Plotting the Distribution (Sanity Check)\nLet's run a sanity check by plotting the probability distribution for `num_flips = 10`."),
cell("code","import matplotlib.pyplot as plt\n\nnum_flips = 10\nprobs = []\n\nfor k in range(num_flips + 1):\n    # p = sim_probability(k, num_flips, trials=2000)\n    # probs.append(p)\n    pass  # Replace with actual code when sim_probability is ready\n\n# if len(probs) > 0:\n#     plt.bar(range(num_flips + 1), probs)\n#     plt.title(f\"Probability Distribution for {num_flips} Coin Flips\")\n#     plt.xlabel(\"Number of Heads\")\n#     plt.ylabel(\"Probability\")\n#     plt.grid(alpha=0.3)\n#     plt.show()\n#     print(f\"Sum of probabilities: {sum(probs):.4f} (should be ≈ 1.0)\")"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: The Birthday Paradox\nWhat is the probability that in a room of $N$ people, at least two share the same birthday? (Assume 365 days in a year).\nUse Monte Carlo simulation to plot the probability for $N$ from 1 to 60."),
cell("code","def sim_birthday_paradox(N, trials=1000):\n    '''Return the probability that >=2 people out of N share a birthday.'''\n    # YOUR CODE HERE\n    pass\n\n# Test for N=23 (Probability should be ≈ 50%)\n# print(f\"P(shared birthday | 23 people) ≈ {sim_birthday_paradox(23):.4f}\")"),
cell("markdown","### Chalkboard Defense\nExplain why `sim_probability` takes $O(\\text{trials} \\times \\text{num\\_flips})$ time. How could you mathematically compute the exact probability without simulation?\n\n<details><summary>💡 Sketch</summary>\nBecause you run a loop `trials` times, and inside that loop you flip a coin `num_flips` times.\nThe exact probability is given by the Binomial Distribution: $P(k) = \\binom{n}{k} p^k (1-p)^{n-k}$.\n</details>\n\n---\n📚 **Next:** Algorithms 05 (Roulette Wheel Selection)")
    ]

def algo_05():
    return [
cell("markdown","# Algorithms 05: Roulette Wheel Selection\n\n**Learning Objectives:**\n1. Sample from discrete, non-uniform probability distributions\n2. Compute a cumulative distribution function computationally\n3. Apply Roulette Wheel Selection to pick an index\n\n**Prerequisites:** Algorithms 04\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 5"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Non-Uniform Distributions\n> 📖 *From Algorithms Ch. 5:* Flipping a fair coin is sampling from `[0.5, 0.5]`. What if we want to roll a die with 2 red, 1 blue, 1 green, and 1 yellow face? We must sample from `[0.4, 0.2, 0.2, 0.2]`.\n\n### Roulette Wheel Selection\nTo sample an index from an arbitrary distribution:\n1. Turn the distribution into a **cumulative distribution**. (e.g. `[0.4, 0.6, 0.8, 1.0]`)\n2. Sample a random float $r$ between 0 and 1. (e.g. `r = 0.63`)\n3. Find the **first index** in the cumulative distribution that is $\\geq r$. (0.8 is the first value $\\geq$ 0.63, so we pick index 2)."),
cell("markdown","### Comprehension Check ✅\n1. Given the cumulative distribution `[0.1, 0.5, 0.9, 1.0]`, which index is chosen if $r = 0.45$?\n2. What must the final value in a cumulative probability distribution always be?\n\n<details><summary>💡 Answers</summary>\n\n1. Index 1 (the value 0.5 is the first value $\\geq$ 0.45).\n2. It must be 1.0, because the sum of all probabilities must be 100%.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Compute Cumulative Distribution\nCompute the cumulative distribution for `[0.1, 0.2, 0.3, 0.4]` by hand, then write a function to do it."),
cell("code","def get_cumulative(dist):\n    '''Given a list of probabilities, return the cumulative list.'''\n    # YOUR CODE HERE\n    pass\n\n# assert get_cumulative([0.1, 0.2, 0.3, 0.4]) == [0.1, 0.3, 0.6, 1.0]\n# print('Phase 0 passed ✅')"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Roulette Wheel Selection\nImplement the full algorithm using Python's `random.random()`."),
cell("code","import random\n\ndef roulette_wheel_selection(dist):\n    '''Return an index sampled according to the given distribution.'''\n    # 1. Get cumulative distribution\n    # 2. Generate random float r\n    # 3. Find first index where cumulative[i] >= r\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# print(\"Sampled index:\", roulette_wheel_selection([0.4, 0.2, 0.2, 0.2]))"),
cell("markdown","### Step 2: Verification (Interleaved Practice)\nVerify that your selection algorithm is correct by running it 10,000 times and checking the proportions."),
cell("code","def verify_roulette(dist, trials=10000):\n    '''Return a list of experimental proportions for each index.'''\n    # YOUR CODE HERE\n    pass\n\n# dist = [0.4, 0.2, 0.2, 0.2]\n# exp_dist = verify_roulette(dist)\n# print(\"Expected:\", dist)\n# print(\"Experimental:\", exp_dist)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Pathological Case: Imprecise Floats\nWhat happens if the sum of probabilities is `0.9999999999` instead of exactly `1.0`, and $r$ happens to be exactly `0.99999999995`? Your loop might reach the end of the array and find nothing $\\geq r$!\n\nModify your `roulette_wheel_selection` code above to handle this (e.g., if you exit the loop without returning, return the very last index)."),
cell("code","# Write a test that proves your function won't crash on this edge case.\ndist = [0.333, 0.333, 0.333]  # Sum is 0.999\n\n# Mock random.random to return 0.9995\noriginal_random = random.random\nrandom.random = lambda: 0.9995\n\ntry:\n    # idx = roulette_wheel_selection(dist)\n    # print(\"Fallback index returned safely:\", idx)\n    pass\nfinally:\n    random.random = original_random  # restore original function"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Binary Search Optimization\nIf the distribution has $N=10,000$ items, scanning the cumulative distribution from left to right takes $O(N)$ time.\nSince a cumulative distribution is inherently **sorted**, you can use Binary Search to find the index in $O(\\log N)$ time.\nImplement `roulette_wheel_binary_search`."),
cell("code","def roulette_wheel_binary_search(dist):\n    '''Sample an index in O(log N) time using binary search on the cumulative array.'''\n    # YOUR CODE HERE\n    pass\n\n# verify_roulette with roulette_wheel_binary_search"),
cell("markdown","### Chalkboard Defense\nExplain how the binary search approach reduces the time complexity from $O(N)$ to $O(\\log N)$, and provide the exact condition used to determine whether to search the left or right half of the array.\n\n<details><summary>💡 Sketch</summary>\nInstead of checking every element sequentially, binary search checks the middle element of the cumulative array. If $r > \\text{cumulative}[\\text{mid}]$, the target must be in the right half. If $r \\leq \\text{cumulative}[\\text{mid}]$, it must be in the left half (including mid). This halves the search space at each step, taking $\\log_2 N$ steps.\n</details>\n\n---\n📚 **Next:** Algorithms 06 (Cartesian Product)")
    ]

def algo_06():
    return [
cell("markdown","# Algorithms 06: Cartesian Product\n\n**Learning Objectives:**\n1. Understand the Cartesian Product of multiple arrays\n2. Understand the danger of array-referencing vs array-copying in Python\n3. Implement an iterative Cartesian product generator from scratch\n\n**Prerequisites:** Algorithms 01\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 6"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### What is a Cartesian Product?\n> 📖 *From Algorithms Ch. 6:* The Cartesian product constructs all the points whose elements occupy the given ranges. \n\nFor example, if we have ranges `[1, 2]` and `['A', 'B']`, the Cartesian product is:\n`[[1, 'A'], [1, 'B'], [2, 'A'], [2, 'B']]`.\n\n### The Algorithm\n1. Create an array initialized with an empty point: `points = [[]]`.\n2. For each range in your input:\n   - Create a `new_points` array.\n   - For every point currently in `points`, and every item in the current range, append the item to the point and save it to `new_points`.\n   - Update `points = new_points`.\n\n### The Array Copying Trap\nIn Python, if `a = [1]`, doing `b = a` does NOT copy the array. Both `a` and `b` point to the exact same list in memory. Doing `b.append(2)` will modify `a` as well!\nTo make a new copy, you must use `b = a[:]` or `b = a.copy()` or `b = list(a)`."),
cell("markdown","### Comprehension Check ✅\n1. If you take the Cartesian product of three arrays of sizes 2, 3, and 4, how many items will be in the result?\n2. What is the value of `a` after this code runs? `a = [1]; b = a; b.append(2)`\n\n<details><summary>💡 Answers</summary>\n\n1. $2 \\times 3 \\times 4 = 24$ items.\n2. `a = [1, 2]`. Because `b` is just a reference to `a`, appending to `b` mutates the underlying list.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: The Copy Trap\nWrite a small code snippet to demonstrate the array referencing trap. Create `a`, make `b` point to it, mutate `b`, and print `a` to show it changed. Then show the correct way to make a copy."),
cell("code","# YOUR CODE HERE to demonstrate the copy trap\n# a = ...\n# b = ..."),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Cartesian Product Implementation\nImplement `calc_cartesian_product(arrays)`. Remember to copy your sub-arrays when extending them!"),
cell("code","def calc_cartesian_product(arrays):\n    '''Return a list of all combinations (Cartesian product) of the input arrays.'''\n    points = [[]]\n    \n    for arr in arrays:\n        new_points = []\n        # For each point in points, and each item in arr:\n        #   1. Make a copy of the point\n        #   2. Append the item to the copy\n        #   3. Add the copy to new_points\n        # YOUR CODE HERE\n        \n        points = new_points\n        \n    return points\n\n# Tests:\n# out = calc_cartesian_product([[1, 2], ['A', 'B']])\n# assert len(out) == 4\n# assert [1, 'A'] in out\n# print('Step 1 passed ✅')"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Visualizing Combinatorial Explosion\nThe size of a Cartesian product grows exponentially. Let's see how fast our computer can compute combinations of size $N$ from an array of 10 items."),
cell("code","import time\n\nitems = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n\n# Warning: don't set max_N too high!\nmax_N = 5 \nfor n in range(1, max_N + 1):\n    start = time.time()\n    # res = calc_cartesian_product([items] * n)\n    # print(f\"N={n}: {len(res)} combinations | Time: {time.time() - start:.4f}s\")\n    pass"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Recursive Cartesian Product\nThe iterative method is great, but Cartesian product is highly amenable to recursion.\nWrite a recursive function to compute the Cartesian product.\n\n*Hint:* The Cartesian product of `[A, B, C]` is the Cartesian product of `[A]` combined with the Cartesian product of `[B, C]`."),
cell("code","def calc_cartesian_recursive(arrays):\n    # YOUR CODE HERE\n    pass\n\n# assert len(calc_cartesian_recursive([[1, 2], ['A', 'B']])) == 4"),
cell("markdown","### Chalkboard Defense\nWhy is the space complexity of `calc_cartesian_product` equal to $O(K^N)$ (assuming $N$ arrays of size $K$), and how could you mitigate memory exhaustion using Python **generators** (`yield`)?\n\n<details><summary>💡 Sketch</summary>\nIt builds the entire list of $K^N$ combinations in memory at once. \nIf you use `yield` (a generator), you can lazily evaluate the combinations one at a time. This reduces the memory footprint (space complexity) to $O(N)$ — enough to store a single point and the generator state — while the time complexity remains $O(K^N)$.\n</details>\n\n---\n📚 **Next:** Algorithms 07 (Brute Force Cryptography)")
    ]

if __name__=="__main__":
    save(algo_04(),os.path.join(OUT,"04_simulating_randomness.ipynb"))
    save(algo_05(),os.path.join(OUT,"05_roulette_wheel.ipynb"))
    save(algo_06(),os.path.join(OUT,"06_cartesian_product.ipynb"))
    print("Notebooks 04, 05, and 06 done.")
