import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nimport math, random\nprint('Ready ✅')")

def algo_14():
    return [
cell("markdown","# Algorithms 14: Basic Matrix Arithmetic\n\n**Learning Objectives:**\n1. Design a `Matrix` class from scratch using 2D arrays\n2. Implement matrix addition, subtraction, scalar multiplication, and transpose\n3. Implement matrix multiplication using dot products\n4. Compute matrix determinants recursively via cofactor expansion\n\n**Prerequisites:** Linear Algebra\n**Estimated time:** 120 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 14"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Object-Oriented Approach\n> 📖 *From Algorithms Ch. 14:* Let’s use arrays to implement matrices and their associated mathematical operations. Create a class `Matrix` that implements basic matrix arithmetic.\n\nIn Python, a class is defined using the `class` keyword. \n- The `__init__` method initializes the object.\n- Methods like `add(self, other)` take `self` (the current object) and `other` (another matrix).\n- You should validate dimensions before attempting operations (e.g., adding a 2x3 matrix to a 3x3 matrix should raise an error).\n\n### Recursive Cofactor Expansion\nTo find the determinant of a 3x3 matrix, we expand along the top row, multiplying each element by the determinant of the 2x2 submatrix (cofactor) that remains when you cross out its row and column. The signs alternate: $+ - + - \\dots$"),
cell("markdown","### Comprehension Check ✅\n1. If $A$ is $2 \\times 3$ and $B$ is $3 \\times 4$, what are the dimensions of $A \\times B$?\n2. What is the base case for the recursive determinant algorithm?\n\n<details><summary>💡 Answers</summary>\n\n1. $2 \\times 4$. The number of columns in A must match the number of rows in B.\n2. A $1 \\times 1$ matrix. Its determinant is just its single element. (Alternatively, a $2 \\times 2$ matrix, where the determinant is $ad-bc$).\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: 2x2 Determinant\nGiven matrix $A = \\begin{bmatrix} 4 & 5 \\\\ 7 & 8 \\end{bmatrix}$. Compute its determinant by hand.\n\nThen write a simple function that computes the determinant of any 2x2 array `[[a,b],[c,d]]`."),
cell("code","def det_2x2(matrix_data):\n    # YOUR CODE HERE\n    pass\n\n# assert det_2x2([[4, 5], [7, 8]]) == -3\n# print('Phase 0 passed ✅')"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The Matrix Class Core\nImplement `__init__`, dimensions, and basic arithmetic (`add`, `subtract`, `scalar_multiply`, `transpose`)."),
cell("code","class Matrix:\n    def __init__(self, data):\n        # data is a 2D list, e.g. [[1, 2], [3, 4]]\n        # Create a deep copy to prevent mutation bugs!\n        self.data = [list(row) for row in data]\n        self.num_rows = len(self.data)\n        self.num_cols = len(self.data[0]) if self.num_rows > 0 else 0\n\n    def add(self, other):\n        if self.num_rows != other.num_rows or self.num_cols != other.num_cols:\n            raise ValueError(\"Dimensions do not match for addition.\")\n        # Create new 2D list for result\n        # YOUR CODE HERE\n        pass\n\n    # Implement subtract, scalar_multiply, and transpose\n    # YOUR CODE HERE\n    pass\n\n# Test logic\n# m1 = Matrix([[1, 2], [3, 4]])\n# m2 = Matrix([[5, 6], [7, 8]])\n# print(\"Addition:\", m1.add(m2).data) # Should be [[6, 8], [10, 12]]"),
cell("markdown","### Step 2: Matrix Multiplication\nImplement `multiply(self, other)`. Remember that cell $(i, j)$ in the output is the dot product of row $i$ in `self` and column $j$ in `other`."),
cell("code","# Add this method to your Matrix class:\n# def multiply(self, other):\n#     if self.num_cols != other.num_rows:\n#         raise ValueError(\"Inner dimensions must match!\")\n#     # YOUR CODE HERE\n#     pass"),
cell("markdown","### Step 3: Recursive Determinant\nWrite a method to extract a submatrix (by removing row $i$ and column $j$). Then use it to write `determinant(self)`."),
cell("code","# Add these methods to your Matrix class:\n# def get_submatrix(self, drop_row, drop_col):\n#     # YOUR CODE HERE\n#     pass\n\n# def determinant(self):\n#     if self.num_rows != self.num_cols:\n#         raise ValueError(\"Must be a square matrix.\")\n#     if self.num_rows == 1:\n#         return self.data[0][0]\n#     if self.num_rows == 2:\n#         return self.data[0][0]*self.data[1][1] - self.data[0][1]*self.data[1][0]\n#     \n#     # Compute recursively along the top row (row 0)\n#     det = 0\n#     # YOUR CODE HERE\n#     return det"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Pathological Case: Deep Copy vs Shallow Copy\nIf you initialize `Matrix` by just doing `self.data = data` (shallow copy), and then the user modifies the original array `data[0][0] = 99`, the `Matrix` object *magically changes* too!\n\nVerify that your `Matrix` class is immune to this by running the test below."),
cell("code","arr = [[1, 2], [3, 4]]\nm = Matrix(arr)\narr[0][0] = 99\n\n# print(\"Original array:\", arr)\n# print(\"Matrix data:\", m.data)\n# assert m.data[0][0] == 1, \"Your Matrix class suffered a mutation leak! Use deep copies.\""),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Matrix Power $A^n$ in $O(\\log n)$ Time\nComputing $A^{10}$ as $A \\times A \\dots \\times A$ takes 9 multiplications.\nYou can do it in 4 multiplications using **Exponentiation by Squaring**:\n$A^2 = A \\times A$\n$A^4 = A^2 \\times A^2$\n$A^8 = A^4 \\times A^4$\n$A^{10} = A^8 \\times A^2$\n\nImplement `power(self, n)` using this algorithm."),
cell("code","# YOUR CODE HERE\npass"),
cell("markdown","### Chalkboard Defense\nExplain the time complexity of your recursive determinant algorithm for an $N \\times N$ matrix. Why is this unacceptably slow for $N=10$?\n\n<details><summary>💡 Sketch</summary>\nComputing an $N \\times N$ determinant requires computing $N$ determinants of size $(N-1) \\times (N-1)$.\nThis yields a recurrence relation roughly equivalent to $O(N!)$ time complexity.\nFor $N=10$, $10! = 3.6$ million operations, which is slow but manageable. For $N=20$, $20! \approx 2.4 \\times 10^{18}$, which would take hundreds of years. We need a faster way (RREF!)\n</details>\n\n---\n📚 **Next:** Algorithms 15 (Reduced Row Echelon Form)")
    ]

def algo_15():
    return [
cell("markdown","# Algorithms 15: Reduced Row Echelon Form\n\n**Learning Objectives:**\n1. Implement the RREF algorithm iteratively using helper functions\n2. Compute the Inverse of a matrix much faster using augmented RREF\n3. Compute Determinants in $O(N^3)$ time instead of $O(N!)$\n\n**Prerequisites:** Algorithms 14\n**Estimated time:** 120 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 15"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The RREF Algorithm\n> 📖 *From Algorithms Ch. 15:* To convert a matrix to RREF:\n1. Initialize `pivot_row = 0` and `pivot_col = 0`.\n2. Look for a non-zero entry in `pivot_col` at or below `pivot_row`.\n3. If found: \n   - Swap that row with `pivot_row`.\n   - Divide `pivot_row` by the pivot element so it becomes 1.\n   - Subtract multiples of `pivot_row` from all other rows so the rest of the column becomes 0.\n   - Increment both `pivot_row` and `pivot_col`.\n4. If NOT found: Increment only `pivot_col`.\n5. Repeat until you run out of rows or columns.\n\n### Inverse via RREF\nTo invert matrix $A$, augment it with the Identity matrix $I$: $[A | I]$. \nRun RREF. If the left side becomes $I$, the right side is $A^{-1}$.\n\n### Fast Determinant via RREF\nRecursive determinant is $O(N!)$. RREF takes $O(N^3)$ time.\n- Swapping two rows multiplies determinant by $-1$.\n- Dividing a row by $c$ multiplies determinant by $c$.\nIf you track these changes during RREF, the final matrix has determinant $1$, and you can multiply backward to find the original determinant!"),
cell("markdown","### Comprehension Check ✅\n1. If you augment $A = [2]$ with $I = [1]$ and run RREF, what do you get?\n2. During RREF, you swap rows twice, and divide one row by 3, and another by 4. If the resulting RREF matrix is the identity, what was the original determinant?\n\n<details><summary>💡 Answers</summary>\n\n1. $[2 | 1]$. Divide by 2: $[1 | 0.5]$. So $A^{-1} = [0.5]$.\n2. Determinant of identity is 1. Original determinant = $1 \\times (-1)^2 \\times 3 \\times 4 = 12$.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: RREF by Hand\nConvert $\\begin{bmatrix} 2 & 4 \\\\ 3 & 1 \\end{bmatrix}$ to RREF on paper.\nTrack the operations you performed.\n\n*(Work it out on paper, then check mentally)*"),
cell("code","# Expected sequence of operations:\n# 1. Pivot at (0,0) is 2. Divide Row 0 by 2 -> [1, 2]\n# 2. Eliminate Row 1: Row 1 = Row 1 - 3*Row 0 -> [0, -5]\n# 3. Pivot at (1,1) is -5. Divide Row 1 by -5 -> [0, 1]\n# 4. Eliminate Row 0: Row 0 = Row 0 - 2*Row 1 -> [1, 0]\n# Result is the Identity matrix."),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Helper Functions\nWrite three helper methods for your `Matrix` class:\n1. `swap_rows(self, i, j)`\n2. `multiply_row(self, i, c)`\n3. `add_multiple_of_row(self, target_row, source_row, c)` (does: `target = target + c * source`)"),
cell("code","class Matrix:\n    def __init__(self, data):\n        self.data = [list(row) for row in data]\n        self.num_rows = len(self.data)\n        self.num_cols = len(self.data[0]) if self.num_rows > 0 else 0\n        \n    # YOUR HELPER FUNCTIONS HERE\n    pass\n\n# Test your helpers!"),
cell("markdown","### Step 2: The RREF Algorithm\nImplement `rref(self)` using the exact procedure described in the Phase -1 section."),
cell("code","# Add this to your Matrix class:\n# def rref(self):\n#     # Create a copy so we don't mutate the original\n#     rref_mat = Matrix(self.data)\n#     pr = 0\n#     pc = 0\n#     while pr < rref_mat.num_rows and pc < rref_mat.num_cols:\n#         # Find a non-zero element in column `pc` at or below row `pr`\n#         # YOUR CODE HERE\n#         pass\n#     return rref_mat\n\n# Test:\n# m = Matrix([[2, 4], [3, 1]])\n# print(m.rref().data) # Should be [[1.0, 0.0], [0.0, 1.0]]"),
cell("markdown","### Step 3: Fast Determinant (Interleaved Practice)\nCopy-paste your RREF code into a new method `fast_determinant(self)`. \nTrack a variable `det = 1`. Whenever you swap, `det *= -1`. Whenever you divide by $c$, `det *= c`.\nAt the end, if the RREF matrix is the Identity, return `det`. Otherwise (e.g. it has a row of zeros), the determinant is 0."),
cell("code","# def fast_determinant(self):\n#     # YOUR CODE HERE\n#     pass"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Pathological Case: Float Imprecision\nWhen doing division, floats can become slightly inaccurate (e.g., `0.0000000000000001` instead of `0`). \nIf you check `if val == 0:`, it might fail! \nYou must check `if abs(val) < 1e-10:`.\nGo back and update your RREF implementation to use this tolerance threshold!"),
cell("code","# Test your float tolerance:\n# m = Matrix([[3, 6], [1, 2]])\n# The determinant is exactly 0. \n# If you didn't use epsilon-tolerance, fast_determinant might crash or return a tiny non-zero float.\n# print(\"Det:\", m.fast_determinant())"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Matrix Inversion\nImplement `inverse(self)`.\n1. Augment `self` with the Identity matrix.\n2. Run RREF.\n3. If the left side is NOT the identity, raise an Error (\"Matrix is singular/non-invertible\").\n4. Slice and return the right side as a new `Matrix`."),
cell("code","# YOUR CODE HERE\npass"),
cell("markdown","### Chalkboard Defense\nExplain why calculating the determinant via RREF takes $O(N^3)$ time, whereas recursive cofactor expansion takes $O(N!)$ time. What are the two nested loops occurring inside the `while` loop of RREF?\n\n<details><summary>💡 Sketch</summary>\nThe while loop runs $N$ times. Inside, we find a pivot ($O(N)$), and then we eliminate all other rows by subtracting a multiple of the pivot row. Subtracting a row from another row requires iterating over all $N$ columns. Doing this for $N$ rows takes $N \\times N = O(N^2)$ time inside the while loop. \nTotal time: $N \\times O(N^2) = O(N^3)$.\n</details>\n\n---\n📚 **Next:** Algorithms 16 (K-Means Clustering)")
    ]

def algo_16():
    return [
cell("markdown","# Algorithms 16: K-Means Clustering\n\n**Learning Objectives:**\n1. Understand unsupervised learning and clustering\n2. Implement the iterative K-Means algorithm\n3. Use Euclidean distance to assign data points to clusters\n4. Use the Elbow Method to determine the optimal number of clusters $K$\n\n**Prerequisites:** Algorithms 11\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 16"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The K-Means Algorithm\n> 📖 *From Algorithms Ch. 16:* K-means clustering groups similar records together. It guesses initial clusters, and repeatedly updates them to make them more cohesive.\n\n1. **Initialize:** Randomly divide the data into $K$ parts (clusters). Compute the center (mean) of each part.\n2. **Assign:** Loop through all data points. Re-assign each point to the cluster whose center is closest (using Euclidean distance).\n3. **Update:** Compute the new center for each cluster by taking the mean of all points newly assigned to it.\n4. **Repeat:** Repeat Assign & Update until the cluster assignments stop changing.\n\n### The Elbow Method\nHow do we choose $K$? If $K = N$ (number of points), every point is its own cluster (distance=0, but useless). \nWe plot the **Total Distance** (sum of distances from each point to its cluster center) against $K$. The curve goes down. We pick the \"elbow\" of the curve — the point of diminishing returns."),
cell("markdown","### Comprehension Check ✅\n1. If a cluster loses all its points during the \"Assign\" phase, what happens to its center?\n2. Why does the Total Distance always decrease as $K$ increases?\n\n<details><summary>💡 Answers</summary>\n\n1. The mean of 0 points is undefined (division by zero)! You must handle this edge case (e.g. by re-assigning the center randomly, or keeping its old position).\n2. More clusters mean more centers spread throughout the data. Each point has a higher chance of having a center very close to it.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Euclidean Distance & Centroids\nGiven two points $A = [1, 2]$ and $B = [4, 6]$.\n1. Compute the Euclidean distance between them.\n2. Compute the mean center of the two points.\n*(Write code to do it for any N-dimensional points)*"),
cell("code","import math\n\ndef get_distance(p1, p2):\n    '''Return Euclidean distance between two vectors.'''\n    # YOUR CODE HERE\n    pass\n\ndef get_center(points):\n    '''Return the mean vector of a list of vectors.'''\n    if not points: return []\n    # YOUR CODE HERE\n    pass\n\n# assert get_distance([1, 2], [4, 6]) == 5.0\n# assert get_center([[1, 2], [4, 6]]) == [2.5, 4.0]"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Initialization\nWrite a function to randomly assign initial cluster labels to $N$ data points. Ensure every cluster $0$ to $K-1$ gets at least one point! (e.g. count off 0, 1, 2, 0, 1, 2, then shuffle)."),
cell("code","import random\ndef initialize_clusters(data, k):\n    '''Return a list of initial cluster labels (integers 0 to k-1) for each data point.'''\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Step 2: The K-Means Loop\nPut the initialization, assignment, and update steps together. Loop until the labels array doesn't change from the previous iteration."),
cell("code","def kmeans(data, k):\n    '''Return final labels and cluster centers.'''\n    labels = initialize_clusters(data, k)\n    centers = []\n    \n    while True:\n        # 1. Update centers based on current labels\n        # 2. Create new_labels by assigning each point to the nearest center\n        # 3. Check for convergence (if new_labels == labels: break)\n        # 4. labels = new_labels\n        # YOUR CODE HERE\n        break # remove this\n        \n    return labels, centers"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Elbow Plot\nWe need to compute the `total_cohesiveness` (sum of distances from each point to its assigned center).\nWrite a function `compute_total_distance(data, labels, centers)`.\nThen generate fake data, run k-means for $K=1$ to $K=10$, and plot the results."),
cell("code","import matplotlib.pyplot as plt\n\ndef compute_total_distance(data, labels, centers):\n    # YOUR CODE HERE\n    pass\n\n# Let's generate 3 clear blobs of data\nblob1 = [[random.gauss(0, 1), random.gauss(0, 1)] for _ in range(50)]\nblob2 = [[random.gauss(10, 1), random.gauss(10, 1)] for _ in range(50)]\nblob3 = [[random.gauss(0, 1), random.gauss(10, 1)] for _ in range(50)]\nfake_data = blob1 + blob2 + blob3\n\ndistances = []\nK_range = range(1, 10)\nfor k in K_range:\n    # labels, centers = kmeans(fake_data, k)\n    # dist = compute_total_distance(fake_data, labels, centers)\n    # distances.append(dist)\n    pass\n\n# plt.plot(K_range, distances, 'bo-')\n# plt.title(\"Elbow Method for K-Means\")\n# plt.xlabel(\"K\"); plt.ylabel(\"Total Distance\")\n# plt.show()"),
cell("markdown","### 🔍 Reflection\nWhere is the elbow in your plot? Given how we generated the fake data (3 distinct blobs), does the elbow align with $K=3$?"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: K-Means++ Initialization\nRandomly grouping points often results in slow convergence or getting trapped in local minima.\n**K-Means++** is a smarter initialization:\n1. Pick 1 random point as the first center.\n2. For each remaining point, compute its distance $D(x)$ to the nearest existing center.\n3. Pick the next center using Roulette Wheel Selection, where the probability of picking point $x$ is proportional to $D(x)^2$.\n4. Repeat until you have $K$ centers.\n\nImplement `kmeans_plus_plus(data, k)`."),
cell("code","# YOUR CODE HERE\npass"),
cell("markdown","### Chalkboard Defense\nExplain why K-Means++ initialization is vastly superior to purely random cluster assignment. What \"pathological\" starting state does it actively prevent?\n\n<details><summary>💡 Sketch</summary>\nRandom assignment might accidentally put two initial centers very close together inside the same data blob, while leaving another blob completely empty of centers. K-Means++ prevents this: because probabilities are proportional to distance squared, it actively seeks out data points that are *as far away as possible* from all existing centers, forcing the initial centers to spread out into the different natural clusters of the data.\n</details>\n\n---\n📚 **Next:** Algorithms 17 (Tic-Tac-Toe & Connect Four)")
    ]

def algo_17():
    return [
cell("markdown","# Algorithms 17: Tic-Tac-Toe\n\n**Learning Objectives:**\n1. Use Object-Oriented design to encapsulate game state\n2. Enforce rules via private methods and move validation\n3. Create Random and Manual Player classes that interact with the Game\n4. Develop logging and debugging tools for game history\n\n**Prerequisites:** Algorithms 01\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 17"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Game Development Architecture\n> 📖 *From Algorithms Ch. 17:* Develop a tic-tac-toe game in which two random players play against each other.\n\nWe need separation of concerns:\n- `Game` Class: Owns the 3x3 board. Knows the rules. Knows who won. Validates moves.\n- `Player` Class: Receives a *copy* of the board. Decides what move to play. Returns the move.\n\n**Crucial Security Rule:**\nPlayers should NOT update the board themselves! Otherwise, they could cheat. The Game asks the player for a move, the game verifies it is legal, and the game updates the board. If the move is illegal, the game skips the player's turn."),
cell("markdown","### Comprehension Check ✅\n1. Why must the Game pass a *copy* of the board to the Player, rather than the original board array?\n2. What is the difference between a `RandomPlayer` and a `ManualPlayer` in terms of class design?\n\n<details><summary>💡 Answers</summary>\n\n1. Array Referencing trap! If the game passes the original array, the Player can directly mutate it (e.g. `board[0][0] = 'X'`) bypassing all rule checks.\n2. They share the same interface (they both have a `get_move(board)` method), but `RandomPlayer` uses `random.choice`, while `ManualPlayer` uses Python's `input()` to ask the human.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Win Detection Logic\nBefore building classes, write the raw logic to check if a 3x3 board (represented as a 2D array of 'X', 'O', or ' ') has a winner."),
cell("code","def check_winner(board):\n    '''Return 'X', 'O', or None.'''\n    # Check 3 rows, 3 cols, 2 diagonals\n    # YOUR CODE HERE\n    pass\n\n# assert check_winner([['X','X','X'],[' ','O',' '],[' ',' ','O']]) == 'X'\n# print('Phase 0 passed ✅')"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The Player Classes\nImplement `RandomPlayer` and `ManualPlayer`. They must implement `get_move(board)` and return a tuple `(row, col)`."),
cell("code","import random\n\nclass RandomPlayer:\n    def __init__(self, piece):\n        self.piece = piece # 'X' or 'O'\n        \n    def get_move(self, board):\n        # Find all empty spaces ' '\n        # Return a random one as (row, col)\n        # YOUR CODE HERE\n        pass\n\nclass ManualPlayer:\n    def __init__(self, piece):\n        self.piece = piece\n        \n    def get_move(self, board):\n        # Print the board nicely\n        # Ask for input e.g. \"Enter row and col (0-2): \"\n        # Return (row, col)\n        # YOUR CODE HERE\n        pass"),
cell("markdown","### Step 2: The Game Class\nImplement the `Game` class. It takes `player1` and `player2`.\nImplement `run(self, log=True)` which loops until someone wins or the board is full (tie)."),
cell("code","class TicTacToe:\n    def __init__(self, player1, player2):\n        self.board = [[' ' for _ in range(3)] for _ in range(3)]\n        self.players = [player1, player2]\n        self.turn = 0\n        \n    def run(self, log=True):\n        while True:\n            current_player = self.players[self.turn % 2]\n            \n            # 1. Get move from player (pass a DEEP COPY of self.board!)\n            # 2. Check if move is legal (bounds check & space is empty)\n            # 3. If legal, update board. If illegal, print warning and skip turn.\n            # 4. Check for winner or tie. Break loop if game over.\n            # 5. self.turn += 1\n            # YOUR CODE HERE\n            break # Remove this\n\n# Run a simulation!\n# p1 = RandomPlayer('X')\n# p2 = RandomPlayer('O')\n# game = TicTacToe(p1, p2)\n# game.run(log=True)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Arena (Interleaved Practice)\nWrite a script that runs 1000 games of `RandomPlayer` vs `RandomPlayer` (with logging disabled!).\nCount the number of times X wins, O wins, and Ties occur. \n*(Since X goes first, X should win more often than O!)*"),
cell("code","def run_arena(trials=1000):\n    x_wins = 0\n    o_wins = 0\n    ties = 0\n    \n    # YOUR CODE HERE\n    \n    print(f\"X wins: {x_wins} | O wins: {o_wins} | Ties: {ties}\")\n\n# run_arena()"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Connect Four\nTic-Tac-Toe is a $3 \\times 3$ grid needing 3 in a row.\nConnect Four is a $6 \\times 7$ grid needing 4 in a row. Furthermore, gravity exists! Players choose a *column* (0-6), and the piece falls to the lowest available row in that column.\n\nClone your Tic-Tac-Toe game and modify it into Connect Four. The `check_winner` logic will be much harder!"),
cell("code","class ConnectFour:\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Chalkboard Defense\nExplain how you would write a `MinimaxPlayer` that never loses at Tic-Tac-Toe. What does the algorithm do conceptually?\n\n<details><summary>💡 Sketch</summary>\nMinimax generates a **Game Tree** of every possible future move. At the bottom of the tree, it scores wins as +1, losses as -1, and ties as 0.\nIt then percolates these scores back up the tree. When it is X's turn, X chooses the move that *maximizes* the score. When it is O's turn, O chooses the move that *minimizes* the score.\nBecause the search space of Tic-Tac-Toe is tiny ($< 362,880$ nodes), Minimax can see the end of the game from turn 1 and play perfectly.\n</details>\n\n---\n📚 **Next:** Algorithms 18 (Euler Estimation)")
    ]

if __name__=="__main__":
    save(algo_14(),os.path.join(OUT,"14_basic_matrix_arithmetic.ipynb"))
    save(algo_15(),os.path.join(OUT,"15_reduced_row_echelon_form.ipynb"))
    save(algo_16(),os.path.join(OUT,"16_k_means_clustering.ipynb"))
    save(algo_17(),os.path.join(OUT,"17_tic_tac_toe_connect_four.ipynb"))
    print("Notebooks 14, 15, 16, 17 done.")
