import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nimport math\nfrom collections import deque\nimport heapq\nprint('Ready ✅')")

def algo_31():
    return [
cell("markdown","# Algorithms 31: Breadth-First and Depth-First Search\n\n**Learning Objectives:**\n1. Represent a Graph using Adjacency Lists and Adjacency Matrices\n2. Implement Breadth-First Search (BFS) using a Queue\n3. Implement Depth-First Search (DFS) using a Stack or Recursion\n4. Differentiate the use-cases for BFS vs DFS\n\n**Prerequisites:** Algorithms 15\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 31"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Graph Representations\n> 📖 *From Algorithms Ch. 31:* A graph is a set of vertices (nodes) and edges (connections). Edges can be directed or undirected.\n\nTo represent a graph in code, we generally use an **Adjacency List** (a dictionary mapping each node to a list of its neighbors) or an **Adjacency Matrix** (a 2D grid where `matrix[i][j]` is 1 if an edge exists, 0 otherwise).\n\n### Graph Traversal: BFS vs DFS\nTo explore a graph, we need a systematic way to visit all reachable nodes without getting stuck in infinite loops.\n- **Breadth-First Search (BFS)**: Explores all neighbors of a node before moving deeper. It ripples outwards like a wave. It is guaranteed to find the *shortest path* in an unweighted graph. It uses a **Queue** (First-In, First-Out).\n- **Depth-First Search (DFS)**: Plunges as deep as possible down one path before backtracking. It is great for maze-solving and detecting cycles. It uses a **Stack** (Last-In, First-Out), which can be managed explicitly or via the recursive call stack."),
cell("markdown","### Comprehension Check ✅\nIf you want to find the fastest route out of a maze, should you use BFS or DFS? What if you want to find ALL possible routes out of the maze?\n\n<details><summary>💡 Answer</summary>\nUse **BFS** to find the absolute fastest route, because it naturally explores shorter paths before longer ones. Use **DFS** to exhaustively find all possible routes, because it easily traces single paths from start to finish and then backtracks.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Adjacency List to Matrix\nConvert the following adjacency list into a 2D adjacency matrix representation.\n`adj_list = {0: [1, 2], 1: [2], 2: [0, 3], 3: []}`"),
cell("code","def list_to_matrix(adj_list):\n    n = len(adj_list)\n    matrix = [[0] * n for _ in range(n)]\n    # Iterate through adj_list and populate matrix\n    # YOUR CODE HERE\n    return matrix\n\n# print(list_to_matrix({0: [1, 2], 1: [2], 2: [0, 3], 3: []}))"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Breadth-First Search (BFS)\nWrite a function `bfs(graph, start_node)` that prints out the nodes in BFS order.\nUse a `collections.deque` for $O(1)$ pop from the front, and a `set` to track `visited` nodes."),
cell("code","def bfs(graph, start):\n    queue = deque([start])\n    visited = set([start])\n    order = []\n    \n    while queue:\n        # 1. Pop from the LEFT of the queue\n        # curr = queue.popleft()\n        # 2. Add to order\n        # 3. For each neighbor of curr in graph:\n        #      If not visited, mark visited and append to queue\n        # YOUR CODE HERE\n        pass\n        \n    return order"),
cell("markdown","### Step 2: Depth-First Search (DFS)\nWrite `dfs(graph, start_node)`. \nYou can do this recursively, or iteratively by using a standard list as a stack (popping from the RIGHT). Let's do the iterative stack version."),
cell("code","def dfs(graph, start):\n    stack = [start]\n    visited = set()\n    order = []\n    \n    while stack:\n        # 1. Pop from the RIGHT of the stack\n        # curr = stack.pop()\n        # 2. If curr not in visited:\n        #      Mark visited, add to order\n        #      For each neighbor of curr in graph:\n        #          Append to stack\n        # YOUR CODE HERE\n        pass\n        \n    return order"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Traversing a Tree\nTest your algorithms on the following binary-tree-like graph!"),
cell("code","tree_graph = {\n    'A': ['B', 'C'],\n    'B': ['D', 'E'],\n    'C': ['F', 'G'],\n    'D': [], 'E': [], 'F': [], 'G': []\n}\n\n# print(\"BFS Order:\", bfs(tree_graph, 'A'))\n# print(\"DFS Order:\", dfs(tree_graph, 'A'))"),
cell("markdown","### 🔍 Reflection\nBFS should print `A, B, C, D, E, F, G` (level by level).\nDFS should plunge deep: `A, C, G, F, B, E, D` (assuming we push left-to-right, so we pop right-to-left!).\n\n---\n📚 **Next:** Algorithms 32-33 (Dijkstra's Algorithm)")
    ]

def algo_32_33():
    return [
cell("markdown","# Algorithms 32-33: Shortest Paths & Dijkstra's Algorithm\n\n**Learning Objectives:**\n1. Define Weighted Graphs\n2. Use a Priority Queue (Min-Heap)\n3. Implement Dijkstra's Algorithm to find the shortest path from a start node to all other nodes\n4. Track the actual path taken using a `previous` map\n\n**Prerequisites:** Algorithms 31\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapters 32-33"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Weighted Graphs\n> 📖 *From Algorithms Ch. 32:* In the real world, roads have speed limits and distances. Not all edges are equal! A weighted graph assigns a numerical cost to each edge.\n\nIn BFS, we assumed every edge had a cost of 1. To find the shortest path in a weighted graph, we must use **Dijkstra's Algorithm**.\n\n### Dijkstra's Algorithm\nDijkstra's algorithm is essentially BFS, but instead of a standard Queue, it uses a **Priority Queue**.\n1. We maintain a table of the shortest known `distance` to every node (initialized to infinity).\n2. We push `(0, start_node)` into the priority queue.\n3. While the queue is not empty, we pop the node with the *smallest distance*.\n4. For each neighbor, we calculate `new_dist = current_dist + edge_weight`.\n5. If `new_dist` is less than the neighbor's known `distance`, we update the table, set `previous[neighbor] = current_node`, and push `(new_dist, neighbor)` into the priority queue.\n\nBecause we always process the *closest* unvisited node, once we pop a node, we are mathematically guaranteed that we have found its absolute shortest path!"),
cell("markdown","### Comprehension Check ✅\nWhy can't Dijkstra's algorithm handle graphs with *negative* edge weights?\n\n<details><summary>💡 Answer</summary>\nDijkstra assumes that once a node is popped from the priority queue, its shortest path is permanently finalized. If there are negative weights, a longer path with more edges could suddenly drop in total cost, invalidating the \"finalized\" distances. Algorithms like Bellman-Ford are required for negative weights.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: The Min-Heap\nPython's `heapq` module implements a Priority Queue. `heapq.heappush(queue, item)` and `heapq.heappop(queue)`.\nWrite a function that takes an unsorted list of numbers, pushes them all into a heap, and then pops them out to return a sorted list! (This is called HeapSort)."),
cell("code","def heap_sort(nums):\n    heap = []\n    # YOUR CODE HERE\n    # push all nums into heap\n    # pop them all out into a sorted_list\n    # return sorted_list\n    pass\n\n# print(heap_sort([5, 2, 9, 1, 5, 6]))"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Dijkstra's Core Algorithm\nWrite `dijkstra(graph, start)`. The `graph` will be a dictionary like `{'A': {'B': 5, 'C': 2}}`.\nReturn two dictionaries: `distances` and `previous`."),
cell("code","def dijkstra(graph, start):\n    distances = {node: float('inf') for node in graph}\n    distances[start] = 0\n    previous = {node: None for node in graph}\n    \n    # Priority Queue: stores tuples of (distance, node)\n    pq = [(0, start)]\n    \n    while pq:\n        # 1. Pop the node with the smallest distance\n        # current_dist, current_node = heapq.heappop(pq)\n        \n        # 2. Ignore if we already found a better path earlier in the queue\n        # if current_dist > distances[current_node]: continue\n        \n        # 3. Check all neighbors\n        # for neighbor, weight in graph[current_node].items():\n        #     distance = current_dist + weight\n        #     If distance < distances[neighbor]:\n        #         Update distances[neighbor]\n        #         Update previous[neighbor]\n        #         Push (distance, neighbor) to pq\n        \n        # YOUR CODE HERE\n        pass\n        \n    return distances, previous"),
cell("markdown","### Step 2: Path Reconstruction\nWrite `reconstruct_path(previous, target)`. \nFollow the `previous` pointers from `target` back to `start`, then reverse the list."),
cell("code","def reconstruct_path(previous, target):\n    path = []\n    # curr = target\n    # while curr is not None:\n    #     path.append(curr)\n    #     curr = previous[curr]\n    # return path[::-1]\n    # YOUR CODE HERE\n    pass"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Highway System\nTest Dijkstra on this map!"),
cell("code","map_graph = {\n    'Seattle': {'Denver': 1300, 'SF': 800},\n    'SF': {'Seattle': 800, 'Denver': 1200, 'LA': 400},\n    'LA': {'SF': 400, 'Denver': 1000, 'Dallas': 1400},\n    'Denver': {'Seattle': 1300, 'SF': 1200, 'LA': 1000, 'Dallas': 800, 'Chicago': 1000},\n    'Dallas': {'LA': 1400, 'Denver': 800, 'NY': 1500},\n    'Chicago': {'Denver': 1000, 'NY': 800},\n    'NY': {'Chicago': 800, 'Dallas': 1500}\n}\n\n# distances, previous = dijkstra(map_graph, 'Seattle')\n# print(\"Distance to NY:\", distances['NY'])\n# print(\"Path to NY:\", reconstruct_path(previous, 'NY'))"),
cell("markdown","---\n📚 **Next:** Algorithms 34 (Decision Trees)")
    ]

def algo_34():
    return [
cell("markdown","# Algorithms 34: Decision Trees\n\n**Learning Objectives:**\n1. Formulate rules-based classification as a Tree structure\n2. Compute Shannon Entropy to measure dataset impurity\n3. Implement the recursive ID3 / CART algorithm to automatically grow a Decision Tree\n\n**Prerequisites:** Algorithms 29\n**Estimated time:** 120 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 34"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Rules-Based Classification\nKNN stores all data points. A **Decision Tree** compresses the data into a flowchart of Yes/No questions. \nFor example, to predict whether a customer will buy a product:\n- *Is Age > 30?*\n  - Yes: *Is Income > 50k?* -> Predict: **BUY**\n  - No: Predict: **DO NOT BUY**\n\n### How does the algorithm choose the questions?\nIt uses **Information Theory**. We want to ask the question that perfectly splits the data into pure groups (all BUYs on one side, all DO NOT BUYs on the other).\n\nWe measure impurity using **Shannon Entropy ($H$)**:\n$$H = - \\sum p_i \\log_2(p_i)$$\nwhere $p_i$ is the probability of class $i$ in the current subset of data.\n- If a group is 100% BUY, $H = 0$ (Perfectly pure, zero chaos/information).\n- If a group is 50% BUY / 50% DO NOT BUY, $H = 1$ (Maximum chaos/information).\n\n### Information Gain\nThe algorithm tests every possible split, and calculates the weighted average Entropy of the two resulting branches. \n**Information Gain = Current Entropy - Weighted Branch Entropy**\nThe algorithm greedily picks the split with the maximum Information Gain, and then recursively applies the process to the branches!"),
cell("markdown","### Comprehension Check ✅\nCalculate the Entropy of a dataset with 4 cats, 4 dogs. \nNow calculate the Entropy of a dataset with 8 cats, 0 dogs.\n\n<details><summary>💡 Answers</summary>\n\n1. 4 cats, 4 dogs: $p_{cat} = 0.5, p_{dog} = 0.5$. \n$H = -(0.5 \\log_2(0.5) + 0.5 \\log_2(0.5)) = -(-0.5 - 0.5) = 1.0$\n2. 8 cats: $p_{cat} = 1.0, p_{dog} = 0.0$. (By definition $0 \\log(0) = 0$).\n$H = -(1.0 \\log_2(1.0) + 0) = 0.0$\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Shannon Entropy Function\nWrite a function `entropy(labels)` that takes a list of class labels (e.g. `['cat', 'cat', 'dog']`) and computes $H$."),
cell("code","import math\nfrom collections import Counter\n\ndef entropy(labels):\n    if not labels: return 0.0\n    counts = Counter(labels)\n    h = 0.0\n    # For each count in counts.values():\n    # p = count / len(labels)\n    # h -= p * math.log2(p)\n    # YOUR CODE HERE\n    return h\n\n# assert entropy(['cat', 'dog', 'cat', 'dog']) == 1.0\n# assert entropy(['cat', 'cat']) == 0.0"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Splitting the Data\nWrite a function `split_data(data, feature_idx, threshold)` that splits a dataset based on a condition.\n`data` is a list of `(features_tuple, label)`. \nReturn `(left_data, right_data)` where `left` is $\\le$ threshold, `right` is $>$ threshold."),
cell("code","def split_data(data, feature_idx, threshold):\n    left, right = [], []\n    # YOUR CODE HERE\n    return left, right"),
cell("markdown","### Step 2: Finding the Best Split\nWrite a function `find_best_split(data)` that loops through every feature, and every possible threshold (every value seen in the dataset for that feature), and calculates Information Gain. Return the `(best_feature_idx, best_threshold)`. \n*(If the data is completely pure, return None)*"),
cell("code","def find_best_split(data):\n    best_gain = 0.0\n    best_split = None\n    current_entropy = entropy([label for _, label in data])\n    \n    if current_entropy == 0: return None\n    \n    num_features = len(data[0][0])\n    \n    for f_idx in range(num_features):\n        # Get all unique values for this feature to try as thresholds\n        thresholds = set(row[0][f_idx] for row in data)\n        \n        for t in thresholds:\n            left, right = split_data(data, f_idx, t)\n            if not left or not right: continue\n            \n            # Calculate weighted average entropy of children\n            p_left = len(left) / len(data)\n            p_right = len(right) / len(data)\n            child_entropy = p_left * entropy([l for _, l in left]) + p_right * entropy([l for _, l in right])\n            \n            gain = current_entropy - child_entropy\n            if gain > best_gain:\n                best_gain = gain\n                best_split = (f_idx, t)\n                \n    return best_split"),
cell("markdown","### Step 3: Building the Tree Recursively\nLet's define a `Node` class. Then `build_tree(data)` will recursively call `find_best_split`."),
cell("code","class Node:\n    def __init__(self, feature_idx=None, threshold=None, left=None, right=None, prediction=None):\n        self.feature_idx = feature_idx\n        self.threshold = threshold\n        self.left = left\n        self.right = right\n        self.prediction = prediction # Only set for leaf nodes\n\ndef build_tree(data, max_depth=5, current_depth=0):\n    # 1. Base cases: pure data, or max depth reached\n    labels = [l for _, l in data]\n    if len(set(labels)) == 1 or current_depth == max_depth:\n        return Node(prediction=Counter(labels).most_common(1)[0][0])\n        \n    # 2. Find best split\n    split = find_best_split(data)\n    if not split:\n        return Node(prediction=Counter(labels).most_common(1)[0][0])\n        \n    f_idx, t = split\n    left_data, right_data = split_data(data, f_idx, t)\n    \n    # 3. Recursively build branches\n    left_node = build_tree(left_data, max_depth, current_depth + 1)\n    right_node = build_tree(right_data, max_depth, current_depth + 1)\n    \n    return Node(feature_idx=f_idx, threshold=t, left=left_node, right=right_node)"),
cell("markdown","### Step 4: Inference\nWrite `predict_tree(node, point)` which drops a single point down the tree until it hits a leaf."),
cell("code","def predict_tree(node, point):\n    # If it's a leaf node, return prediction\n    # YOUR CODE HERE\n    pass\n    # Otherwise, check point[node.feature_idx] against node.threshold\n    # Recursively call predict_tree on left or right child\n    # YOUR CODE HERE"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The XOR Problem\nLet's test the tree on a dataset that linear models (like standard pseudoinverse) fail catastrophically on: the XOR logic gate!"),
cell("code","xor_data = [\n    ((0, 0), 0), ((0, 1), 1),\n    ((1, 0), 1), ((1, 1), 0)\n]\n\n# root = build_tree(xor_data)\n\n# print(\"Predict (0,0):\", predict_tree(root, (0,0))) # Should be 0\n# print(\"Predict (0,1):\", predict_tree(root, (0,1))) # Should be 1\n# print(\"Predict (1,0):\", predict_tree(root, (1,0))) # Should be 1\n# print(\"Predict (1,1):\", predict_tree(root, (1,1))) # Should be 0"),
cell("markdown","---\n📚 **Next:** Algorithms 35-36 (Neural Networks)")
    ]


if __name__=="__main__":
    save(algo_31(),os.path.join(OUT,"31_bfs_dfs.ipynb"))
    save(algo_32_33(),os.path.join(OUT,"32-33_shortest_paths_dijkstra.ipynb"))
    save(algo_34(),os.path.join(OUT,"34_decision_trees.ipynb"))
    print("Notebooks 31 to 34 generated.")
