import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nimport math\nimport random\nimport matplotlib.pyplot as plt\nprint('Ready ✅')")

def algo_26():
    return [
cell("markdown","# Algorithms 26: Overfitting, Underfitting, and Bias-Variance Tradeoff\n\n**Learning Objectives:**\n1. Understand why fitting a model to 100% accuracy on training data is dangerous\n2. Diagnose High Bias (Underfitting) vs High Variance (Overfitting)\n3. Implement Leave-One-Out Cross Validation to measure true generalization accuracy\n\n**Prerequisites:** Algorithms 23-25\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 26"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Problem with Training Accuracy\n> 📖 *From Algorithms Ch. 26:* If we define “accuracy” as simply matching with points in the dataset, then an 8th-degree polynomial is incredibly accurate. But it has to curve and contort itself in unrealistic ways between data points.\n\nImagine tracking a rocket's height over time. The sensor data is noisy.\n- A **Linear Regression** draws a perfectly straight line. It completely ignores that the rocket is accelerating upwards. This model is too rigid. It **Underfits** the data. This is an error due to **Bias** (the model stubbornly assumes the world is simple).\n- An **8th-Degree Polynomial** hits every single sensor point perfectly! But between seconds 9 and 10, the polynomial predicts the rocket shoots up to space, then crashes into the ground, then shoots back up. It trusts the noisy sensor data too much. This model is too flexible. It **Overfits** the data. This is an error due to **Variance** (the model drastically changes its shape depending on the exact points in the dataset).\n\n### The Solution: Cross Validation\nThe true test of a model is how well it predicts data it has *never seen before*. \nInstead of checking accuracy on the training data, we use **Leave-One-Out Cross Validation**:\n1. Remove 1 point from the dataset.\n2. Train the model on the remaining $N-1$ points.\n3. Ask the model to predict the 1 point we removed. Record the error.\n4. Put the point back, and repeat for every point in the dataset!\n\nThe sum of these errors is the true measure of generalization."),
cell("markdown","### Comprehension Check ✅\nAnthropomorphizing models can help intuition. The textbook says a high-bias model is \"dumb\" (cannot comprehend complexity). What is the analogy for a high-variance model?\n\n<details><summary>💡 Answer</summary>\nA high-variance model is \"paranoid\": it thinks it is seeing all sorts of complicated relationships that just aren't there (it treats random noise as ground truth).\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: The Cross-Validation Loop\nImagine we have a function `fit_and_predict(train_data, test_x)` that returns a predicted `y`.\nWrite the outer loop for Leave-One-Out Cross Validation to compute the **Residual Sum of Squares (RSS)**."),
cell("code","def pseudo_fit_and_predict(train_data, test_x):\n    # (Pretend this does linear regression)\n    return 0.0\n\ndef leave_one_out_cv(data):\n    total_rss = 0.0\n    for i in range(len(data)):\n        test_point = data[i]\n        # Create train_data by excluding data[i]\n        # train_data = data[:i] + data[i+1:]\n        # pred_y = pseudo_fit_and_predict(train_data, test_point[0])\n        # sq_error = (pred_y - test_point[1]) ** 2\n        # total_rss += sq_error\n        # YOUR CODE HERE\n        pass\n    return total_rss"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Linear vs Polynomial Fitting\nWe will use `numpy.polyfit` to fit polynomials for this experiment so we can focus on the CV logic rather than matrix inversion.\nWrite `evaluate_model(data, degree)` which fits a polynomial of `degree` on the training subset, and predicts the test point."),
cell("code","import numpy as np\n\ndef evaluate_model(data, degree):\n    total_rss = 0.0\n    for i in range(len(data)):\n        test_x, test_y = data[i]\n        train_data = data[:i] + data[i+1:]\n        \n        train_xs = [p[0] for p in train_data]\n        train_ys = [p[1] for p in train_data]\n        \n        # 1. Fit polynomial of `degree` (returns coefficients)\n        # coeffs = np.polyfit(train_xs, train_ys, degree)\n        # YOUR CODE HERE\n        \n        # 2. Evaluate the polynomial at test_x\n        # pred_y = np.polyval(coeffs, test_x)\n        # YOUR CODE HERE\n        \n        # 3. Add squared error to total_rss\n        # YOUR CODE HERE\n        pass\n        \n    return total_rss"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Rocket Dataset\nLet's test Degree 1 (Linear), Degree 2 (Quadratic), and Degree 8 (Overfit) on the noisy rocket dataset!"),
cell("code","# rocket_data = [\n#     (0, 0), (1, 10), (2, 20), (3, 50), (4, 35), (5, 100), \n#     (6, 110), (7, 190), (8, 150), (9, 260), (10, 270)\n# ]\n\n# rss_linear = evaluate_model(rocket_data, 1)\n# rss_quad = evaluate_model(rocket_data, 2)\n# rss_overfit = evaluate_model(rocket_data, 8)\n\n# print(f\"Linear (Deg 1) CV Error: {rss_linear:.0f}\")\n# print(f\"Quadratic (Deg 2) CV Error: {rss_quad:.0f}\")\n# print(f\"Polynomial (Deg 8) CV Error: {rss_overfit:.0f}\")"),
cell("markdown","### 🔍 Reflection\nThe 8th degree polynomial probably has near **zero** error on the training dataset, but its CV error is likely absolutely massive! The Quadratic model should have the lowest CV error, proving it is the true \"Goldilocks\" fit for this dataset.\n\n---\n📚 **Next:** Algorithms 27-28 (Regression via Gradient Descent)")
    ]

def algo_27_28():
    return [
cell("markdown","# Algorithms 27-28: Regression via Gradient Descent & Interaction Terms\n\n**Learning Objectives:**\n1. Formulate Logistic and Non-linear Regression without using the Pseudoinverse transform\n2. Define a loss function (Residual Sum of Squares)\n3. Compute partial derivatives to update weights using Gradient Descent\n4. Use Interaction Terms to model complex multi-variable relationships\n\n**Prerequisites:** Algorithms 26\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapters 27-28"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Problem with Pseudoinverse Transforms\n> 📖 *From Algorithms Ch. 27:* If we transform $y = a x^b$ using logarithms to apply the pseudoinverse, we find the optimal fit for the *transformed* equation, which is often NOT the optimal fit for the original equation! We must use Gradient Descent instead.\n\n### Gradient Descent for Regression\nTo fit a model using gradient descent, we construct an expression representing the error (RSS): \n$$RSS = \\sum (pred - y_{actual})^2$$\nFor a power regression $y = a \\cdot x^b$, the predicted value is $a \\cdot x^b$.\nWe take the partial derivative of RSS with respect to $a$ and $b$, and take small steps $-\\alpha \\nabla RSS$ to minimize the error!\n\n### Multiple Variables & Interaction Terms\nSuppose $x_1$ is \"scoops of peanut butter\" and $x_2$ is \"slices of roast beef\". \nA logistic model $y = \\frac{1}{1 + e^{-(a_1x_1 + a_2x_2 + b)}}$ predicts if someone likes the sandwich.\nIf both ingredients are good individually, $a_1 > 0, a_2 > 0$. \nBut if you combine PB & Beef, it tastes awful! Linear models cannot capture this. \nWe add an **Interaction Term** $x_1 x_2$:\n$$z = a_1x_1 + a_2x_2 + a_{12}(x_1x_2) + b$$\nThe algorithm will learn a *negative* weight for $a_{12}$ to drop the probability if both are present!"),
cell("markdown","### Comprehension Check ✅\nWhy do interaction terms vanish unless both variables are non-zero?\n\n<details><summary>💡 Answer</summary>\nBecause they are multiplied together ($x_1 \\cdot x_2$). If there is no peanut butter ($x_1 = 0$), then $0 \\cdot x_2 = 0$, so the interaction term completely disappears and has no effect on the prediction. It only activates when BOTH ingredients are present.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: The Logistic Derivative\nCompute the derivative of $\\sigma(z) = (1 + e^{-z})^{-1}$ with respect to $z$.\n\n<details><summary>💡 Solution</summary>\n$\\sigma'(z) = \\sigma(z) \\cdot (1 - \\sigma(z))$\n</details>"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The Prediction Function\nWrite `predict(weights, x1, x2)`. The `weights` list is `[a1, a2, a12, b]`. \nReturn the logistic probability."),
cell("code","def predict(weights, x1, x2):\n    a1, a2, a12, b = weights\n    # z = a1*x1 + a2*x2 + a12*(x1*x2) + b\n    # return 1 / (1 + math.exp(-z))\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Step 2: The Error Gradient\nFor $RSS = \\sum (pred - y)^2$, the derivative with respect to $w_i$ is:\n$$\\frac{\\partial E}{\\partial w_i} = \\sum 2 (pred - y) \\cdot pred \\cdot (1 - pred) \\cdot \\frac{\\partial z}{\\partial w_i}$$\nWhere $\\frac{\\partial z}{\\partial w_i}$ is the input variable for that weight (e.g. $x_1$, $x_2$, $x_1x_2$, or $1$)."),
cell("code","def compute_gradient(data, weights):\n    grad_a1, grad_a2, grad_a12, grad_b = 0, 0, 0, 0\n    \n    for x1, x2, y_actual in data:\n        # pred = predict(weights, x1, x2)\n        # diff = pred - y_actual\n        # multiplier = 2 * diff * pred * (1 - pred)\n        \n        # grad_a1 += multiplier * x1\n        # grad_a2 += multiplier * x2\n        # grad_a12 += multiplier * (x1 * x2)\n        # grad_b += multiplier * 1\n        # YOUR CODE HERE\n        pass\n        \n    return [grad_a1, grad_a2, grad_a12, grad_b]"),
cell("markdown","### Step 3: The Training Loop\nWrite `train_logistic(data, learning_rate=0.1, epochs=5000)`."),
cell("code","def train_logistic(data, learning_rate=0.1, epochs=5000):\n    weights = [0.0, 0.0, 0.0, 0.0]\n    # Loop epochs times, update weights -= learning_rate * gradient\n    # YOUR CODE HERE\n    return weights"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Sandwich Dataset\n`x1` = scoops of PB. `x2` = slices of Beef. `y` = 1 if liked, 0 if hated."),
cell("code","sandwich_data = [\n    (0, 0, 0), # Nothing: 0\n    (1, 0, 1), # Just PB: 1\n    (2, 0, 1), # Lots of PB: 1\n    (0, 1, 1), # Just Beef: 1\n    (0, 2, 1), # Lots of Beef: 1\n    (1, 1, 0), # PB and Beef: 0 (Yuck!)\n    (2, 2, 0), # Lots of both: 0 (Vomit!)\n]\n\n# weights = train_logistic(sandwich_data, learning_rate=0.5, epochs=10000)\n# print(\"Learned Weights [a1, a2, a12, b]:\")\n# print([round(w, 2) for w in weights])\n\n# print(\"\\nPredictions:\")\n# print(\"Just PB:\", round(predict(weights, 1, 0), 2))\n# print(\"Just Beef:\", round(predict(weights, 0, 1), 2))\n# print(\"PB + Beef:\", round(predict(weights, 1, 1), 2))"),
cell("markdown","---\n📚 **Next:** Algorithms 29 (K-Nearest Neighbors)")
    ]

def algo_29():
    return [
cell("markdown","# Algorithms 29: K-Nearest Neighbors\n\n**Learning Objectives:**\n1. Differentiate Regression from Classification\n2. Implement the K-Nearest Neighbors (KNN) classification algorithm\n3. Use Euclidean Distance to measure point similarity\n4. Use Leave-One-Out Cross Validation to choose the optimal hyperparameter $K$\n\n**Prerequisites:** Algorithms 26\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 29"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The K-Nearest Neighbors Algorithm\n> 📖 *From Algorithms Ch. 29:* Given a data set of points labeled with classes, KNN predicts the class of a new point by finding the $K$ points in the dataset nearest to the new point, and predicting the majority class of those neighbors.\n\nImagine we have a dataset of cookies: `(portion_butter, portion_sugar, type)`.\nType 0 is Shortbread, Type 1 is Sugar Cookie.\n\nIf we have a new cookie with `(0.25, 0.30)`, we compute the Euclidean distance $\\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$ to every cookie in our dataset. If $K=3$, we look at the 3 closest cookies. If 2 are Shortbread and 1 is Sugar, we predict Shortbread!\n\n### Choosing K\nWe use **Leave-One-Out Cross Validation** (from Chapter 26). For every point in the dataset, we pretend we don't know its label, and try to predict it using the *rest* of the dataset. We sum up the accuracy for each $K$, and pick the $K$ with the highest accuracy!"),
cell("markdown","### Comprehension Check ✅\nWhy is it mathematically dangerous to use KNN on a dataset where `Butter` is measured in tiny decimals like $0.05$ cups, but `Sugar` is measured in huge integers like $300$ grams?\n\n<details><summary>💡 Answer</summary>\nBecause the Euclidean distance formula treats all axes equally! A difference of $10$ grams of sugar will absolutely overwhelm a difference of $0.1$ cups of butter in the distance formula. The algorithm will essentially ignore the butter. We must **Normalize** all variables to a $0-1$ scale before running KNN.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Euclidean Distance\nWrite a function `distance(p1, p2)` that computes the Euclidean distance between two points (which can have any number of dimensions)."),
cell("code","import math\ndef distance(p1, p2):\n    # p1 and p2 are tuples/lists of numbers, e.g. (0.15, 0.2)\n    # YOUR CODE HERE\n    pass\n\n# assert abs(distance((0,0), (3,4)) - 5.0) < 1e-5"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The KNN Classifier\nWrite a function `predict_knn(training_data, new_point, k)`.\n`training_data` is a list of tuples: `((x, y), label)`.\nFind the distances, sort them, take the top $k$, and find the most common label."),
cell("code","def predict_knn(training_data, new_point, k):\n    distances = []\n    # 1. Loop through training_data. Compute distance to new_point.\n    # Append (dist, label) to distances list.\n    # YOUR CODE HERE\n    \n    # 2. Sort the distances list by the first element (the distance)\n    # YOUR CODE HERE\n    \n    # 3. Slice the top k elements. Extract their labels.\n    # YOUR CODE HERE\n    \n    # 4. Return the most common label. (In case of a tie, you can just pick the first one, or write logic to sum total distances of the tied classes!)\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Step 2: Leave-One-Out Cross Validation\nWrite a function `evaluate_knn(data, k)` that performs cross-validation and returns the accuracy (from 0.0 to 1.0)."),
cell("code","def evaluate_knn(data, k):\n    correct = 0\n    # For each point in data:\n    #   Remove it to form training_data\n    #   Call predict_knn on it\n    #   If prediction == actual label, correct += 1\n    \n    # YOUR CODE HERE\n    \n    return correct / len(data)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Finding the Best K\nHere is a synthetic dataset of cookies. Let's plot the accuracy for $K = 1, 2, \\dots, 9$."),
cell("code","cookie_data = [\n    ((0.15, 0.2), \"Shortbread\"), ((0.15, 0.3), \"Shortbread\"), ((0.2, 0.25), \"Shortbread\"),\n    ((0.25, 0.4), \"Shortbread\"), ((0.3, 0.35), \"Shortbread\"), \n    ((0.05, 0.25), \"Sugar\"), ((0.05, 0.35), \"Sugar\"), ((0.1, 0.3), \"Sugar\"), \n    ((0.15, 0.4), \"Sugar\"), ((0.25, 0.35), \"Sugar\")\n]\n\n# k_values = list(range(1, 10))\n# accuracies = [evaluate_knn(cookie_data, k) for k in k_values]\n\n# plt.plot(k_values, accuracies, marker='o')\n# plt.xlabel(\"K value\"); plt.ylabel(\"Cross-Validation Accuracy\")\n# plt.title(\"Bias-Variance Tradeoff in KNN\")\n# plt.grid(True); plt.show()"),
cell("markdown","---\n📚 **Next:** Algorithms 30 (Naive Bayes)")
    ]

def algo_30():
    return [
cell("markdown","# Algorithms 30: Naive Bayes Classification\n\n**Learning Objectives:**\n1. Formulate classification using Bayes' Theorem\n2. Understand the \"Naive\" independence assumption\n3. Implement a probabilisitic classifier that calculates $P(Class | Data)$\n\n**Prerequisites:** Algorithms 29\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 30"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Bayesian Probability\n> 📖 *From Algorithms Ch. 30:* Naive Bayes is grounded in Bayesian probability. It chooses the class with the highest conditional probability given the data point, assuming that all the variables in the dataset are independent from each other.\n\nFrom Bayes' Theorem: \n$$P(\\text{class} \\mid \\text{point}) = \\frac{P(\\text{point} \\mid \\text{class}) P(\\text{class})}{P(\\text{point})}$$\n\nSince $P(\\text{point})$ is the same for all classes, we just want to maximize the numerator: $P(\\text{point} \\mid \\text{class}) P(\\text{class})$.\n\n### The \"Naive\" Assumption\nA point has multiple features $(x_1, x_2, \\dots)$. Calculating the exact joint probability $P(x_1, x_2 \\mid \\text{class})$ is nearly impossible. \nBut if we Naively assume the features are strictly independent, we can multiply them!\n$$P(x_1, x_2 \\mid \\text{class}) \\approx P(x_1 \\mid \\text{class}) \\times P(x_2 \\mid \\text{class})$$\n\nThus, the formula becomes:\n$\\text{Score} = P(\\text{class}) \\times P(x_1 \\mid \\text{class}) \\times P(x_2 \\mid \\text{class})$\n\nThe algorithm computes this score for every possible class, and predicts the class with the highest score!"),
cell("markdown","### Comprehension Check ✅\nWhy is the independence assumption called \"Naive\"?\n\n<details><summary>💡 Answer</summary>\nBecause features in the real world are almost never perfectly independent! For example, if predicting whether an animal is a Dog, the feature \"Has Fur\" and \"Barks\" are heavily correlated. Treating them as independent statistical events is a mathematical fiction, but it turns out to work remarkably well in practice anyway.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Continuous Probability Density\nIf our features are continuous numbers (like height or weight), we use the Gaussian (Normal) Distribution PDF to estimate $P(x \\mid \\text{class})$:\n$$P(x \\mid \\mu, \\sigma) = \\frac{1}{\\sigma \\sqrt{2\\pi}} e^{-\\frac{1}{2} (\\frac{x - \\mu}{\\sigma})^2}$$\nWrite a function `gaussian_pdf(x, mean, stdev)`."),
cell("code","import math\ndef gaussian_pdf(x, mean, stdev):\n    # Prevent division by zero if stdev is exactly 0\n    if stdev == 0: stdev = 1e-6\n    # YOUR CODE HERE\n    pass\n\n# assert abs(gaussian_pdf(0, 0, 1) - 0.3989) < 1e-3"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Calculate Statistics\nWrite a function `summarize_by_class(dataset)` that groups the data by class, and for each class, computes the `(mean, stdev)` for each feature.\n`dataset` is `[(features_tuple, label)]`."),
cell("code","def mean(numbers):\n    return sum(numbers) / float(len(numbers))\n\ndef stdev(numbers):\n    avg = mean(numbers)\n    variance = sum((x - avg)**2 for x in numbers) / float(len(numbers) - 1 + 1e-6)\n    return math.sqrt(variance)\n\ndef summarize_by_class(dataset):\n    separated = {}\n    # 1. Group rows by class\n    for features, label in dataset:\n        if label not in separated:\n            separated[label] = []\n        separated[label].append(features)\n        \n    # 2. Compute (mean, stdev) for each feature in each class\n    summaries = {}\n    for label, rows in separated.items():\n        # ZIP trick to group columns: list(zip(*rows))\n        # YOUR CODE HERE\n        pass\n        \n    return summaries"),
cell("markdown","### Step 2: Prediction\nWrite `predict_naive_bayes(summaries, point)`.\nFor each class, compute $P(\\text{class}) \\times \\prod P(x_i \\mid \\text{mean}_i, \\text{stdev}_i)$.\nReturn the class with the highest probability score."),
cell("code","def predict_naive_bayes(summaries, total_rows, class_counts, point):\n    best_label, best_prob = None, -1\n    \n    # for label, class_summaries in summaries.items():\n    #     prob = class_counts[label] / total_rows # P(class)\n    #     for i in range(len(class_summaries)):\n    #         mean, stdev = class_summaries[i]\n    #         prob *= gaussian_pdf(point[i], mean, stdev) # P(xi | class)\n    #     \n    #     if best_label is None or prob > best_prob:\n    #         best_prob = prob\n    #         best_label = label\n            \n    # return best_label\n    pass"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Gender Dataset\nLet's predict gender based on `(Height(ft), Weight(lbs), Foot Size(in))`."),
cell("code","data = [\n    ((6.00, 180, 12), \"M\"), ((5.92, 190, 11), \"M\"), ((5.58, 170, 12), \"M\"), ((5.92, 165, 10), \"M\"),\n    ((5.00, 100, 6), \"F\"), ((5.50, 150, 8), \"F\"), ((5.42, 130, 7), \"F\"), ((5.75, 150, 9), \"F\")\n]\n\n# summaries = summarize_by_class(data)\n# class_counts = {\"M\": 4, \"F\": 4}\n\n# new_person = (6.0, 130, 8)\n# prediction = predict_naive_bayes(summaries, 8, class_counts, new_person)\n# print(\"Prediction for (6.0, 130, 8):\", prediction) # Should probably be Female due to weight and foot size!"),
cell("markdown","---\n📚 **Next:** Algorithms 31 (Breadth/Depth First Search)")
    ]

if __name__=="__main__":
    save(algo_26(),os.path.join(OUT,"26_overfitting_bias_variance.ipynb"))
    save(algo_27_28(),os.path.join(OUT,"27-28_regression_gradient_descent.ipynb"))
    save(algo_29(),os.path.join(OUT,"29_k_nearest_neighbors.ipynb"))
    save(algo_30(),os.path.join(OUT,"30_naive_bayes.ipynb"))
    print("Notebooks 26 to 30 generated.")
