import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nimport math\nimport random\nimport matplotlib.pyplot as plt\nprint('Ready ✅')")

def algo_29():
    return [
cell("markdown","# Algorithms 29: Logistic Regression via Gradient Descent\n\n**Learning Objectives:**\n1. Formulate Logistic Regression without using the Pseudoinverse transform\n2. Define a loss function (Residual Sum of Squares or Cross-Entropy)\n3. Compute partial derivatives to update weights using Gradient Descent\n4. Use Interaction Terms to model non-linear relationships\n\n**Prerequisites:** Algorithms 23-25, Algorithms 10-11\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapters 27-28"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Problem with Pseudoinverse Transforms\n> 📖 *From Algorithms Ch. 27:* If we transform $y = a x^b$ using logarithms to apply the pseudoinverse, we find the optimal fit for the *transformed* equation, which is often NOT the optimal fit for the original equation! We must use Gradient Descent instead.\n\n### The Logistic Model\nThe logistic curve smoothly maps any real number to a value between $0$ and $1$, making it perfect for predicting probabilities (like the probability someone likes a sandwich). \n$$y = \\sigma(z) = \\frac{1}{1 + e^{-z}}$$\nwhere $z$ is a linear combination of our inputs: $z = a_1x_1 + a_2x_2 + b$.\n\n### Interaction Terms\nSuppose $x_1$ is \"scoops of peanut butter\" and $x_2$ is \"slices of roast beef\". Both might taste good individually ($a_1 > 0, a_2 > 0$). But if you put them together on the same sandwich, it tastes awful! \nLinear combinations cannot model this \"together they are bad\" logic. We need an **Interaction Term** $x_1 x_2$.\n$$z = a_1x_1 + a_2x_2 + a_{12}(x_1x_2) + b$$\nThe algorithm will learn a *negative* weight for $a_{12}$ to drop the probability if both are present!"),
cell("markdown","### Comprehension Check ✅\nIf $z = 0$, what does the logistic function output? What does this mean in terms of probability?\n\n<details><summary>💡 Answer</summary>\n$\\sigma(0) = 1 / (1 + e^0) = 1 / 2 = 0.5$. It means the model is exactly 50% sure; a complete coin toss.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: The Logistic Derivative\nThe derivative of the logistic function $\\sigma(z)$ with respect to $z$ has a beautiful and simple property. It can be expressed entirely in terms of $\\sigma(z)$ itself!\nCompute the derivative of $\\sigma(z) = (1 + e^{-z})^{-1}$ using the chain rule.\n\n<details><summary>💡 Solution</summary>\n$\\sigma'(z) = -1 \\cdot (1 + e^{-z})^{-2} \\cdot (-e^{-z})$\n$\\sigma'(z) = \\frac{e^{-z}}{(1 + e^{-z})^2}$\n$\\sigma'(z) = \\frac{1}{1 + e^{-z}} \\cdot \\frac{e^{-z}}{1 + e^{-z}}$\n$\\sigma'(z) = \\sigma(z) \\cdot (1 - \\sigma(z))$\n</details>"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The Prediction Function\nWrite `predict(weights, x1, x2)`. The `weights` list is `[a1, a2, a12, b]`. \nReturn the logistic probability."),
cell("code","def predict(weights, x1, x2):\n    a1, a2, a12, b = weights\n    # z = a1*x1 + a2*x2 + a12*(x1*x2) + b\n    # return 1 / (1 + math.exp(-z))\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Step 2: The Error Gradient\nWe will use the **Residual Sum of Squares (RSS)** error function: $E = \\sum (\\text{pred} - y_{actual})^2$.\nTo update a weight $w_i$, we need $\\frac{\\partial E}{\\partial w_i}$.\nUsing the chain rule, for a single data point:\n$$\\frac{\\partial E}{\\partial w_i} = 2 (\\text{pred} - y) \\cdot \\text{pred} \\cdot (1 - \\text{pred}) \\cdot \\frac{\\partial z}{\\partial w_i}$$\nWhere $\\frac{\\partial z}{\\partial w_i}$ is simply the input variable attached to that weight (e.g., $x_1$ for $a_1$, or $1$ for $b$)."),
cell("code","def compute_gradient(data, weights):\n    grad_a1, grad_a2, grad_a12, grad_b = 0, 0, 0, 0\n    \n    for x1, x2, y_actual in data:\n        # pred = predict(weights, x1, x2)\n        # diff = pred - y_actual\n        # multiplier = 2 * diff * pred * (1 - pred)\n        \n        # grad_a1 += multiplier * x1\n        # grad_a2 += multiplier * x2\n        # grad_a12 += multiplier * (x1 * x2)\n        # grad_b += multiplier * 1\n        # YOUR CODE HERE\n        pass\n        \n    return [grad_a1, grad_a2, grad_a12, grad_b]"),
cell("markdown","### Step 3: The Training Loop\nWrite `train_logistic(data, learning_rate=0.1, epochs=5000)`.\nInitialize weights to 0. Loop `epochs` times, compute the gradient, and update weights: $w_i = w_i - \\alpha \\cdot \\text{grad}_i$."),
cell("code","def train_logistic(data, learning_rate=0.1, epochs=5000):\n    weights = [0.0, 0.0, 0.0, 0.0]\n    # YOUR CODE HERE\n    return weights"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Sandwich Dataset\nLet's test our interaction term on the Peanut Butter & Roast Beef dataset.\n`x1` = scoops of PB. `x2` = slices of Beef. `y` = 1 if liked, 0 if hated."),
cell("code","sandwich_data = [\n    (0, 0, 0), # Nothing: 0\n    (1, 0, 1), # Just PB: 1\n    (2, 0, 1), # Lots of PB: 1\n    (0, 1, 1), # Just Beef: 1\n    (0, 2, 1), # Lots of Beef: 1\n    (1, 1, 0), # PB and Beef: 0 (Yuck!)\n    (2, 2, 0), # Lots of both: 0 (Vomit!)\n]\n\n# weights = train_logistic(sandwich_data, learning_rate=0.5, epochs=10000)\n# print(\"Learned Weights [a1, a2, a12, b]:\")\n# print([round(w, 2) for w in weights])\n\n# print(\"\\nPredictions:\")\n# print(\"Just PB:\", round(predict(weights, 1, 0), 2))\n# print(\"Just Beef:\", round(predict(weights, 0, 1), 2))\n# print(\"PB + Beef:\", round(predict(weights, 1, 1), 2))"),
cell("markdown","### 🔍 Reflection\nLook at the learned weights. You should see that `a1` and `a2` are positive, but `a12` (the interaction weight) is strongly negative. The Gradient Descent algorithm independently \"learned\" that combining the ingredients is disgusting!"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Chalkboard Defense\nWhat happens to Logistic Regression using Gradient Descent if the data is *perfectly linearly separable* (e.g. all points with $x < 5$ are 0, and $x \\ge 5$ are 1) and we run gradient descent for an infinite number of epochs?\n\n<details><summary>💡 Sketch</summary>\nThe weights will approach **infinity**! \nTo make $\\sigma(z)$ perfectly output $1.0$ (instead of $0.9999$), $z$ must reach $\\infty$. To make it output perfectly $0.0$, $z$ must reach $-\\infty$. Thus, the algorithm will continuously increase the magnitude of the weights endlessly to make the logistic curve infinitely steep (a perfect step function). In practice, this leads to numerical overflow errors, which is why we often use **Regularization** (penalizing large weights in the error function) to stop them from growing to infinity.\n</details>\n\n---\n📚 **Next:** Algorithms 30-31 (Neural Networks)")
    ]

def algo_30_31():
    return [
cell("markdown","# Algorithms 30-31: Artificial Neural Networks\n\n**Learning Objectives:**\n1. Design a Multi-Layer Perceptron (MLP)\n2. Implement Forward Propagation using Matrix multiplications\n3. Implement Backpropagation to calculate gradients across hidden layers\n4. Train a neural network to solve the non-linear XOR problem\n\n**Prerequisites:** Algorithms 29\n**Estimated time:** 120 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning*"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### From Logistic Regression to Neural Networks\n> 📖 *From Algorithms:* A single logistic regression model is essentially a single \"neuron\". It takes inputs, computes a weighted sum, and passes it through a non-linear activation function.\n\nWhat if we hook up multiple neurons together? \n- The **Input Layer** receives raw data $(x_1, x_2)$.\n- The **Hidden Layer** consists of $N$ neurons. Each neuron acts as a logistic regression on the inputs, detecting different hidden \"features\".\n- The **Output Layer** is a final neuron that acts as a logistic regression on the *outputs of the hidden layer*.\n\nBy chaining linear combinations and non-linear activations, a Neural Network can approximate literally *any* mathematical function (Universal Approximation Theorem).\n\n### Backpropagation\nTo train this network via Gradient Descent, we need to know the error gradient for every single weight. \nFor the Output Layer weights, we just use the chain rule exactly like Phase 1 of the Logistic Regression notebook.\nFor the Hidden Layer weights, we use the chain rule again, propagating the error *backwards* from the output layer through the hidden layer's activation function. This algorithmic application of the Chain Rule is called **Backpropagation**."),
cell("markdown","### Comprehension Check ✅\nWhy is the non-linear activation function (like Logistic $\\sigma$, or ReLU) strictly required? What would happen if the neurons just did $z = a_1 x_1 + a_2 x_2$ and passed $z$ straight to the next layer?\n\n<details><summary>💡 Answer</summary>\nA linear combination of a linear combination is mathematically just a single linear combination. Without non-linear activation functions, a 100-layer neural network collapses into a simple $y = mx+b$ linear regression, and completely loses its ability to learn complex curves!\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: The Activation Function\nWrite the `sigmoid(x)` function, and its derivative `sigmoid_derivative(out)` where `out` is the pre-computed output of the sigmoid function (to save computation!)."),
cell("code","def sigmoid(x):\n    # YOUR CODE HERE\n    pass\n\ndef sigmoid_derivative(out):\n    # Remember from the previous notebook: sigma' = sigma * (1 - sigma)\n    # YOUR CODE HERE\n    pass"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Network Initialization\nWe will build a 2-Layer Network: \n- `input_size` = 2\n- `hidden_size` = 2\n- `output_size` = 1\n\nWe need weight matrices: `W1` (connects input to hidden) and `W2` (connects hidden to output). We also need bias vectors `b1` and `b2`.\nInitialize them with random values between -0.5 and 0.5."),
cell("code","class NeuralNetwork:\n    def __init__(self):\n        # W1: 2 inputs -> 2 hidden (2x2 matrix)\n        self.W1 = [[random.uniform(-0.5, 0.5) for _ in range(2)] for _ in range(2)]\n        self.b1 = [random.uniform(-0.5, 0.5) for _ in range(2)]\n        \n        # W2: 2 hidden -> 1 output (2x1 matrix)\n        self.W2 = [[random.uniform(-0.5, 0.5)] for _ in range(2)]\n        self.b2 = [random.uniform(-0.5, 0.5)]"),
cell("markdown","### Step 2: Forward Propagation\nPass a 1D list of inputs `X` (e.g. `[1.0, 0.0]`) through the network.\nCalculate `hidden_z`, then apply `sigmoid` to get `hidden_a`. \nCalculate `output_z`, then apply `sigmoid` to get `output_a`.\nReturn all of them, as they are needed for backpropagation!"),
cell("code","# Add to NeuralNetwork class\n# def forward(self, X):\n#     # 1. Hidden Layer\n#     hidden_a = [0.0, 0.0]\n#     for j in range(2):\n#         z = self.W1[0][j] * X[0] + self.W1[1][j] * X[1] + self.b1[j]\n#         hidden_a[j] = sigmoid(z)\n        \n#     # 2. Output Layer\n#     output_a = [0.0]\n#     z = self.W2[0][0] * hidden_a[0] + self.W2[1][0] * hidden_a[1] + self.b2[0]\n#     output_a[0] = sigmoid(z)\n    \n#     return hidden_a, output_a"),
cell("markdown","### Step 3: Backpropagation\nWe use Mean Squared Error (similar to RSS). \nThe error signal at the output is `(output_a - target) * sigmoid_derivative(output_a)`.\nThe error signal at a hidden node `j` is `(error_signal_out * W2[j][0]) * sigmoid_derivative(hidden_a[j])`.\nUpdate the weights: $W = W - \\text{lr} \\cdot \\text{signal} \\cdot \\text{input\\_to\\_that\\_weight}$"),
cell("code","# Add to NeuralNetwork class\n# def backward(self, X, target, hidden_a, output_a, lr=0.5):\n#     # 1. Output Layer Error\n#     out_error = (output_a[0] - target) * sigmoid_derivative(output_a[0])\n    \n#     # 2. Hidden Layer Errors\n#     hid_error = [0.0, 0.0]\n#     for j in range(2):\n#         hid_error[j] = (out_error * self.W2[j][0]) * sigmoid_derivative(hidden_a[j])\n        \n#     # 3. Update W2 and b2\n#     for j in range(2):\n#         self.W2[j][0] -= lr * out_error * hidden_a[j]\n#     self.b2[0] -= lr * out_error\n    \n#     # 4. Update W1 and b1\n#     for i in range(2):\n#         for j in range(2):\n#             self.W1[i][j] -= lr * hid_error[j] * X[i]\n#     for j in range(2):\n#         self.b1[j] -= lr * hid_error[j]"),
cell("markdown","### Step 4: Training Loop\nLoop through epochs, passing each datapoint through `forward` and `backward`."),
cell("code","# Add to NeuralNetwork class\n# def train(self, data, epochs=10000, lr=0.5):\n#     for epoch in range(epochs):\n#         for X, target in data:\n#             hidden_a, output_a = self.forward(X)\n#             self.backward(X, target, hidden_a, output_a, lr)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The XOR Problem Revisited\nIn Algorithms 27, we saw that a single linear/logistic layer CANNOT solve the XOR problem. \nLet's prove our Neural Network can!"),
cell("code","# xor_data = [\n#     ([0, 0], 0),\n#     ([0, 1], 1),\n#     ([1, 0], 1),\n#     ([1, 1], 0)\n# ]\n\n# nn = NeuralNetwork()\n# nn.train(xor_data, epochs=10000, lr=0.5)\n\n# print(\"Predictions after training:\")\n# for X, target in xor_data:\n#     _, out = nn.forward(X)\n#     print(f\"X={X} -> Pred: {out[0]:.3f} (Target: {target})\")"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Chalkboard Defense\nWhat is the **Vanishing Gradient** problem? Why did modern Deep Learning shift from using the `Sigmoid` activation function to using `ReLU` (Rectified Linear Unit, $f(x) = \\max(0, x)$)?\n\n<details><summary>💡 Sketch</summary>\nThe derivative of Sigmoid is highly peaked at $0$, but asymptotically approaches $0$ everywhere else. \nDuring Backpropagation, the error signal is repeatedly multiplied by the activation derivative at each layer. If the network is 50 layers deep, you are multiplying by tiny decimals 50 times. By the time the error signal reaches the first layer, the gradient is essentially `0.000000`, so the first layer never updates its weights! \nReLU's derivative is literally just $1$ (if $x > 0$). Multiplying by $1$ fifty times preserves the error signal perfectly, allowing researchers to train ultra-deep networks for the first time in the 2010s.\n</details>\n\n---\n📚 **Next:** Algorithms 32 (Graph Theory & Shortest Paths)")
    ]

if __name__=="__main__":
    save(algo_29(),os.path.join(OUT,"29_logistic_regression.ipynb"))
    save(algo_30_31(),os.path.join(OUT,"30-31_neural_networks.ipynb"))
    print("Notebooks 29 to 31 generated.")
