import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nimport math\nimport matplotlib.pyplot as plt\nprint('Ready ✅')")

def algo_23_25():
    return [
cell("markdown","# Algorithms 23-25: Regression via Pseudoinverse\n\n**Learning Objectives:**\n1. Formulate curve-fitting as an overdetermined system of linear equations $y = Xp$\n2. Use the Pseudoinverse $(X^T X)^{-1} X^T$ to find the optimal least-squares parameters $p$\n3. Extend the pseudoinverse to fit Polynomial, Multiple Linear, Power, Exponential, and Logistic models via algebraic transformation\n\n**Prerequisites:** Algorithms 15 (RREF/Matrix Inversion)\n**Estimated time:** 120 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapters 23-25"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Supervised Learning Problem\n> 📖 *From Algorithms Ch. 23:* Supervised learning consists of fitting functions to data sets. We want to come up with a mathematical model that predicts outputs for other inputs.\n\nGiven data `[(0, 1), (2, 5), (4, 3)]`, we want to fit a line $y = mx + b$. We can plug each point into the equation:\n$1 = m(0) + b$\n$5 = m(2) + b$\n$3 = m(4) + b$\n\nThis is an overdetermined system (3 equations, 2 unknowns). There is no perfect solution. In matrix form, $y = Xp$:\n$\\begin{bmatrix} 1 \\\\ 5 \\\\ 3 \\end{bmatrix} = \\begin{bmatrix} 0 & 1 \\\\ 2 & 1 \\\\ 4 & 1 \\end{bmatrix} \\begin{bmatrix} m \\\\ b \\end{bmatrix}$\n\n### The Pseudoinverse\nBecause $X$ is tall and rectangular, it has no inverse. But if we multiply both sides by $X^T$, we project the problem into a square matrix space!\n$X^T y = X^T X p$\n\nNow, $X^T X$ is a square matrix (in this case $2 \\times 2$). If its columns are independent, it is invertible!\n$p = (X^T X)^{-1} X^T y$\n\nThis magical formula guarantees the mathematically optimal least-squares fit for *any* linear combination of functions!"),
cell("markdown","### Comprehension Check ✅\nHow would you set up the $X$ matrix to fit a quadratic model $y = ax^2 + bx + c$ to the same three points?\n\n<details><summary>💡 Answer</summary>\n\nEach row in $X$ would have 3 columns: $x^2$, $x$, and $1$.\n$\\begin{bmatrix} 1 \\\\ 5 \\\\ 3 \\end{bmatrix} = \\begin{bmatrix} 0^2 & 0 & 1 \\\\ 2^2 & 2 & 1 \\\\ 4^2 & 4 & 1 \\end{bmatrix} \\begin{bmatrix} a \\\\ b \\\\ c \\end{bmatrix}$\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Non-Linear Transformations\nThe pseudoinverse can only solve models of the form $y = c_1 f_1(x) + c_2 f_2(x) + \\dots$.\nIf we want to fit a **Power Regression** $y = a \\cdot x^b$, we must transform it.\nTake the natural logarithm of both sides and expand the right side using logarithm rules.\nWhat does the equation look like now? What are the new \"variables\" and \"constants\"?\n\n<details><summary>💡 Answer</summary>\n\n$\\ln(y) = \\ln(a \\cdot x^b)$\n$\\ln(y) = \\ln(a) + b \\ln(x)$\n\nLet $Y = \\ln(y)$ and $X_{new} = \\ln(x)$. The equation is $Y = b X_{new} + \\ln(a)$, which is a straight line! We can solve for $b$ and $\\ln(a)$ using the pseudoinverse on the transformed data.\n</details>"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The Matrix Class (Refresher)\nTo do this, we need matrix multiplication, transpose, and inverse. Bring over your `Matrix` class from Algorithms 15. \n*(For the sake of time in this lab, you may use a simplified list-of-lists approach or a basic pure-Python matrix library if you already built one. Here is a starter.)*"),
cell("code","class Matrix:\n    def __init__(self, data):\n        self.data = data\n        self.rows = len(data)\n        self.cols = len(data[0])\n        \n    def transpose(self):\n        return Matrix([[self.data[r][c] for r in range(self.rows)] for c in range(self.cols)])\n        \n    def multiply(self, other):\n        result = [[sum(self.data[r][k] * other.data[k][c] for k in range(self.cols)) \n                   for c in range(other.cols)] for r in range(self.rows)]\n        return Matrix(result)\n        \n    # We need an inverse method! For 2x2, there is a simple formula:\n    def inverse_2x2(self):\n        a, b = self.data[0][0], self.data[0][1]\n        c, d = self.data[1][0], self.data[1][1]\n        det = a*d - b*c\n        return Matrix([[d/det, -b/det], [-c/det, a/det]])"),
cell("markdown","### Step 2: Linear Regression Solver\nWrite a function `fit_linear(points)` that takes a list of `(x, y)` tuples and returns `(m, b)`."),
cell("code","def fit_linear(points):\n    # 1. Construct X and Y matrices\n    # X should be [[x1, 1], [x2, 1], ...]\n    # Y should be [[y1], [y2], ...]\n    # YOUR CODE HERE\n    \n    # 2. Compute X_T = X.transpose()\n    # 3. Compute X_T_X = X_T.multiply(X)\n    # 4. Compute X_T_X_inv = X_T_X.inverse_2x2()\n    # 5. Compute X_T_Y = X_T.multiply(Y)\n    # 6. Compute p = X_T_X_inv.multiply(X_T_Y)\n    # return (p.data[0][0], p.data[1][0]) # (m, b)\n    pass"),
cell("markdown","### Step 3: Exponential Regression Solver\nWrite a function `fit_exponential(points)` that fits $y = a \\cdot b^x$.\nTransform the data, use `fit_linear`, and then reverse the transformation to find $a$ and $b$."),
cell("code","def fit_exponential(points):\n    # y = a * b^x  =>  ln(y) = ln(a) + x * ln(b)\n    # This is a line: Y = m*X + B, where Y = ln(y), m = ln(b), X = x, B = ln(a)\n    \n    # 1. Transform the points: (x, y) -> (x, ln(y))\n    # YOUR CODE HERE\n    \n    # 2. Call fit_linear on the transformed points to get (m, B)\n    # YOUR CODE HERE\n    \n    # 3. Reverse the transformation:\n    # b = math.exp(m)\n    # a = math.exp(B)\n    # return (a, b)\n    pass"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Fitting and Plotting\nTest your algorithms on the dataset `[(1, 2), (2, 4), (3, 7), (4, 15), (5, 30)]`.\nPlot the data points as a scatter plot. Then, generate $X$ values from 1 to 5, compute the predicted $Y$ values using your exponential model, and plot the curve!"),
cell("code","# data = [(1, 2), (2, 4), (3, 7), (4, 15), (5, 30)]\n# a, b = fit_exponential(data)\n# print(f\"Model: y = {a:.3f} * {b:.3f}^x\")\n\n# xs = [p[0] for p in data]\n# ys = [p[1] for p in data]\n# plt.scatter(xs, ys, color='red', label=\"Data\")\n\n# plot_xs = [1 + i*0.1 for i in range(41)]\n# plot_ys = [a * (b**x) for x in plot_xs]\n# plt.plot(plot_xs, plot_ys, color='blue', label=\"Exponential Fit\")\n\n# plt.legend(); plt.grid(True); plt.show()"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### The Danger of Transformation\n> 📖 *From Algorithms Ch. 25:* If we transform $y = a x^b$ into $\\ln(y) = \\ln(a) + b \\ln(x)$, the pseudoinverse finds the absolute mathematically optimal fit for the *transformed* equation. It does **NOT** guarantee the optimal fit for the *original* equation!\n\nThis is because distances are warped by the logarithm. An error of $100$ at $y=1000$ looks like a tiny error in $\\ln(y)$ space, while an error of $1$ at $y=2$ looks huge in $\\ln(y)$ space! \n\nHow could we solve for the parameters of $y = a x^b$ WITHOUT transforming the equation, ensuring we get the true optimal fit in the original space?\n\n<details><summary>💡 Sketch</summary>\nWe cannot use the exact algebraic pseudoinverse formula, because the equation is strictly non-linear with respect to its parameters. \nInstead, we must formulate an error function $E(a, b) = \\sum (a x_i^b - y_i)^2$, compute the partial derivatives $\\frac{\\partial E}{\\partial a}$ and $\\frac{\\partial E}{\\partial b}$, and use **Gradient Descent** (Chapter 27) to walk down the 3D error surface until we find the minimum!\n</details>\n\n---\n📚 **Next:** Algorithms 26 (K-Nearest Neighbors)")
    ]

def algo_26():
    return [
cell("markdown","# Algorithms 26: K-Nearest Neighbors & Cross Validation\n\n**Learning Objectives:**\n1. Differentiate Regression (predicting numbers) from Classification (predicting categories)\n2. Implement the K-Nearest Neighbors (KNN) classification algorithm\n3. Understand Overfitting, Underfitting, and the Bias-Variance Tradeoff\n4. Use Leave-One-Out Cross Validation to choose the optimal hyperparameter $K$\n\n**Prerequisites:** Algorithms 23-25\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapters 26 & 29"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The K-Nearest Neighbors Algorithm\n> 📖 *From Algorithms Ch. 29:* Given a data set of points labeled with classes, KNN predicts the class of a new point by finding the $K$ points in the dataset nearest to the new point, and predicting the majority class of those neighbors.\n\nImagine we have a dataset of cookies: `(portion_butter, portion_sugar, type)`.\nType 0 is Shortbread, Type 1 is Sugar Cookie.\n\nIf we have a new cookie with `(0.25, 0.30)`, we compute the Euclidean distance $\\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$ to every cookie in our dataset. If $K=3$, we look at the 3 closest cookies. If 2 are Shortbread and 1 is Sugar, we predict Shortbread!\n\n### The Bias-Variance Tradeoff & Cross Validation\nHow do we choose $K$?\n- If $K=1$, the model is extremely paranoid and flexible. It trusts individual, noisy data points too much (**High Variance, Overfitting**).\n- If $K=N$ (the whole dataset), the model is extremely rigid. It just predicts the most common cookie type in the whole dataset, ignoring the $x, y$ coordinates entirely (**High Bias, Underfitting**).\n\nTo find the \"Goldilocks\" $K$, we use **Leave-One-Out Cross Validation**. For every point in the dataset, we pretend we don't know its label, and try to predict it using the *rest* of the dataset. We sum up the accuracy for each $K$, and pick the $K$ with the highest accuracy!"),
cell("markdown","### Comprehension Check ✅\nWhy is it mathematically dangerous to use KNN on a dataset where `Butter` is measured in tiny decimals like $0.05$ cups, but `Sugar` is measured in huge integers like $300$ grams?\n\n<details><summary>💡 Answer</summary>\nBecause the Euclidean distance formula treats all axes equally! A difference of $10$ grams of sugar will absolutely overwhelm a difference of $0.1$ cups of butter in the distance formula. The algorithm will essentially ignore the butter. We must **Normalize** all variables to a $0-1$ scale before running KNN.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Euclidean Distance\nWrite a function `distance(p1, p2)` that computes the Euclidean distance between two points (which can have any number of dimensions)."),
cell("code","import math\ndef distance(p1, p2):\n    # p1 and p2 are tuples/lists of numbers, e.g. (0.15, 0.2)\n    # YOUR CODE HERE\n    pass\n\n# assert abs(distance((0,0), (3,4)) - 5.0) < 1e-5"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The KNN Classifier\nWrite a function `predict_knn(training_data, new_point, k)`.\n`training_data` is a list of tuples: `((x, y), label)`.\nFind the distances, sort them, take the top $k$, and find the most common label."),
cell("code","def predict_knn(training_data, new_point, k):\n    distances = []\n    # 1. Loop through training_data. Compute distance to new_point.\n    # Append (dist, label) to distances list.\n    # YOUR CODE HERE\n    \n    # 2. Sort the distances list by the first element (the distance)\n    # YOUR CODE HERE\n    \n    # 3. Slice the top k elements. Extract their labels.\n    # YOUR CODE HERE\n    \n    # 4. Return the most common label. (In case of a tie, you can just pick the first one, or write logic to sum total distances of the tied classes!)\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Step 2: Leave-One-Out Cross Validation\nWrite a function `evaluate_knn(data, k)` that performs cross-validation and returns the accuracy (from 0.0 to 1.0)."),
cell("code","def evaluate_knn(data, k):\n    correct = 0\n    # For each point in data:\n    #   Remove it to form training_data\n    #   Call predict_knn on it\n    #   If prediction == actual label, correct += 1\n    \n    # YOUR CODE HERE\n    \n    return correct / len(data)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Finding the Best K\nHere is a synthetic dataset of cookies. Let's plot the accuracy for $K = 1, 2, \\dots, 9$."),
cell("code","cookie_data = [\n    ((0.15, 0.2), \"Shortbread\"), ((0.15, 0.3), \"Shortbread\"), ((0.2, 0.25), \"Shortbread\"),\n    ((0.25, 0.4), \"Shortbread\"), ((0.3, 0.35), \"Shortbread\"), \n    ((0.05, 0.25), \"Sugar\"), ((0.05, 0.35), \"Sugar\"), ((0.1, 0.3), \"Sugar\"), \n    ((0.15, 0.4), \"Sugar\"), ((0.25, 0.35), \"Sugar\")\n]\n\n# k_values = list(range(1, 10))\n# accuracies = [evaluate_knn(cookie_data, k) for k in k_values]\n\n# plt.plot(k_values, accuracies, marker='o')\n# plt.xlabel(\"K value\"); plt.ylabel(\"Cross-Validation Accuracy\")\n# plt.title(\"Bias-Variance Tradeoff in KNN\")\n# plt.grid(True); plt.show()"),
cell("markdown","### 🔍 Reflection\nLook at your graph. For this specific dataset, what $K$ values yield the highest accuracy? \n*(You should see that $K=3$ and $K=4$ are the peaks. Extreme low or high values drop off!)*"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Chalkboard Defense\nWhat is the Time Complexity of making a *single prediction* in KNN if your training dataset has $N$ points, each with $D$ dimensions? \nWhy might this be a massive problem for real-world applications like Face Recognition on iPhones (where $D = 100,000$ pixels, and $N = 1,000,000$ photos), and how do algorithms like SVM or Neural Networks bypass this specific bottleneck?\n\n<details><summary>💡 Sketch</summary>\nThe time complexity is $O(N \\cdot D)$ because you must compute the distance to *every single point in the training set* at inference time! This makes KNN a \"Lazy Learner\". It does zero work during training, but extreme amounts of work during inference.\nNeural Networks do the opposite: they take hours to train (compressing the $N$ points into a matrix of weights), but during inference, they just do a few matrix multiplications $O(W)$, entirely independent of the dataset size $N$. This allows instant Face ID unlock!\n</details>\n\n---\n📚 **Next:** Algorithms 27-28 (Decision Trees)")
    ]

def algo_27_28():
    return [
cell("markdown","# Algorithms 27-28: Decision Trees & Entropy\n\n**Learning Objectives:**\n1. Formulate rules-based classification as a Tree structure\n2. Compute Shannon Entropy to measure dataset impurity\n3. Implement the recursive ID3 / CART algorithm to automatically grow a Decision Tree\n\n**Prerequisites:** Algorithms 26\n**Estimated time:** 120 minutes"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Rules-Based Classification\nKNN stores all data points. A **Decision Tree** compresses the data into a flowchart of Yes/No questions. \nFor example, to predict whether a customer will buy a product:\n- *Is Age > 30?*\n  - Yes: *Is Income > 50k?* -> Predict: **BUY**\n  - No: Predict: **DO NOT BUY**\n\n### How does the algorithm choose the questions?\nIt uses **Information Theory**. We want to ask the question that perfectly splits the data into pure groups (all BUYs on one side, all DO NOT BUYs on the other).\n\nWe measure impurity using **Shannon Entropy ($H$)**:\n$$H = - \\sum p_i \\log_2(p_i)$$\nwhere $p_i$ is the probability of class $i$ in the current subset of data.\n- If a group is 100% BUY, $H = 0$ (Perfectly pure, zero chaos/information).\n- If a group is 50% BUY / 50% DO NOT BUY, $H = 1$ (Maximum chaos/information).\n\n### Information Gain\nThe algorithm tests every possible split, and calculates the weighted average Entropy of the two resulting branches. \n**Information Gain = Current Entropy - Weighted Branch Entropy**\nThe algorithm greedily picks the split with the maximum Information Gain, and then recursively applies the process to the branches!"),
cell("markdown","### Comprehension Check ✅\nCalculate the Entropy of a dataset with 4 cats, 4 dogs. \nNow calculate the Entropy of a dataset with 8 cats, 0 dogs.\n\n<details><summary>💡 Answers</summary>\n\n1. 4 cats, 4 dogs: $p_{cat} = 0.5, p_{dog} = 0.5$. \n$H = -(0.5 \\log_2(0.5) + 0.5 \\log_2(0.5)) = -(-0.5 - 0.5) = 1.0$\n2. 8 cats: $p_{cat} = 1.0, p_{dog} = 0.0$. (By definition $0 \\log(0) = 0$).\n$H = -(1.0 \\log_2(1.0) + 0) = 0.0$\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Shannon Entropy Function\nWrite a function `entropy(labels)` that takes a list of class labels (e.g. `['cat', 'cat', 'dog']`) and computes $H$."),
cell("code","import math\nfrom collections import Counter\n\ndef entropy(labels):\n    if not labels: return 0.0\n    counts = Counter(labels)\n    h = 0.0\n    # For each count in counts.values():\n    # p = count / len(labels)\n    # h -= p * math.log2(p)\n    # YOUR CODE HERE\n    return h\n\n# assert entropy(['cat', 'dog', 'cat', 'dog']) == 1.0\n# assert entropy(['cat', 'cat']) == 0.0"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Splitting the Data\nWrite a function `split_data(data, feature_idx, threshold)` that splits a dataset based on a condition.\n`data` is a list of `(features_tuple, label)`. \nReturn `(left_data, right_data)` where `left` is $\\le$ threshold, `right` is $>$ threshold."),
cell("code","def split_data(data, feature_idx, threshold):\n    left, right = [], []\n    # YOUR CODE HERE\n    return left, right"),
cell("markdown","### Step 2: Finding the Best Split\nWrite a function `find_best_split(data)` that loops through every feature, and every possible threshold (every value seen in the dataset for that feature), and calculates Information Gain. Return the `(best_feature_idx, best_threshold)`. \n*(If the data is completely pure, return None)*"),
cell("code","def find_best_split(data):\n    best_gain = 0.0\n    best_split = None\n    current_entropy = entropy([label for _, label in data])\n    \n    if current_entropy == 0: return None\n    \n    num_features = len(data[0][0])\n    \n    for f_idx in range(num_features):\n        # Get all unique values for this feature to try as thresholds\n        thresholds = set(row[0][f_idx] for row in data)\n        \n        for t in thresholds:\n            left, right = split_data(data, f_idx, t)\n            if not left or not right: continue\n            \n            # Calculate weighted average entropy of children\n            p_left = len(left) / len(data)\n            p_right = len(right) / len(data)\n            child_entropy = p_left * entropy([l for _, l in left]) + p_right * entropy([l for _, l in right])\n            \n            gain = current_entropy - child_entropy\n            if gain > best_gain:\n                best_gain = gain\n                best_split = (f_idx, t)\n                \n    return best_split"),
cell("markdown","### Step 3: Building the Tree Recursively\nLet's define a `Node` class. Then `build_tree(data)` will recursively call `find_best_split`."),
cell("code","class Node:\n    def __init__(self, feature_idx=None, threshold=None, left=None, right=None, prediction=None):\n        self.feature_idx = feature_idx\n        self.threshold = threshold\n        self.left = left\n        self.right = right\n        self.prediction = prediction # Only set for leaf nodes\n\ndef build_tree(data, max_depth=5, current_depth=0):\n    # 1. Base cases: pure data, or max depth reached\n    labels = [l for _, l in data]\n    if len(set(labels)) == 1 or current_depth == max_depth:\n        return Node(prediction=Counter(labels).most_common(1)[0][0])\n        \n    # 2. Find best split\n    split = find_best_split(data)\n    if not split:\n        return Node(prediction=Counter(labels).most_common(1)[0][0])\n        \n    f_idx, t = split\n    left_data, right_data = split_data(data, f_idx, t)\n    \n    # 3. Recursively build branches\n    left_node = build_tree(left_data, max_depth, current_depth + 1)\n    right_node = build_tree(right_data, max_depth, current_depth + 1)\n    \n    return Node(feature_idx=f_idx, threshold=t, left=left_node, right=right_node)"),
cell("markdown","### Step 4: Inference\nWrite `predict_tree(node, point)` which drops a single point down the tree until it hits a leaf."),
cell("code","def predict_tree(node, point):\n    # If it's a leaf node, return prediction\n    # YOUR CODE HERE\n    pass\n    # Otherwise, check point[node.feature_idx] against node.threshold\n    # Recursively call predict_tree on left or right child\n    # YOUR CODE HERE"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The XOR Problem\nLet's test the tree on a dataset that linear models (like standard pseudoinverse) fail catastrophically on: the XOR logic gate!"),
cell("code","xor_data = [\n    ((0, 0), 0), ((0, 1), 1),\n    ((1, 0), 1), ((1, 1), 0)\n]\n\n# root = build_tree(xor_data)\n\n# print(\"Predict (0,0):\", predict_tree(root, (0,0))) # Should be 0\n# print(\"Predict (0,1):\", predict_tree(root, (0,1))) # Should be 1\n# print(\"Predict (1,0):\", predict_tree(root, (1,0))) # Should be 1\n# print(\"Predict (1,1):\", predict_tree(root, (1,1))) # Should be 0"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Random Forests\nA single Decision Tree with no `max_depth` will almost always perfectly memorize the training data ($100\\%$ accuracy, zero entropy leaves) and **overfit** terribly. \n\nHow does the **Random Forest** algorithm solve this? \n\n<details><summary>💡 Sketch</summary>\nA Random Forest trains $100$ *different* Decision Trees. To make them different, each tree is trained on a random subsample of the dataset (Bootstrapping), and at each split, the tree is only allowed to look at a random subset of features. \nAt inference time, a data point is dropped down all $100$ trees, and the trees \"vote\" on the final classification. This ensemble approach drastically lowers Variance and prevents overfitting, creating one of the most powerful algorithms in machine learning.\n</details>\n\n---\n📚 **Next:** Algorithms 29 (Logistic Regression via Gradient Descent)")
    ]

if __name__=="__main__":
    save(algo_23_25(),os.path.join(OUT,"23-25_regression_pseudoinverse.ipynb"))
    save(algo_26(),os.path.join(OUT,"26_nearest_neighbors.ipynb"))
    save(algo_27_28(),os.path.join(OUT,"27-28_decision_trees.ipynb"))
    print("Notebooks 23 to 28 generated.")
