import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")
OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\n!pip install -q sympy matplotlib plotly ipywidgets\nimport sympy as sp; sp.init_printing()\nimport numpy as np, matplotlib.pyplot as plt\nprint('Ready ✅')")

def math_02():
    return [
cell("markdown","# Math 02: Calculus — Derivatives & the Power Rule\n\n**Learning Objectives:**\n1. Understand the derivative as the slope of a function at a point\n2. Compute derivatives via the difference quotient (limit definition)\n3. Apply the Power Rule to differentiate polynomials efficiently\n4. Implement numerical and symbolic differentiation in Python\n\n**Prerequisites:** Math 01 (Algebra), basic function concepts\n**Estimated time:** 120 minutes\n**Textbook:** *Justin Skycak — Calculus* §1.3–1.4"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### What is a derivative?\n\n> 📖 *From Calculus §1.3:* The **derivative** of a function is the function's slope at a particular point.\n\nWe approximate the slope at $x$ by picking a nearby point $x + \\Delta x$ and computing:\n\n$$\\text{slope} \\approx \\frac{f(x+\\Delta x) - f(x)}{\\Delta x}$$\n\nThis is the **difference quotient**. The derivative is the limit as $\\Delta x \\to 0$:\n\n$$f'(x) = \\lim_{\\Delta x \\to 0} \\frac{f(x+\\Delta x)-f(x)}{\\Delta x}$$"),
cell("markdown","### Guided Proof — Derivative of $f(x) = x^2$\n\n$$f'(x) = \\lim_{\\Delta x \\to 0}\\frac{(x+\\Delta x)^2 - x^2}{\\Delta x} = \\lim_{\\Delta x \\to 0}\\frac{x^2+2x\\Delta x+(\\Delta x)^2-x^2}{\\Delta x}$$\n$$= \\lim_{\\Delta x \\to 0}\\frac{2x\\Delta x + (\\Delta x)^2}{\\Delta x} = \\lim_{\\Delta x \\to 0}(2x + \\Delta x) = 2x \\quad \\square$$\n\nSo the slope of $x^2$ at any point $x$ is $2x$. At $x=-2$ the slope is $-4$ (falling), at $x=0$ slope is $0$ (flat valley), at $x=3$ slope is $6$ (rising)."),
cell("code","# Symbolic verification with SymPy\nimport sympy as sp\nx, dx = sp.symbols('x Delta_x')\n\nf = x**2\ndiff_quot = ((x+dx)**2 - x**2) / dx\nprint('Difference quotient:', sp.expand(diff_quot))\nprint('Limit as Δx→0:    ', sp.limit(diff_quot, dx, 0))\nprint('SymPy derivative:  ', sp.diff(f, x))"),
cell("markdown","### The Power Rule\n\n> 📖 *From Calculus §1.4:* The **power rule** states that for $f(x) = x^n$:\n> $$f'(x) = nx^{n-1}$$\n\n| $f(x)$ | $f'(x)$ | Rule applied |\n|---|---|---|\n| $x^3$ | $3x^2$ | bring 3 down, reduce power |\n| $x^{-1} = 1/x$ | $-x^{-2}$ | works for negative exponents |\n| $x^{1/2} = \\sqrt{x}$ | $\\frac{1}{2}x^{-1/2}$ | works for fractional exponents |\n| $x^0 = 1$ (constant) | $0$ | constants have zero slope |\n\nFor a sum of terms: differentiate each term individually.\nFor a constant multiple: $\\frac{d}{dx}[cf(x)] = c \\cdot f'(x)$.\n\n**Example:** $f(x)=3x^4-2x^2+5x-7$\n$$f'(x) = 12x^3 - 4x + 5$$"),
cell("markdown","### Comprehension Check ✅\n1. What is the derivative of $f(x) = 7x^3 - x + 4$?\n2. Why is the derivative of a constant always 0?\n3. What does a negative derivative tell you about the function?\n\n<details><summary>💡 Answers</summary>\n\n1. $f'(x)=21x^2-1$\n2. A constant has no slope — it's a flat horizontal line.\n3. The function is *decreasing* at that point.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### Worked Example: Numerical Derivative"),
cell("code","# Computing the derivative numerically vs analytically\nimport numpy as np\nimport matplotlib.pyplot as plt\n\ndef f(x): return x**3 - 2*x + 1\ndef f_prime_exact(x): return 3*x**2 - 2  # by power rule\n\n# Numerical derivative using difference quotient\ndef numerical_derivative(f, x, dx=1e-7):\n    return (f(x + dx) - f(x)) / dx\n\n# Compare at x = 2\nx_val = 2.0\nprint(f'Exact derivative at x={x_val}:    {f_prime_exact(x_val)}')\nprint(f'Numerical derivative at x={x_val}: {numerical_derivative(f, x_val)}')\nprint(f'Error: {abs(f_prime_exact(x_val) - numerical_derivative(f, x_val)):.2e}')"),
cell("markdown","### 🎯 Your Turn\nUse the difference quotient to find the derivative of $f(x)=x^4$ by hand.\nThen verify with SymPy."),
cell("code","def power_rule_derivative(coefficients):\n    '''Apply the power rule to a polynomial.\n    coefficients: list [a_n, a_{n-1}, ..., a_1, a_0] (highest degree first)\n    Returns: list of derivative coefficients\n    '''\n    # YOUR CODE HERE\n    pass\n\n# Test: f(x) = 3x^3 - 2x^2 + x - 5 → f'(x) = 9x^2 - 4x + 1\n# assert power_rule_derivative([3, -2, 1, -5]) == [9, -4, 1]\n# print('Phase 0 passed ✅')"),
cell("markdown","<details><summary>💡 Hint</summary>\n\nFor term $a_k x^k$, the derivative is $k \\cdot a_k \\cdot x^{k-1}$.\nIterate from the highest power down, multiplying each coefficient by its exponent.\n</details>"),
cell("markdown","---\n## Phase 1 — Micro-Scaffolded Algorithm Construction\n\n### Step 1: Difference Quotient Function\nWrite a general numerical derivative function."),
cell("code","def derivative(f, x, dx=1e-7):\n    '''Approximate f'(x) using the difference quotient.'''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# import math\n# assert abs(derivative(lambda x: x**2, 3) - 6.0) < 1e-5\n# assert abs(derivative(math.sin, 0) - 1.0) < 1e-5  # cos(0) = 1\n# print('Step 1 passed ✅')"),
cell("markdown","### Step 2: Central Difference (Better Approximation)\nThe central difference $\\frac{f(x+h)-f(x-h)}{2h}$ is more accurate than the forward difference."),
cell("code","def derivative_central(f, x, dx=1e-7):\n    '''Approximate f'(x) using the central difference quotient.'''\n    # YOUR CODE HERE\n    pass\n\n# Compare accuracy:\n# import math\n# x0 = 1.0\n# exact = math.cos(x0)  # derivative of sin\n# fwd = derivative(math.sin, x0)\n# ctr = derivative_central(math.sin, x0)\n# print(f'Exact:   {exact:.15f}')\n# print(f'Forward: {fwd:.15f}  error={abs(fwd-exact):.2e}')\n# print(f'Central: {ctr:.15f}  error={abs(ctr-exact):.2e}')"),
cell("markdown","### Step 3: Visualize the Tangent Line (Spaced Repetition — uses slope-intercept from Math 01)"),
cell("code","def plot_tangent(f, f_prime, x0):\n    '''Plot f(x) and its tangent line at x0.'''\n    import matplotlib.pyplot as plt, numpy as np\n    xs = np.linspace(x0 - 3, x0 + 3, 300)\n    slope = f_prime(x0)\n    tangent = slope * (xs - x0) + f(x0)\n    plt.figure(figsize=(8, 5))\n    plt.plot(xs, f(xs), 'b-', lw=2, label='f(x)')\n    plt.plot(xs, tangent, 'r--', lw=2, label=f'tangent (slope={slope:.2f})')\n    plt.plot(x0, f(x0), 'ko', ms=8, zorder=5)\n    plt.legend(); plt.grid(alpha=0.3); plt.title(f'Tangent Line at x={x0}')\n    plt.tight_layout(); plt.show()\n\n# Example: f(x) = x^3 - 2x + 1, tangent at x = 1\nplot_tangent(lambda x: x**3-2*x+1, lambda x: 3*x**2-2, 1.0)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Pathological Case: Choosing dx Too Small\nIf $\\Delta x$ is too small, floating-point subtraction in $f(x+\\Delta x)-f(x)$ cancels most digits."),
cell("code","import numpy as np, matplotlib.pyplot as plt\n\ndef f(x): return x**3\ndef f_prime(x): return 3*x**2  # exact\n\nx0 = 1.0\ndx_values = np.logspace(-1, -16, 100)\nerrors = [abs((f(x0+dx)-f(x0))/dx - f_prime(x0)) for dx in dx_values]\n\nplt.figure(figsize=(9,5))\nplt.loglog(dx_values, errors, 'r-', lw=2)\nplt.xlabel('Δx'); plt.ylabel('Absolute Error')\nplt.title('Error in Numerical Derivative vs Step Size')\nplt.axvline(x=1e-8, color='g', ls='--', label='Sweet spot ≈ 1e-8')\nplt.legend(); plt.grid(alpha=0.3); plt.tight_layout(); plt.show()\nprint('Too large Δx → truncation error. Too small Δx → rounding error.')"),
cell("markdown","### 🔍 Reflection\n1. What step size minimizes error?\n2. Why does error *increase* when $\\Delta x < 10^{-8}$?\n\n<details><summary>💡 Answer</summary>\n\nOptimal $\\Delta x \\approx \\sqrt{\\epsilon_{\\text{machine}}} \\approx 10^{-8}$ for float64.\nBelow that, $f(x+\\Delta x)$ and $f(x)$ are so close that their difference loses all significant digits.\n</details>"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Symbolic Differentiator\nBuild a function that takes a polynomial as a list of coefficients and returns\nits derivative as a list — **without using SymPy**. Then extend it to compute the\n$n$-th derivative."),
cell("code","def nth_derivative(coeffs, n=1):\n    '''Compute the n-th derivative of a polynomial.\n    coeffs: [a_n, ..., a_1, a_0] highest degree first\n    Returns: coefficient list of the n-th derivative\n    '''\n    # YOUR CODE HERE (no scaffolding!)\n    pass\n\n# Test: f(x) = x^4, f''(x) = 12x^2 → [12, 0, 0]\n# assert nth_derivative([1,0,0,0,0], 2) == [12, 0, 0]"),
cell("markdown","### Chalkboard Defense\n\n1. **Correctness:** Prove that the central difference has error $O(h^2)$ vs $O(h)$ for forward difference.\n2. **Complexity:** What is the cost of computing the $n$-th derivative of a degree-$d$ polynomial?\n3. **Stability:** Explain the U-shaped error curve from Phase 2.\n\n*(Write your defense below)*\n\n<details><summary>💡 Defense sketch</summary>\n\nTaylor expand: $f(x+h) = f(x)+hf'(x)+\\frac{h^2}{2}f''(x)+O(h^3)$.\nForward difference: error term is $\\frac{h}{2}f''(x)$ → $O(h)$.\nCentral: $f(x+h)-f(x-h)=2hf'(x)+O(h^3)$ → divide by $2h$ gives error $O(h^2)$.\n</details>"),
cell("markdown","---\n### 📚 Further Reading\n- *Calculus* §1.5–1.6: Chain Rule, Product/Quotient Rule\n- **Next:** Math 03 (Chain Rule)"),
    ]

def math_03():
    return [
cell("markdown","# Math 03: Calculus — The Chain Rule\n\n**Learning Objectives:**\n1. Differentiate composite functions using the Chain Rule\n2. Decompose nested functions into layers for differentiation\n3. Implement chain-rule differentiation computationally\n\n**Prerequisites:** Math 02 (Derivatives & Power Rule)\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Calculus* §1.5"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Chain Rule\n\n> 📖 *From Calculus §1.5:* The chain rule tells us how to differentiate compositions of functions.\n> Informally: 'forget' about the inside, differentiate the outside, then multiply by the derivative of the inside.\n\nFor $y = f(g(x))$, let $u = g(x)$. Then:\n$$\\frac{dy}{dx} = \\frac{dy}{du} \\cdot \\frac{du}{dx} = f'(g(x)) \\cdot g'(x)$$\n\n**Intuition:** Derivatives cancel like fractions: $\\frac{dy}{dx} = \\frac{dy}{du} \\cdot \\frac{du}{dx}$\n\n### Examples\n| $y$ | $u$ (inside) | $dy/du$ | $du/dx$ | $dy/dx$ |\n|---|---|---|---|---|\n| $(3x+1)^5$ | $u=3x+1$ | $5u^4$ | $3$ | $15(3x+1)^4$ |\n| $\\sqrt{x^2+1}$ | $u=x^2+1$ | $\\frac{1}{2\\sqrt{u}}$ | $2x$ | $\\frac{x}{\\sqrt{x^2+1}}$ |\n| $\\sin(x^3)$ | $u=x^3$ | $\\cos u$ | $3x^2$ | $3x^2\\cos(x^3)$ |"),
cell("code","# Symbolic verification\nimport sympy as sp\nx = sp.Symbol('x')\n\nexpressions = [(3*x+1)**5, sp.sqrt(x**2+1), sp.sin(x**3)]\nfor expr in expressions:\n    print(f'd/dx [{expr}] = {sp.diff(expr, x)}')"),
cell("markdown","### Multi-layer chains\n\nFor deeply nested functions, apply the chain rule repeatedly:\n$$\\frac{d}{dx}[f(g(h(x)))] = f'(g(h(x))) \\cdot g'(h(x)) \\cdot h'(x)$$\n\n**Example:** $y = \\sin^2(3x) = [\\sin(3x)]^2$\n- Layer 1: $u_1 = 3x \\Rightarrow du_1/dx = 3$\n- Layer 2: $u_2 = \\sin(u_1) \\Rightarrow du_2/du_1 = \\cos(u_1)$\n- Layer 3: $y = u_2^2 \\Rightarrow dy/du_2 = 2u_2$\n\n$$\\frac{dy}{dx} = 2\\sin(3x) \\cdot \\cos(3x) \\cdot 3 = 6\\sin(3x)\\cos(3x)$$\n\n> 💡 This layer-by-layer decomposition is **exactly how backpropagation works** in neural networks (Notebook 35-36)."),
cell("markdown","### Comprehension Check ✅\n1. Differentiate $f(x) = (2x^3-1)^4$\n2. Why can't you just use the power rule on $(2x^3-1)^4$ directly?\n\n<details><summary>💡 Answers</summary>\n\n1. $f'(x)=4(2x^3-1)^3 \\cdot 6x^2 = 24x^2(2x^3-1)^3$\n2. The power rule applies to $x^n$, not $(\\text{stuff})^n$. The chain rule accounts for the 'stuff' inside.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice"),
cell("code","def chain_rule_gradient(df_dg, dg_dx):\n    '''Given the outer derivative and inner derivative, compute the overall gradient.'''\n    # YOUR CODE HERE\n    pass\n\n# Test: d/dx[sin(x^2)] at x=1 → cos(1)*2 ≈ 1.0806\n# import math\n# assert abs(chain_rule_gradient(math.cos(1), 2*1) - 2*math.cos(1)) < 1e-10\n# print('Phase 0 passed ✅')"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Numerical Chain Rule\nGiven two functions $f$ and $g$, compute $\\frac{d}{dx}[f(g(x))]$ numerically."),
cell("code","def composite_derivative(f, g, x, dx=1e-7):\n    '''Compute d/dx[f(g(x))] numerically.'''\n    # YOUR CODE HERE\n    pass\n\n# Test: d/dx[sin(x^2)] at x=1\n# import math\n# result = composite_derivative(math.sin, lambda x: x**2, 1.0)\n# expected = 2 * math.cos(1)  # chain rule\n# assert abs(result - expected) < 1e-5\n# print('Step 1 passed ✅')"),
cell("markdown","### Step 2: Symbolic Chain Rule Engine\nBuild a function that applies the chain rule symbolically using SymPy."),
cell("code","import sympy as sp\n\ndef apply_chain_rule(outer_func, inner_expr, var=sp.Symbol('x')):\n    '''Apply chain rule: d/dx[outer(inner(x))]\n    outer_func: a SymPy function (e.g. sp.sin)\n    inner_expr: a SymPy expression in var\n    Returns: the derivative expression\n    '''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# x = sp.Symbol('x')\n# result = apply_chain_rule(sp.sin, x**2)\n# print(result)  # should be 2*x*cos(x**2)"),
cell("markdown","### Step 3: Multi-Layer Chain (Interleaved Practice)\nImplement a function that chains N derivatives together."),
cell("code","def multi_chain(derivatives_list):\n    '''Given [df/dg, dg/dh, dh/dx, ...], multiply them all.\n    This is the chain rule for arbitrarily deep compositions.\n    '''\n    result = 1\n    for d in derivatives_list:\n        # YOUR CODE HERE\n        pass\n    return result"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Pathological Case: Vanishing Gradient in Deep Chains\nWhen composing many functions with small derivatives, the product of gradients → 0."),
cell("code","import numpy as np, matplotlib.pyplot as plt\n\n# Simulate a chain of N sigmoid-like functions\n# Each local gradient is at most 0.25 (sigmoid'(0) = 0.25)\ndef sigmoid_grad(x): return np.exp(-x) / (1+np.exp(-x))**2\n\ndepths = range(1, 51)\nfinal_grads = [sigmoid_grad(0)**d for d in depths]\n\nplt.figure(figsize=(9,5))\nplt.semilogy(list(depths), final_grads, 'r-o', ms=3)\nplt.xlabel('Chain Depth (number of layers)')\nplt.ylabel('Gradient magnitude (log scale)')\nplt.title('Vanishing Gradient Problem: Chain Rule with Sigmoid')\nplt.grid(alpha=0.3); plt.tight_layout(); plt.show()\nprint(f'After 10 layers: gradient ≈ {sigmoid_grad(0)**10:.2e}')\nprint(f'After 50 layers: gradient ≈ {sigmoid_grad(0)**50:.2e}')\nprint('\\n⚠️ This is the VANISHING GRADIENT problem — it makes deep neural networks hard to train!')"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: ReLU vs Sigmoid Gradient Flow\nThe ReLU function $\\max(0,x)$ has gradient 1 for $x>0$ and 0 for $x\\leq 0$.\nShow that a chain of ReLU gradients does NOT vanish (but can die completely).\nImplement both and compare."),
cell("code","# YOUR CODE: compare gradient flow through 50 sigmoid vs 50 ReLU layers\n# Plot both on the same graph\npass"),
cell("markdown","### Chalkboard Defense\n1. Prove the chain rule using the limit definition\n2. Explain why vanishing gradients are a problem for neural network training\n3. Why does ReLU partially solve this?\n\n<details><summary>💡 Sketch</summary>\n\n$\\frac{d}{dx}f(g(x))=\\lim_{h\\to0}\\frac{f(g(x+h))-f(g(x))}{h}$. Let $k=g(x+h)-g(x)$, then $=\\lim\\frac{f(g(x)+k)-f(g(x))}{k}\\cdot\\frac{k}{h}=f'(g(x))\\cdot g'(x)$.\n</details>\n\n---\n📚 **Next:** Math 04 (Local Extrema) — uses derivatives to find peaks and valleys"),
    ]

if __name__=="__main__":
    save(math_02(),os.path.join(OUT,"math_02_calculus_derivatives.ipynb"))
    save(math_03(),os.path.join(OUT,"math_03_calculus_chain_rule.ipynb"))
    print("Batch 1a done.")
