import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nprint('Ready ✅')")

def algo_07():
    return [
cell("markdown","# Algorithms 07: Brute Force Cryptography\n\n**Learning Objectives:**\n1. Understand encoding and decoding functions\n2. Use brute-force search to explore a parameter space\n3. Break a simple linear encryption scheme computationally\n\n**Prerequisites:** Algorithms 01\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 7"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Linear-Encoding Cryptography\n> 📖 *From Algorithms Ch. 7:* An encoding function maps a string to a sequence of numbers. Using a linear encoding function $f(x) = ax + b$, we can encode messages.\n\nSuppose $a=2$ and $b=3$. \nThe letter 'a' is $x=1$. $f(1) = 2(1) + 3 = 5$.\nThe space ' ' is $x=0$. $f(0) = 2(0) + 3 = 3$.\n\n### Decoding\nTo decode, we invert the function: $x = \\frac{f(x) - b}{a}$.\nIf we receive $5$, $x = \\frac{5 - 3}{2} = 1$ ('a').\n\n### Brute-Force Search\nIf we don't know $a$ and $b$, but we know they are small integers, we can try *every* possible combination of $(a, b)$. This is **brute-force search**.\nWe check each decoded sequence. If all characters are valid integers between 0 and 26, it *might* be a valid message. If it contains real words, we've broken the code!"),
cell("markdown","### Comprehension Check ✅\n1. If the encoded message is `[7, 3, 11]` and $a=2, b=1$, what is the decoded sequence of numbers?\n2. What is the fundamental weakness of brute-force search if $a$ and $b$ can be any 64-bit integer?\n\n<details><summary>💡 Answers</summary>\n\n1. $x = \\frac{y-1}{2}$. $7 \\rightarrow 3$, $3 \\rightarrow 1$, $11 \\rightarrow 5$. So `[3, 1, 5]` ('c a e').\n2. The search space becomes too large. $2^{64} \\times 2^{64}$ combinations would take millions of years to check.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Manual Decoding\nGiven encoded message `[5, 11]` and $a=3, b=2$. \nSolve $3x + 2 = y$ for $x$ on paper. Then write code to convert the resulting numbers to characters (space=0, a=1, b=2...)."),
cell("code","def number_to_char(n):\n    '''Return space if n=0, 'a' if 1, 'b' if 2, etc.'''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# assert number_to_char(1) == 'a'\n# assert number_to_char(0) == ' '"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Decode Numbers\nWrite a function that attempts to decode an array of numbers using a given $a$ and $b$. If any $x$ is not an integer between 0 and 26, return `False`."),
cell("code","def decode_numbers(numbers, a, b):\n    '''Attempt to decode numbers using f(x) = ax + b. \n    Return string if valid, else False.'''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# assert decode_numbers([5, 11], 3, 2) == 'ac'"),
cell("markdown","### Step 2: Brute-Force Codebreaker (Interleaved Practice)\nWe intercepted the message `[377, 717, 71, 513, 105, 921, 581, 547, 547, 105, 377, 717]`.\nWe know $0 \\leq a, b \\leq 100$. Use a nested loop to test all combinations. Print any valid message found."),
cell("code","def break_code(encoded_message):\n    '''Print all valid decoded messages and their (a, b) pairs.'''\n    # YOUR CODE HERE\n    pass\n\n# Run it:\n# msg = [377, 717, 71, 513, 105, 921, 581, 547, 547, 105, 377, 717]\n# break_code(msg)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Filtering the Noise\nYou likely printed out multiple \"valid\" strings, but only one is english: `'go get a coffee go'`. How can we make the computer automatically reject the gibberish?\nWe can check the decoded string against a dictionary of valid english words!"),
cell("code","valid_words = {'go', 'get', 'a', 'coffee'}\n\ndef break_code_smart(encoded_message):\n    '''Print ONLY the message if all its words are in the dictionary.'''\n    # YOUR CODE HERE\n    pass\n\n# break_code_smart(msg)"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Quadratic Encoding\nSuppose the encoding function was $f(x) = ax^2 + bx + c$, with $a,b,c \\in [0, 20]$.\nTo decode, you must use the Quadratic Formula! \nWrite a brute-force solver that searches for $a,b,c$ and uses the quadratic formula to decode. Remember that the quadratic formula yields two roots; at least one must be a valid character index.\n\n*(Leave as a theoretical exercise or implement below if you dare!)*"),
cell("code","# YOUR CODE HERE\npass"),
cell("markdown","### Chalkboard Defense\nWhat is the time complexity of the brute force search in terms of the message length $L$ and the search range $R$ for the parameters $a$ and $b$? Why does brute-force cryptography fail on modern AES-256?\n\n<details><summary>💡 Sketch</summary>\nThe two loops take $O(R^2)$ iterations. Inside the loop, decoding takes $O(L)$. Total time is $O(L \\cdot R^2)$.\nModern AES-256 has $R = 2^{256}$. $O(R)$ is so astronomically large that all the computers on Earth couldn't check every combination before the heat death of the universe.\n</details>\n\n---\n📚 **Next:** Algorithms 08 (Backtracking & Magic Squares)")
    ]

def algo_08():
    return [
cell("markdown","# Algorithms 08: Backtracking & Magic Squares\n\n**Learning Objectives:**\n1. Understand how backtracking optimizes brute-force search\n2. Use a `continue` statement to prune hopeless search branches\n3. Solve the $3 \\times 3$ Magic Square computationally\n\n**Prerequisites:** Algorithms 07\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 8"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Problem with Brute Force\n> 📖 *From Algorithms Ch. 8:* Brute force search can often be slow or infeasible when there are lots of possibilities. However, **backtracking** can drastically cut down the number of possibilities.\n\nWe want to find a $3 \\times 3$ **magic square** using the digits 1-9 without repetition. A magic square has all rows, columns, and diagonals summing to exactly 15.\n\nIf we use 9 nested loops, we check $9! = 362,880$ arrangements.\nBut if we fill the top row with `[1, 2, 3]`, the sum is 6. This row will *never* sum to 15, no matter what we put in the other 6 squares! \n\n### Backtracking\nWhenever we reach an arrangement that can no longer become valid, we **skip** exploring it further. We use a `continue` statement to jump to the next iteration of the loop, effectively pruning thousands of hopeless branches at once."),
cell("markdown","### Comprehension Check ✅\n1. If the top row is `[8, 1, x]`, what must `x` be for the row to sum to 15?\n2. If we prune a branch at the 3rd nested loop out of 9, how many loop iterations did we just save?\n\n<details><summary>💡 Answers</summary>\n\n1. `x = 6`.\n2. We saved $6! = 720$ iterations that would have explored the remaining 6 variables uselessly.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Identify Hopeless States\nWrite a function that checks if a fully populated row/col/diag sums to 15. If it is fully populated and does NOT sum to 15, it's hopeless."),
cell("code","def is_hopeless_line(line):\n    '''Return True if the line has no zeros (fully populated) \n    AND its sum is not 15.'''\n    # YOUR CODE HERE\n    pass\n\n# Tests:\n# assert is_hopeless_line([1, 2, 3]) == True  # Sum is 6 != 15\n# assert is_hopeless_line([8, 1, 6]) == False # Sum is 15\n# assert is_hopeless_line([8, 1, 0]) == False # Not fully populated yet"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The `is_hopeless` checker\nWrite a function that checks a $3 \\times 3$ grid (represented as a 1D list of length 9, where `0` means empty). Check all 3 rows, 3 cols, and 2 diagonals. If *any* fully-populated line fails the sum, the whole square is hopeless."),
cell("code","def is_hopeless(square):\n    '''Return True if the square is hopeless.'''\n    # Indices for rows, cols, diagonals:\n    lines = [\n        [0, 1, 2], [3, 4, 5], [6, 7, 8], # rows\n        [0, 3, 6], [1, 4, 7], [2, 5, 8], # cols\n        [0, 4, 8], [2, 4, 6]             # diags\n    ]\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Step 2: The Backtracking Solver\nUse 9 nested loops for variables $v_0$ through $v_8$. At each loop, check if the square so far is hopeless or if the number is already used. If so, `continue`."),
cell("code","def solve_magic_square():\n    '''Print the first valid magic square found.'''\n    for v0 in range(1, 10):\n        for v1 in range(1, 10):\n            if v1 == v0: continue\n            for v2 in range(1, 10):\n                if v2 in (v0, v1): continue\n                if is_hopeless([v0, v1, v2, 0, 0, 0, 0, 0, 0]): continue\n                \n                # COMPLETE THE NESTED LOOPS for v3 through v8\n                # Make sure to check is_hopeless at strategic points!\n                # YOUR CODE HERE\n                pass"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Profiling Backtracking\nLet's add a counter to see exactly how many states our backtracking algorithm evaluates, compared to the $362,880$ of pure brute force."),
cell("code","def solve_magic_square_counted():\n    states_checked = 0\n    # Modify your solver to increment states_checked right before every is_hopeless call.\n    # YOUR CODE HERE\n    # return states_checked\n    pass\n\n# print(\"States evaluated:\", solve_magic_square_counted())"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Recursive Backtracking\nWriting 9 nested loops is ugly. Writing 16 nested loops for a $4 \\times 4$ square is unbearable!\nWe can generalize backtracking using **Recursion**. Write a recursive solver that takes `(square, index)` and tries to fill `index` from 1 to 9, calling itself for `index+1`."),
cell("code","def solve_recursive(square, index=0):\n    '''Recursively fill the square. Return True if solved.'''\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Chalkboard Defense\nWhy is recursive backtracking a form of Depth-First Search (DFS) on a tree? Draw a tiny tree showing the pruning of branches.\n\n<details><summary>💡 Sketch</summary>\nThe search space is a tree where the root is an empty board, and each child adds one number. Exploring deeply until hitting a wall (hopeless) and then stepping back to try the next sibling is exactly Depth-First Search. Pruning a node deletes the entire subtree below it.\n</details>\n\n---\n📚 **Next:** Algorithms 09 (Estimating Roots)")
    ]

def algo_09():
    return [
cell("markdown","# Algorithms 09: Estimating Roots\n\n**Learning Objectives:**\n1. Estimate roots of functions using Bisection Search\n2. Estimate roots of functions using the Newton-Raphson Method\n3. Compare the convergence rates of both algorithms\n\n**Prerequisites:** Math 02 (Derivatives)\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 9"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Bisection Search\n> 📖 *From Algorithms Ch. 9:* To estimate the root using **bisection search**, we start with a lower bound and an upper bound, and repeatedly move one bound halfway to the other.\n\nIf $f(x) = x^3 - 2$, we know $f(1) = -1$ and $f(2) = 6$. The root must be between 1 and 2.\nWe test the midpoint $1.5$. $f(1.5) = 1.375 > 0$. \nBecause it's positive, the root must be to its left. New bounds: $[1, 1.5]$.\nWe repeat until the difference between bounds is less than a target `epsilon`.\n\n### Newton-Raphson Method\n> 📖 *From Algorithms Ch. 9:* We start with an initial guess and repeatedly update our guess to be the root of the *tangent line* to the function.\n\nThe tangent line at $x_n$ has slope $f'(x_n)$. Its root is given by the update rule:\n$$x_{n+1} = x_n - \\frac{f(x_n)}{f'(x_n)}$$\nThis method converges much faster, provided the derivative isn't zero."),
cell("markdown","### Comprehension Check ✅\n1. What is the fundamental requirement for the initial bounds $[a, b]$ in bisection search?\n2. What happens in Newton-Raphson if $f'(x_n) = 0$?\n\n<details><summary>💡 Answers</summary>\n\n1. $f(a)$ and $f(b)$ must have opposite signs, guaranteeing a root lies between them (Intermediate Value Theorem).\n2. The tangent line is horizontal and never hits the x-axis. The formula divides by zero and crashes.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: A Single Step\nGiven $f(x) = x^2 - 5$. We want to find $\\sqrt{5}$.\n1. Do one bisection step with bounds $[2, 3]$. What is the new midpoint and new bounds?\n2. Do one Newton-Raphson step with guess $x_0 = 2$. What is $x_1$?\n\nCompute these by hand, then verify with Python."),
cell("code","def test_manual_steps():\n    # f(x) = x^2 - 5, f'(x) = 2x\n    midpoint = (2+3)/2 # 2.5\n    f_mid = midpoint**2 - 5 # 1.25 (positive, so replace upper bound)\n    \n    x0 = 2\n    x1 = x0 - (x0**2 - 5) / (2*x0)\n    \n    print(\"New bounds after 1 bisection:\", [2, midpoint])\n    print(\"New guess after 1 Newton step:\", x1)\n\ntest_manual_steps()"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Bisection Search\nImplement `bisection_search(f, lower, upper, epsilon=1e-5)`."),
cell("code","def bisection_search(f, lower, upper, epsilon=1e-5):\n    '''Return the estimated root using bisection.'''\n    # Ensure f(lower) and f(upper) have opposite signs\n    # YOUR CODE HERE\n    pass\n\n# Test: cube root of 2\n# def f(x): return x**3 - 2\n# root = bisection_search(f, 1, 2)\n# print(\"Bisection root:\", root)"),
cell("markdown","### Step 2: Newton-Raphson Method\nImplement `newton_raphson(f, f_prime, guess, epsilon=1e-5)`."),
cell("code","def newton_raphson(f, f_prime, guess, epsilon=1e-5):\n    '''Return the estimated root using Newton-Raphson.'''\n    # Loop until abs(f(x)) < epsilon:\n    #   x = x - f(x)/f'(x)\n    # YOUR CODE HERE\n    pass\n\n# Test: cube root of 2\n# def f_prime(x): return 3*x**2\n# root = newton_raphson(f, f_prime, 2)\n# print(\"Newton root:\", root)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Comparing Convergence Speeds\nLet's count how many iterations each method takes to achieve high precision (`1e-12`)."),
cell("code","def compare_convergence():\n    # Modify your functions above to return (root, num_iterations)\n    # and test them here for finding sqrt(2) with epsilon=1e-12\n    pass\n# compare_convergence()"),
cell("markdown","### Pathological Case: Newton's Nightmare\nNewton-Raphson is fast, but it can fail spectacularly. Consider $f(x) = x^{1/3}$.\nIts derivative is $\\frac{1}{3}x^{-2/3}$. \nThe update rule becomes $x_{n+1} = x_n - \\frac{x_n^{1/3}}{\\frac{1}{3}x_n^{-2/3}} = x_n - 3x_n = -2x_n$.\nIf you start at $x_0 = 1$, the guesses are $1, -2, 4, -8, 16 \\dots$ it spirals to infinity!\n\nWrite a test showing this divergence."),
cell("code","# YOUR CODE HERE to show Newton divergence on f(x) = x**(1/3)"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: The Secant Method\nWhat if you don't have the symbolic derivative $f'(x)$ for Newton's method?\nYou can approximate the tangent using the two most recent guesses: \n$f'(x_n) \\approx \\frac{f(x_n) - f(x_{n-1})}{x_n - x_{n-1}}$.\nThis is the **Secant Method**. Implement it!"),
cell("code","def secant_method(f, x0, x1, epsilon=1e-5):\n    '''Estimate root using secant method.'''\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Chalkboard Defense\nExplain the time complexity (convergence rate) of Bisection vs Newton. \nBisection eliminates half the error each step. How does the error behave in Newton's method?\n\n<details><summary>💡 Sketch</summary>\nBisection has **linear convergence**. The error is halved each step: $E_{n+1} = 0.5 E_n$. It gains roughly 1 decimal point of precision every 3 steps.\nNewton has **quadratic convergence**. The error is squared each step: $E_{n+1} \\propto E_n^2$. If the error is $0.1$, the next is $0.01$, then $0.0001$. The number of correct decimal places *doubles* with every step!\n</details>\n\n---\n📚 **Next:** Algorithms 10 (Single Variable Gradient Descent)")
    ]

if __name__=="__main__":
    save(algo_07(),os.path.join(OUT,"07_brute_force_crypto.ipynb"))
    save(algo_08(),os.path.join(OUT,"08_backtracking_magic_squares.ipynb"))
    save(algo_09(),os.path.join(OUT,"09_estimating_roots.ipynb"))
    print("Notebooks 07, 08, and 09 done.")
