import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\n!pip install -q sympy matplotlib plotly ipywidgets\nimport sympy as sp; sp.init_printing()\nimport numpy as np, matplotlib.pyplot as plt\nprint('Ready ✅')")

def math_05():
    return [
cell("markdown","# Math 05: Linear Algebra — Vectors\n\n**Learning Objectives:**\n1. Represent points and displacements in N-dimensional space\n2. Perform vector addition and scalar multiplication\n3. Compute the dot product and understand its geometric meaning\n4. Compute the cross product (for 3D vectors)\n5. Implement vector math computationally from scratch\n\n**Prerequisites:** Math 01 (Algebra)\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Linear Algebra* §1.1-1.2"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### What is a Vector?\n> 📖 *From Linear Algebra §1.1:* Points in N-dimensional space consist of numbers, but can also be thought of as manipulable entities in their own right, called **vectors**. Instead of fixed points, we think of them as displacements through space.\n\nA vector $\\vec{v} = \\langle v_1, v_2, \\dots, v_n \\rangle$ represents a displacement.\n\n### Vector Algebra\n1. **Addition (Component-wise):** $\\langle 1, 2 \\rangle + \\langle 3, 4 \\rangle = \\langle 4, 6 \\rangle$\n   - *Geometry:* Start the second vector where the first one ends.\n2. **Scalar Multiplication:** $3 \\cdot \\langle 1, -2 \\rangle = \\langle 3, -6 \\rangle$\n   - *Geometry:* Rescales the vector's length. Negative scalars flip its direction.\n3. **Norm (Length):** $||\\vec{v}|| = \\sqrt{v_1^2 + v_2^2 + \\dots + v_n^2}$ (Pythagorean theorem)"),
cell("markdown","### Multiplication of Vectors\n> 📖 *From Linear Algebra §1.2:* What does it mean to multiply a vector by another vector? The two most common interpretations are the **dot product** and the **cross product**.\n\n**1. Dot Product (Scalar Output)**\n$\\vec{a} \\cdot \\vec{b} = a_1 b_1 + a_2 b_2 + \\dots + a_n b_n$\n*Geometry:* $\\vec{a} \\cdot \\vec{b} = ||\\vec{a}|| ||\\vec{b}|| \\cos(\\theta)$, where $\\theta$ is the angle between them.\n- If $\\vec{a} \\cdot \\vec{b} = 0$, the vectors are **perpendicular** (orthogonal).\n\n**2. Cross Product (Vector Output, 3D only)**\n$\\vec{a} \\times \\vec{b} = \\langle a_2 b_3 - a_3 b_2,\\; a_3 b_1 - a_1 b_3,\\; a_1 b_2 - a_2 b_1 \\rangle$\n*Geometry:* Produces a new vector **perpendicular to both** $\\vec{a}$ and $\\vec{b}$.\nIts length $||\\vec{a} \\times \\vec{b}|| = ||\\vec{a}|| ||\\vec{b}|| \\sin(\\theta)$ is the area of the parallelogram formed by $\\vec{a}$ and $\\vec{b}$."),
cell("code","# Symbolic verification of orthogonality\nimport sympy as sp\na1, a2, a3, b1, b2, b3 = sp.symbols('a1 a2 a3 b1 b2 b3')\na = sp.Matrix([a1, a2, a3])\nb = sp.Matrix([b1, b2, b3])\n\ncross_prod = a.cross(b)\nprint('Cross product:\\n', cross_prod)\nprint('\\nDot product of a with (a x b) should be 0:')\nprint('Result:', sp.simplify(a.dot(cross_prod)))"),
cell("markdown","### Comprehension Check ✅\n1. What is $\\langle 1, 0, 0 \\rangle \\cdot \\langle 0, 1, 0 \\rangle$?\n2. What is the length (norm) of $\\langle 3, 4 \\rangle$?\n3. If scalar multiplication by $-1$ flips a vector, what is $\\vec{a} + (-\\vec{a})$?\n\n<details><summary>💡 Answers</summary>\n\n1. 0 (they are perpendicular axes: x and y).\n2. $\\sqrt{3^2 + 4^2} = \\sqrt{25} = 5$.\n3. $\\langle 0, 0, \\dots, 0 \\rangle$ (the zero vector).\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Compute by Hand\nGiven $\\vec{u} = \\langle 1, -2, 3 \\rangle$ and $\\vec{v} = \\langle 0, 4, 1 \\rangle$:\n1. Compute $\\vec{u} + \\vec{v}$\n2. Compute $2\\vec{u} - \\vec{v}$\n3. Compute $\\vec{u} \\cdot \\vec{v}$\n\nDo the math on paper, then write code to verify using standard Python lists."),
cell("code","def vector_math_practice():\n    u = [1, -2, 3]\n    v = [0, 4, 1]\n    # YOUR CODE HERE to compute the 3 results\n    pass\n\n# Note: You can't just do u + v in pure Python, because that concatenates lists!\n# [1,-2,3] + [0,4,1] = [1,-2,3,0,4,1]. You must add element-by-element."),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\nNow we will build a basic linear algebra library from scratch using Python lists (no numpy).\n\n### Step 1: Addition and Scalar Multiplication"),
cell("code","def vec_add(u, v):\n    '''Add two vectors of the same dimension.'''\n    # YOUR CODE HERE\n    pass\n\ndef vec_scale(scalar, v):\n    '''Multiply a vector by a scalar.'''\n    # YOUR CODE HERE\n    pass\n\n# Tests:\n# assert vec_add([1, 2], [3, 4]) == [4, 6]\n# assert vec_scale(3, [1, -2]) == [3, -6]\n# print('Step 1 passed ✅')"),
cell("markdown","### Step 2: Dot Product and Norm"),
cell("code","import math\n\ndef dot_product(u, v):\n    '''Compute the dot product of two vectors.'''\n    # YOUR CODE HERE\n    pass\n\ndef norm(v):\n    '''Compute the length of a vector using the dot product.'''\n    # YOUR CODE HERE\n    pass\n\n# Tests:\n# assert dot_product([1, 3, -5], [4, -2, -1]) == 3\n# assert norm([3, 4]) == 5.0\n# print('Step 2 passed ✅')"),
cell("markdown","### Step 3: Finding the Angle (Interleaved Practice)\nUse the formula $\\vec{a} \\cdot \\vec{b} = ||\\vec{a}|| ||\\vec{b}|| \\cos(\\theta)$ to find the angle between two vectors in radians."),
cell("code","def angle_between(u, v):\n    '''Return the angle between u and v in radians.'''\n    import math\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# angle = angle_between([1, 0], [0, 1])\n# assert abs(angle - math.pi/2) < 1e-5  # 90 degrees\n# print('Step 3 passed ✅')"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Floating Point and Orthogonality\nWhen computing angles or dot products computationally, you rarely get exactly `0.0`. Let's visualize how the dot product behaves as we rotate a vector."),
cell("code","import numpy as np, matplotlib.pyplot as plt\n\n# Vector u is fixed on the x-axis\nu = np.array([1.0, 0.0])\n\n# Vector v rotates from 0 to 2*pi\nthetas = np.linspace(0, 2*np.pi, 100)\ndot_products = []\n\nfor theta in thetas:\n    v = np.array([np.cos(theta), np.sin(theta)])\n    dot_products.append(np.dot(u, v))\n\nplt.figure(figsize=(8,4))\nplt.plot(thetas, dot_products, 'b-', lw=2)\nplt.axhline(0, color='r', ls='--')\nplt.xlabel('Angle θ (radians)')\nplt.ylabel('Dot Product (u • v)')\nplt.title('Dot Product vs Angle for Unit Vectors')\nplt.grid(alpha=0.3); plt.tight_layout(); plt.show()"),
cell("markdown","### Pathological Case: Catastrophic Cancellation in Angles\nWhen vectors are very close to parallel (angle $\\approx 0$), computing the angle via $\\cos^{-1}$ can fail due to precision loss. Specifically, if floating point math makes $\\frac{\\vec{a}\\cdot\\vec{b}}{||a|| ||b||}$ slightly greater than 1, `math.acos` will throw a Domain Error!"),
cell("code","import math\na = [1.0, 2.0, 3.0]\nb = [1.000000000000001, 2.000000000000002, 3.000000000000003] # Almost identical\n\n# Try to compute angle directly:\n# val = dot_product(a, b) / (norm(a) * norm(b))\n# print('Value passed to acos:', val)\n# angle = math.acos(val) # May crash!"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: N-Dimensional Cross Product (Exterior Product)\nThe standard cross product only works in 3D. But there is a mathematical generalization called the **Wedge Product** (or exterior product) that works in any dimension. \n\nAlternatively, in N-dimensions, given $N-1$ vectors, you can find a vector orthogonal to all of them using a generalized cross product (computed via a matrix determinant).\n\nWrite a function that takes two 3D vectors and computes their standard cross product, WITHOUT using numpy."),
cell("code","def cross_product_3d(u, v):\n    '''Return the 3D cross product of u and v.'''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# assert cross_product_3d([1,0,0], [0,1,0]) == [0,0,1]"),
cell("markdown","### Chalkboard Defense\nWrite a formal mathematical defense of why `a.dot(a x b) = 0`. Use the algebraic formula for the cross product to expand the terms and show they cancel out exactly.\n\n*(Write your defense below)*\n\n<details><summary>💡 Sketch</summary>\n\nLet $\\vec{c} = \\vec{a} \\times \\vec{b} = \\langle a_2b_3 - a_3b_2,\\; a_3b_1 - a_1b_3,\\; a_1b_2 - a_2b_1 \\rangle$.\n$\\vec{a} \\cdot \\vec{c} = a_1(a_2b_3 - a_3b_2) + a_2(a_3b_1 - a_1b_3) + a_3(a_1b_2 - a_2b_1)$\n$= a_1a_2b_3 - a_1a_3b_2 + a_2a_3b_1 - a_1a_2b_3 + a_1a_3b_2 - a_2a_3b_1 = 0$.\n</details>\n\n---\n📚 **Next:** Math 06 (Linear Algebra — Matrices)")
    ]

if __name__=="__main__":
    save(math_05(),os.path.join(OUT,"math_05_linear_algebra_vectors.ipynb"))
    print("Batch 1c done.")
