import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\n!pip install -q sympy matplotlib plotly ipywidgets\nimport sympy as sp; sp.init_printing()\nimport numpy as np, matplotlib.pyplot as plt\nprint('Ready ✅')")

def math_07():
    return [
cell("markdown","# Math 07: Calculus — Differential Equations\n\n**Learning Objectives:**\n1. Solve separable differential equations analytically\n2. Visualize differential equations using Slope Fields\n3. Implement Euler's Method to approximate solutions computationally\n\n**Prerequisites:** Math 02 (Derivatives)\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Calculus* §3.1-3.2"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### What is a Differential Equation?\n> 📖 *From Calculus §3.1:* In differential equations, we are given an equation in terms of the derivative(s) of some function, and we need to solve for the function that makes the equation true.\n\nFor example, if $\\frac{dy}{dx} = 2x$, the solution is $y = x^2 + C$.\n\n### Separation of Variables\nThe simplest differential equations can be solved by **separation of variables**, where we move all $y$ terms to one side and all $x$ terms to the other, then integrate.\n\n**Example:** Solve $\\frac{dy}{dx} = \\frac{2x}{y}$\n1. Multiply both sides by $y \\, dx$: $\\quad y \\, dy = 2x \\, dx$\n2. Integrate both sides: $\\quad \\int y \\, dy = \\int 2x \\, dx$\n3. Result: $\\quad \\frac{1}{2}y^2 = x^2 + C$\n4. Solve for $y$: $\\quad y = \\pm \\sqrt{2x^2 + C}$"),
cell("code","# Symbolic solution using SymPy\nimport sympy as sp\nx = sp.Symbol('x')\ny = sp.Function('y')(x)\nC1 = sp.Symbol('C1')\n\n# Define the equation: y' = 2x / y\node = sp.Eq(y.diff(x), 2*x / y)\n\n# Solve it\nsolution = sp.dsolve(ode, y)\nprint('General solutions:')\nfor sol in solution:\n    sp.pprint(sol)"),
cell("markdown","### Slope Fields\n> 📖 *From Calculus §3.2:* When faced with a differential equation that we don’t know how to solve, we can sometimes still approximate the solution. If we just want to get an idea of what the solutions look like on a graph, we can construct a **slope field**.\n\nA slope field is an array of short line segments. At any point $(x,y)$, the segment's slope is determined by $\\frac{dy}{dx}$. If you drop a 'raft' into this 'river' of slopes, it traces out a specific solution curve."),
cell("markdown","### Comprehension Check ✅\n1. What is the separation of variables for $\\frac{dy}{dx} = x^2 y$?\n2. What does the constant $C$ represent geometrically in a slope field?\n\n<details><summary>💡 Answers</summary>\n\n1. $\\frac{1}{y} dy = x^2 dx$\n2. $C$ selects which specific 'current' (solution curve) you follow in the slope field. It is determined by your starting point (Initial Condition).\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Solve by Hand\nSolve $\\frac{dy}{dx} = -2xy$ with the initial condition $y(0) = 1$.\nDo this on paper, then check your answer by taking the derivative of your result computationally."),
cell("code","def verify_solution():\n    import sympy as sp\n    x = sp.Symbol('x')\n    \n    # Replace 'pass' with your symbolic solution expression for y(x)\n    # Example: y_sol = sp.exp(x) \n    # YOUR CODE HERE\n    y_sol = None \n    \n    if y_sol is not None:\n        dy_dx = sp.diff(y_sol, x)\n        print(f\"Your y(x) = {y_sol}\")\n        print(f\"Derivative dy/dx = {dy_dx}\")\n        print(f\"Does dy/dx == -2*x*y? {sp.simplify(dy_dx - (-2*x*y_sol)) == 0}\")\n        print(f\"Does y(0) == 1? {y_sol.subs(x, 0) == 1}\")\n\nverify_solution()"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Visualizing a Slope Field\nLet's write a function to plot the slope field for any differential equation $\\frac{dy}{dx} = f(x, y)$."),
cell("code","def plot_slope_field(f, x_range=(-3, 3), y_range=(-3, 3), density=20):\n    '''Plot the slope field for dy/dx = f(x, y).'''\n    import numpy as np, matplotlib.pyplot as plt\n    \n    xs = np.linspace(x_range[0], x_range[1], density)\n    ys = np.linspace(y_range[0], y_range[1], density)\n    X, Y = np.meshgrid(xs, ys)\n    \n    # Evaluate the slope at each grid point\n    # YOUR CODE HERE to compute dy and dx components for quiver plot\n    # U = ... (x-component of the vector)\n    # V = ... (y-component of the vector)\n    \n    # Example visualization setup:\n    # plt.quiver(X, Y, U, V, color='blue', alpha=0.5)\n    pass\n\n# Test with dy/dx = -x/y (circles)\n# plot_slope_field(lambda x, y: -x/y if y != 0 else 0)\n# print('Step 1 passed ✅')"),
cell("markdown","### Step 2: Euler's Method (Numerical Approximation)\n> 📖 *From Calculus §3.2:* Euler's method uses the slope at the current point to take a small step forward, approximating the next point on the curve.\n\n$y_{n+1} = y_n + \\Delta x \\cdot f(x_n, y_n)$\n\nWrite a function to perform Euler's Method."),
cell("code","def euler_method(f, x0, y0, dx, num_steps):\n    '''Approximate the solution to dy/dx = f(x,y) starting at (x0, y0).'''\n    xs, ys = [x0], [y0]\n    # YOUR CODE HERE\n    return xs, ys\n\n# Test with dy/dx = y (Exponential growth), starting at (0, 1)\n# xs, ys = euler_method(lambda x, y: y, 0, 1, 0.1, 10)\n# assert abs(ys[-1] - 2.5937) < 1e-2  # Approx e^1\n# print('Step 2 passed ✅')"),
cell("markdown","### Step 3: Overlaying the Solution (Interleaved Practice)\nCombine your slope field and Euler's method to visualize the raft in the river."),
cell("code","def plot_euler_on_field(f, x0, y0, dx, num_steps):\n    '''Plot a slope field and overlay an Euler approximation curve.'''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# plot_euler_on_field(lambda x, y: y - x, 0, 0.5, 0.2, 15)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Pathological Case: Euler's Method Divergence\nEuler's method assumes the slope is constant over the step $\\Delta x$. If the curve bends sharply, Euler's method will overshoot and \"fly off\" the true curve.\nLet's visualize this with a stiff equation: $\\frac{dy}{dx} = -15y$, starting at $y(0) = 1$."),
cell("code","import numpy as np, matplotlib.pyplot as plt\n\ndef stiff_eq(x, y): return -15 * y\nexact_xs = np.linspace(0, 1, 100)\nexact_ys = np.exp(-15 * exact_xs)\n\n# Euler with a step size that is slightly too large (dx = 0.15)\n# Try changing dx to 0.05 and see what happens!\ndx = 0.15\nxs, ys = [0], [1]\nfor _ in range(int(1 / dx)):\n    xs.append(xs[-1] + dx)\n    ys.append(ys[-1] + dx * stiff_eq(xs[-2], ys[-1]))\n\nplt.figure(figsize=(8,4))\nplt.plot(exact_xs, exact_ys, 'k-', lw=2, label='True Solution $e^{-15x}$')\nplt.plot(xs, ys, 'ro-', lw=2, label=f\"Euler's Method (dx={dx})\")\nplt.title(\"Overshooting in Euler's Method\")\nplt.legend(); plt.grid(alpha=0.3); plt.show()"),
cell("markdown","### 🔍 Reflection\n1. Why did Euler's method oscillate and grow instead of decaying to 0?\n2. What relationship between the slope $-15$ and the step size $\\Delta x$ caused this?\n\n<details><summary>💡 Answer</summary>\n\nThe step formula is $y_{n+1} = y_n + \\Delta x(-15 y_n) = y_n(1 - 15\\Delta x)$.\nIf $15\\Delta x > 2$ (so $\\Delta x > 0.133$), then the multiplier is less than $-1$, causing the value to flip signs and grow exponentially in magnitude instead of shrinking.\n</details>"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Runge-Kutta 4th Order (RK4)\nEuler's method evaluates the slope once at the beginning of the step.\nRK4 evaluates the slope four times (beginning, middle x2, and end) to compute a much better average slope. It is the workhorse of scientific computing.\n\nImplement RK4 and compare its accuracy against Euler on the stiff equation."),
cell("code","def rk4_step(f, x, y, dx):\n    '''Take a single RK4 step.'''\n    # YOUR CODE HERE\n    pass\n\n# Test and plot RK4 vs Euler!\npass"),
cell("markdown","### Chalkboard Defense\nWrite a formal mathematical explanation of why RK4 has local truncation error $O(\\Delta x^5)$ compared to Euler's $O(\\Delta x^2)$.\n\n<details><summary>💡 Hint</summary>\nEuler's method is essentially a first-order Taylor series approximation: $y(x+\\Delta x) \\approx y(x) + \\Delta x y'(x)$.\nRK4 is designed to match the Taylor series expansion up to the 4th derivative term $\\frac{(\\Delta x)^4}{24}y^{(4)}(x)$.\n</details>\n\n---\n📚 **Next:** Notebook 01 (Introductory Coding) begins the Algorithms & Machine Learning track.")
    ]

if __name__=="__main__":
    save(math_07(),os.path.join(OUT,"math_07_calculus_differential_equations.ipynb"))
    print("Batch 1e done.")
