import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nimport math\nimport random\nimport matplotlib.pyplot as plt\nprint('Ready ✅')")

def algo_35_36():
    return [
cell("markdown","# Algorithms 35-36: Artificial Neural Networks\n\n**Learning Objectives:**\n1. Design a Multi-Layer Perceptron (MLP)\n2. Implement Forward Propagation using Matrix multiplications\n3. Implement Backpropagation to calculate gradients across hidden layers\n4. Train a neural network to solve the non-linear XOR problem\n\n**Prerequisites:** Algorithms 27-28\n**Estimated time:** 120 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapters 35-36"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### From Logistic Regression to Neural Networks\n> 📖 *From Algorithms:* A single logistic regression model is essentially a single \"neuron\". It takes inputs, computes a weighted sum, and passes it through a non-linear activation function.\n\nWhat if we hook up multiple neurons together? \n- The **Input Layer** receives raw data $(x_1, x_2)$.\n- The **Hidden Layer** consists of $N$ neurons. Each neuron acts as a logistic regression on the inputs, detecting different hidden \"features\".\n- The **Output Layer** is a final neuron that acts as a logistic regression on the *outputs of the hidden layer*.\n\nBy chaining linear combinations and non-linear activations, a Neural Network can approximate literally *any* mathematical function (Universal Approximation Theorem).\n\n### Backpropagation\nTo train this network via Gradient Descent, we need to know the error gradient for every single weight. \nFor the Output Layer weights, we just use the chain rule exactly like Phase 1 of the Logistic Regression notebook.\nFor the Hidden Layer weights, we use the chain rule again, propagating the error *backwards* from the output layer through the hidden layer's activation function. This algorithmic application of the Chain Rule is called **Backpropagation**."),
cell("markdown","### Comprehension Check ✅\nWhy is the non-linear activation function (like Logistic $\\sigma$, or ReLU) strictly required? What would happen if the neurons just did $z = a_1 x_1 + a_2 x_2$ and passed $z$ straight to the next layer?\n\n<details><summary>💡 Answer</summary>\nA linear combination of a linear combination is mathematically just a single linear combination. Without non-linear activation functions, a 100-layer neural network collapses into a simple $y = mx+b$ linear regression, and completely loses its ability to learn complex curves!\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: The Activation Function\nWrite the `sigmoid(x)` function, and its derivative `sigmoid_derivative(out)` where `out` is the pre-computed output of the sigmoid function (to save computation!)."),
cell("code","def sigmoid(x):\n    # YOUR CODE HERE\n    pass\n\ndef sigmoid_derivative(out):\n    # Remember from the previous notebook: sigma' = sigma * (1 - sigma)\n    # YOUR CODE HERE\n    pass"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Network Initialization\nWe will build a 2-Layer Network: \n- `input_size` = 2\n- `hidden_size` = 2\n- `output_size` = 1\n\nWe need weight matrices: `W1` (connects input to hidden) and `W2` (connects hidden to output). We also need bias vectors `b1` and `b2`.\nInitialize them with random values between -0.5 and 0.5."),
cell("code","class NeuralNetwork:\n    def __init__(self):\n        # W1: 2 inputs -> 2 hidden (2x2 matrix)\n        self.W1 = [[random.uniform(-0.5, 0.5) for _ in range(2)] for _ in range(2)]\n        self.b1 = [random.uniform(-0.5, 0.5) for _ in range(2)]\n        \n        # W2: 2 hidden -> 1 output (2x1 matrix)\n        self.W2 = [[random.uniform(-0.5, 0.5)] for _ in range(2)]\n        self.b2 = [random.uniform(-0.5, 0.5)]"),
cell("markdown","### Step 2: Forward Propagation\nPass a 1D list of inputs `X` (e.g. `[1.0, 0.0]`) through the network.\nCalculate `hidden_z`, then apply `sigmoid` to get `hidden_a`. \nCalculate `output_z`, then apply `sigmoid` to get `output_a`.\nReturn all of them, as they are needed for backpropagation!"),
cell("code","# Add to NeuralNetwork class\n# def forward(self, X):\n#     # 1. Hidden Layer\n#     hidden_a = [0.0, 0.0]\n#     for j in range(2):\n#         z = self.W1[0][j] * X[0] + self.W1[1][j] * X[1] + self.b1[j]\n#         hidden_a[j] = sigmoid(z)\n        \n#     # 2. Output Layer\n#     output_a = [0.0]\n#     z = self.W2[0][0] * hidden_a[0] + self.W2[1][0] * hidden_a[1] + self.b2[0]\n#     output_a[0] = sigmoid(z)\n    \n#     return hidden_a, output_a"),
cell("markdown","### Step 3: Backpropagation\nWe use Mean Squared Error.\nThe error signal at the output is `(output_a - target) * sigmoid_derivative(output_a)`.\nThe error signal at a hidden node `j` is `(error_signal_out * W2[j][0]) * sigmoid_derivative(hidden_a[j])`.\nUpdate the weights: $W = W - \\text{lr} \\cdot \\text{signal} \\cdot \\text{input\\_to\\_that\\_weight}$"),
cell("code","# Add to NeuralNetwork class\n# def backward(self, X, target, hidden_a, output_a, lr=0.5):\n#     # 1. Output Layer Error\n#     out_error = (output_a[0] - target) * sigmoid_derivative(output_a[0])\n    \n#     # 2. Hidden Layer Errors\n#     hid_error = [0.0, 0.0]\n#     for j in range(2):\n#         hid_error[j] = (out_error * self.W2[j][0]) * sigmoid_derivative(hidden_a[j])\n        \n#     # 3. Update W2 and b2\n#     for j in range(2):\n#         self.W2[j][0] -= lr * out_error * hidden_a[j]\n#     self.b2[0] -= lr * out_error\n    \n#     # 4. Update W1 and b1\n#     for i in range(2):\n#         for j in range(2):\n#             self.W1[i][j] -= lr * hid_error[j] * X[i]\n#     for j in range(2):\n#         self.b1[j] -= lr * hid_error[j]"),
cell("markdown","### Step 4: Training Loop\nLoop through epochs, passing each datapoint through `forward` and `backward`."),
cell("code","# Add to NeuralNetwork class\n# def train(self, data, epochs=10000, lr=0.5):\n#     for epoch in range(epochs):\n#         for X, target in data:\n#             hidden_a, output_a = self.forward(X)\n#             self.backward(X, target, hidden_a, output_a, lr)"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The XOR Problem Revisited\nIn Algorithms 27, we saw that a single linear/logistic layer CANNOT solve the XOR problem. \nLet's prove our Neural Network can!"),
cell("code","# xor_data = [\n#     ([0, 0], 0),\n#     ([0, 1], 1),\n#     ([1, 0], 1),\n#     ([1, 1], 0)\n# ]\n\n# nn = NeuralNetwork()\n# nn.train(xor_data, epochs=10000, lr=0.5)\n\n# print(\"Predictions after training:\")\n# for X, target in xor_data:\n#     _, out = nn.forward(X)\n#     print(f\"X={X} -> Pred: {out[0]:.3f} (Target: {target})\")"),
cell("markdown","---\n📚 **Next:** Algorithms 37-39 (Minimax Game Trees)")
    ]

def algo_37_39():
    return [
cell("markdown","# Algorithms 37-39: Minimax & Game Trees\n\n**Learning Objectives:**\n1. Formulate 2-player zero-sum games as a state-space Tree\n2. Implement the Minimax Algorithm to guarantee optimal play\n3. Integrate Minimax into your Tic-Tac-Toe architecture from Batch 3\n\n**Prerequisites:** Algorithms 17, Algorithms 31\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapters 37-39"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Game Trees\n> 📖 *From Algorithms Ch. 37:* A game tree represents all possible moves in a game. The current board is the \"root\". Each possible legal move creates a \"child\" branch, leading to a new board state. We can explore the tree to find winning paths.\n\n### The Minimax Algorithm\nIf we explore the tree all the way down to a Win (+1), Loss (-1), or Tie (0), we can work backwards to figure out the best move right now. \n- When it is **Our Turn**, we want to maximize our score. We will choose the child branch with the MAXIMUM score.\n- When it is the **Opponent's Turn**, we must assume they play perfectly. They want to minimize our score. They will choose the child branch with the MINIMUM score.\n\nBy recursively calling Minimax down the tree, we alternatingly take the Max and Min of the children to find the true, guaranteed value of any game state!"),
cell("markdown","### Comprehension Check ✅\nIf a board state has 3 possible moves that lead to scores of `[1, 0, -1]`:\nWhat is the Minimax value of this state if it's Our turn? \nWhat is the Minimax value if it's the Opponent's turn?\n\n<details><summary>💡 Answer</summary>\nIf it's Our turn, we pick the maximum: `1` (We force a win!).\nIf it's Their turn, they pick the minimum: `-1` (They force us to lose!).\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Minimax Pseudocode\nReview the core Minimax pseudocode:\n```python\ndef minimax(state, is_maximizing):\n    if state.is_terminal(): return state.score()\n    \n    if is_maximizing:\n        best = -infinity\n        for child in state.get_children():\n            best = max(best, minimax(child, False))\n        return best\n    else:\n        best = infinity\n        for child in state.get_children():\n            best = min(best, minimax(child, True))\n        return best\n```\nWhat is the maximum depth this recursion will reach in a standard game of Tic-Tac-Toe?"),
cell("code","# Answer here as a comment!"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The Tic-Tac-Toe Board State\nBring back your Tic-Tac-Toe Board representation from Algorithms 17. We need to add `get_legal_moves()`, `make_move(move, player)`, and `check_winner()`."),
cell("code","class Board:\n    def __init__(self, state=None):\n        self.state = state if state else [0]*9\n        \n    def get_legal_moves(self):\n        return [i for i, val in enumerate(self.state) if val == 0]\n        \n    def make_move(self, index, player):\n        # Return a NEW Board instance so we don't mutate the current one during tree search!\n        new_state = self.state.copy()\n        new_state[index] = player\n        return Board(new_state)\n        \n    def check_winner(self):\n        # Check rows, cols, diags for 1 (X) or -1 (O)\n        # Return 1 if X wins, -1 if O wins, 0 if tie, None if incomplete\n        # YOUR CODE HERE\n        pass"),
cell("markdown","### Step 2: Implementing Minimax\nWrite `minimax(board, is_maximizing_player)`. Assume X is maximizing (+1) and O is minimizing (-1)."),
cell("code","def minimax(board, is_maximizing):\n    winner = board.check_winner()\n    if winner is not None:\n        return winner # Base case: terminal state\n        \n    if is_maximizing:\n        best_score = -math.inf\n        for move in board.get_legal_moves():\n            # 1. Create child board by making move for X (1)\n            # 2. Call minimax(child, False)\n            # 3. best_score = max(best_score, result)\n            pass\n        return best_score\n    else:\n        best_score = math.inf\n        for move in board.get_legal_moves():\n            # 1. Create child board by making move for O (-1)\n            # 2. Call minimax(child, True)\n            # 3. best_score = min(best_score, result)\n            pass\n        return best_score"),
cell("markdown","### Step 3: Extracting the Best Move\nMinimax returns the *score* of the board, not the move. Write `get_best_move(board, player)` which loops through legal moves, calls Minimax on each, and returns the move with the best score!"),
cell("code","def get_best_move(board, player):\n    best_move = None\n    # if player == 1 (Maximizing):\n    #   best_score = -inf\n    #   loop moves, child = make_move, score = minimax(child, False)\n    #   if score > best_score, update best_move\n    \n    # if player == -1 (Minimizing):\n    #   best_score = inf\n    #   loop moves, child = make_move, score = minimax(child, True)\n    #   if score < best_score, update best_move\n    \n    # YOUR CODE HERE\n    pass"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Unbeatable AI\nPlay a game against your Minimax AI. Try to beat it! (Spoiler: You can't. The best you can do is tie!)"),
cell("code","# b = Board()\n# while b.check_winner() is None:\n#     # You play X (1)\n#     print(b.state[:3]); print(b.state[3:6]); print(b.state[6:])\n#     move = int(input(\"Enter move 0-8: \"))\n#     b = b.make_move(move, 1)\n#     if b.check_winner() is not None: break\n    \n#     # AI plays O (-1)\n#     print(\"AI is thinking...\")\n#     ai_move = get_best_move(b, -1)\n#     b = b.make_move(ai_move, -1)\n    \n# print(\"Game Over! Winner:\", b.check_winner())"),
cell("markdown","---\n📚 **Next:** Algorithms 40-42 (Neuroevolution)")
    ]

def algo_40_42():
    return [
cell("markdown","# Algorithms 40-42: Neuroevolution & Blondie24\n\n**Learning Objectives:**\n1. Combine Neural Networks and Evolutionary Algorithms\n2. Replicate Fogel & Chellapilla's *Blondie24* checkers player\n3. Train networks through pure self-play tournaments without datasets or backpropagation\n\n**Prerequisites:** Algorithms 35-36\n**Estimated time:** 180 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapters 40-42"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Problem with Gradient Descent in Games\n> 📖 *From Algorithms Ch. 42:* When training an AI to play Checkers, we don't have a dataset of \"perfect moves\". And we can't easily backpropagate through thousands of discrete game tree decisions.\n\n### Neuroevolution\nInstead of calculating gradients mathematically, we use **Darwinian Evolution**!\n1. **Initialize** 15 random Neural Networks.\n2. **Mutate**: Each network generates a \"child\" with slightly randomized weights.\n3. **Evaluate**: We now have 30 networks. We make them play Checkers against each other in a massive tournament! We track how many games each network wins.\n4. **Select**: We kill the 15 lowest-scoring networks. The 15 best networks survive.\n5. Go back to step 2 and repeat for 800 generations!\n\nThis exact technique was used by Fogel & Chellapilla in 1999 to create *Blondie24*, a Checkers AI that taught itself to achieve an expert rating on an online gaming site, entirely through self-play!"),
cell("markdown","### Comprehension Check ✅\nWhy do we mutate the weights randomly instead of trying to calculate which direction is best?\n\n<details><summary>💡 Answer</summary>\nBecause the \"fitness landscape\" of a complex game is highly jagged, and we have no mathematical formula to compute the gradient of \"winning a game of checkers\". Random mutation, combined with strict selection, effectively acts as a \"stochastic gradient descent\" that explores the landscape blindly but relentlessly moves uphill toward mastery.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Gaussian Mutation\nWrite a function `mutate(network, mutation_rate=0.05)` that loops through all the weights and biases of a Neural Network and adds random Gaussian noise. `weight += random.gauss(0, mutation_rate)`."),
cell("code","import random\ndef mutate(network_weights, mutation_rate=0.05):\n    # network_weights is a flat list for simplicity, or 2D matrices\n    # loop and add random.gauss(0, mutation_rate)\n    # YOUR CODE HERE\n    pass"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The Agent Network\nFor this lab, instead of full Checkers (which takes hours to run), we will evolve a Neural Network to evaluate Tic-Tac-Toe boards. The network takes 9 inputs, and outputs a score from -1 to 1 representing how \"good\" the board is for X.\n\n*Note: We can use the MLP you built in Algorithms 35-36, but change the input size to 9.*"),
cell("code","class NeuroAgent:\n    def __init__(self, copy_from=None):\n        if copy_from:\n            # Deep copy weights from parent\n            pass\n        else:\n            # Initialize random weights (9 -> 5 -> 1)\n            pass\n            \n    def mutate(self):\n        # Apply gaussian noise to all weights\n        pass\n        \n    def evaluate_board(self, board_state):\n        # Forward pass! Return single output float.\n        pass"),
cell("markdown","### Step 2: Action Selection (Heuristic Minimax)\nThe Agent uses its Neural Network as the heuristic evaluation function for Minimax. Instead of searching all the way to the end of the game, it searches `depth=2`, and uses `evaluate_board` to score the resulting states!"),
cell("code","def get_neuro_move(agent, board, player, depth=2):\n    # A simplified version:\n    # Generate all legal moves.\n    # For each move, simulate it.\n    # Pass the resulting board into agent.evaluate_board().\n    # If player is 1, pick the move with the highest eval.\n    # If player is -1, pick the move with the lowest eval.\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Step 3: The Tournament Evaluation\nWrite `evaluate_generation(population)` that pits agents against each other in random pairings. \nReturn their total scores (+1 for win, 0 for tie, -2 for loss)."),
cell("code","def evaluate_generation(population):\n    scores = {agent: 0 for agent in population}\n    \n    # E.g. each agent plays 5 games against random opponents\n    # for agent in population:\n    #    for _ in range(5):\n    #        opponent = random.choice(population)\n    #        play_game(agent, opponent) \n    #        update scores based on winner\n    # YOUR CODE HERE\n    \n    return scores"),
cell("markdown","### Step 4: Evolution Loop\nLoop through `G` generations!"),
cell("code","def evolve(generations=50):\n    # 1. Init population of 15\n    population = [NeuroAgent() for _ in range(15)]\n    \n    for g in range(generations):\n        # 2. Mutate: create 15 children\n        children = []\n        for p in population:\n            child = NeuroAgent(copy_from=p)\n            child.mutate()\n            children.append(child)\n            \n        # 3. Evaluate all 30\n        full_pop = population + children\n        scores = evaluate_generation(full_pop)\n        \n        # 4. Select top 15 to survive\n        # sort full_pop by scores, keep top 15\n        # population = ...\n        \n        print(f\"Gen {g} Max Score: {max(scores.values())}\")\n        \n    return population[0] # Return the GOAT"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### The Ultimate Test\nTrain your population for 50 generations. Then play a game against the GOAT!\nDoes it play better than random? Did it learn to block your wins without *ever* being explicitly told the rules of the game?"),
cell("code","# goat = evolve(50)\n# play_human_vs_agent(goat)"),
cell("markdown","---\n📚 **Next:** Algorithms 43 (Convolutional Blondie24)")
    ]

def algo_43():
    return [
cell("markdown","# Algorithms 43: Convolutional Blondie24\n\n**Learning Objectives:**\n1. Understand the spatial limits of standard MLPs\n2. Design a Convolutional Neural Network (CNN) architecture\n3. Re-implement the Convolutional layer of Blondie24\n\n**Prerequisites:** Algorithms 40-42\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 43"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Spatial Problem\n> 📖 *From Algorithms Ch. 43:* In 2001, Fogel & Chellapilla improved Blondie24 by adding a **Convolutional Layer**. This acts as a spatial preprocessing layer, allowing the network to perceive spatial characteristics of the board at different levels of zoom.\n\nIn a standard MLP, the $8 \\times 8$ checkers board is flattened into a 64-element 1D list. The network completely loses the 2D geometric structure! It doesn't know that square 1 is \"above\" square 9.\n\n### The Convolutional Concept\nA convolutional layer fixes this by processing 2D patches of the board.\nBlondie24 defined subnetworks that look at every possible $3 \\times 3$, $4 \\times 4$, $5 \\times 5$, $6 \\times 6$, $7 \\times 7$, and $8 \\times 8$ subsquare of the board!\n- For an $8 \\times 8$ board, there are 36 possible $3 \\times 3$ subsquares.\n- Each of these 36 patches has its own node in the Convolutional Layer.\n\nThis structure mathematically forces the neural network to \"see\" localized 2D patterns (like an opponent setting up a jump) before making decisions!"),
cell("markdown","### Comprehension Check ✅\nWhy did the addition of the convolutional layer increase the number of weights in Blondie24 from 1,742 to 5,047?\n\n<details><summary>💡 Answer</summary>\nBecause the input layer now connects to 92 different convolutional nodes ($1 + 4 + 9 + 16 + 25 + 36 + 1$), and each connection processes a 2D patch of inputs, requiring vastly more weight matrices to filter the visual information.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Calculating Subsquares\nIf you have an $N \\times N$ board, how many $K \\times K$ subsquares can fit inside it? \nWrite a function to return the count."),
cell("code","def count_subsquares(N, K):\n    # An N=8 board has (8-3+1) = 6 horizontal positions for a K=3 square.\n    # YOUR CODE HERE\n    pass\n\n# assert count_subsquares(8, 3) == 36\n# assert count_subsquares(8, 8) == 1"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Extracting 2D Patches\nWrite a function `get_patches(board_2d, K)` that takes an $8 \\times 8$ 2D list and returns a list of all $K \\times K$ patches. Each patch should be flattened into a 1D list of length $K^2$."),
cell("code","def get_patches(board_2d, K):\n    patches = []\n    N = len(board_2d)\n    for r in range(N - K + 1):\n        for c in range(N - K + 1):\n            # Extract the KxK patch starting at row r, col c\n            # Flatten it and append to patches\n            # YOUR CODE HERE\n            pass\n    return patches"),
cell("markdown","### Step 2: The Convolutional Forward Pass\nImagine a single Convolutional Filter with a weight vector `W` of size $K^2$.\nWrite `conv_forward(board_2d, K, W)` that extracts the patches, computes the dot product of each patch with `W`, and applies `tanh`. Return the list of outputs!"),
cell("code","import math\ndef tanh(x):\n    return math.tanh(x)\n\ndef conv_forward(board_2d, K, W):\n    patches = get_patches(board_2d, K)\n    outputs = []\n    for patch in patches:\n        # dot product patch and W\n        # z = sum(p * w for p, w in zip(patch, W))\n        # outputs.append(tanh(z))\n        # YOUR CODE HERE\n        pass\n    return outputs"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Edge Detection\nConvolutional filters are famous for Edge Detection. Let's create an $8 \\times 8$ board with a \"vertical line\" of pieces, and apply a $3 \\times 3$ vertical edge filter!\n`W_vertical = [-1, 2, -1, -1, 2, -1, -1, 2, -1]`"),
cell("code","board = [[0]*8 for _ in range(8)]\nfor r in range(8):\n    board[r][3] = 1 # A vertical line of pieces at column 3\n\n# W_vert = [-1, 2, -1, -1, 2, -1, -1, 2, -1]\n# outputs = conv_forward(board, 3, W_vert)\n\n# The output will be a list of 36 values. If we reshape it to a 6x6 grid, \n# we should see strong positive activations right where the vertical line is!\n\n# print(\"Convolutional Outputs (6x6):\")\n# for r in range(6):\n#     print([round(val, 2) for val in outputs[r*6 : (r+1)*6]])"),
cell("markdown","---\n## 🎉 Congratulations! 🎉\nYou have completed the Advanced Algorithms curriculum. You've journeyed from solving linear equations, to optimizing game trees with Minimax, to training spatial AI using Neuroevolution and Convolutional Networks! \n\nYou are now ready to tackle real-world Machine Learning challenges.")
    ]

if __name__=="__main__":
    save(algo_35_36(),os.path.join(OUT,"35-36_neural_networks.ipynb"))
    save(algo_37_39(),os.path.join(OUT,"37-39_minimax_game_trees.ipynb"))
    save(algo_40_42(),os.path.join(OUT,"40-42_neuroevolution.ipynb"))
    save(algo_43(),os.path.join(OUT,"43_convolutional_blondie24.ipynb"))
    print("Notebooks 35 to 43 generated.")
