import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\nimport math\nimport matplotlib.pyplot as plt\nprint('Ready ✅')")

def algo_18():
    return [
cell("markdown","# Algorithms 18: Euler Estimation\n\n**Learning Objectives:**\n1. Solve ordinary differential equations (ODEs) computationally using Euler's Method\n2. Generalize 1D Euler Estimation to Multivariable Systems of ODEs\n3. Use Matplotlib to visualize the trajectories of state variables\n\n**Prerequisites:** Calculus (Derivatives)\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 18"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Idea Behind Euler's Method\n> 📖 *From Algorithms Ch. 18:* Arrays can be used to implement mathematical procedures like Euler estimation to solve differential equations.\n\nIf we know the derivative $f'(x, y)$ (the slope), and we know a starting point $(x_0, y_0)$, we can approximate the next point by taking a tiny step $\\Delta x$ along the tangent line:\n$$y_{n+1} = y_n + f'(x_n, y_n) \\cdot \\Delta x$$\n$$x_{n+1} = x_n + \\Delta x$$\n\nBy chaining these tiny steps together, we can trace out the entire curve $y(x)$ without ever actually integrating the function analytically!\n\n### Multivariable Systems\nIf we have a *system* of differential equations, e.g., \n$$a'(t) = a(t) + 1$$\n$$b'(t) = a(t) + b(t)$$\n\nWe simply update *all* variables simultaneously at each step:\n$$a_{n+1} = a_n + a'(t, a_n, b_n) \\cdot \\Delta t$$\n$$b_{n+1} = b_n + b'(t, a_n, b_n) \\cdot \\Delta t$$\n$$t_{n+1} = t_n + \\Delta t$$"),
cell("markdown","### Comprehension Check ✅\n1. What happens if the step size $\\Delta x$ is extremely large (e.g., 5.0)?\n2. What happens if the step size $\\Delta x$ is extremely small (e.g., 0.00000001)?\n\n<details><summary>💡 Answers</summary>\n\n1. The approximation becomes terrible. The curve will look jagged and will likely diverge from the true mathematical solution because it assumes the slope is constant over that huge interval.\n2. The approximation becomes nearly perfect, but the computer will take millions of loop iterations to compute a short interval, making the program unacceptably slow.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: A Manual Step\nGiven $\\frac{dy}{dx} = x - 2$. \nStart at $x = 0, y = 1$.\nTake one step of $\\Delta x = 0.5$.\nWhat is the new $x$ and $y$?\n\n*(Compute it manually, then run the code to verify)*"),
cell("code","def derivative(x, y):\n    return x - 2\n\n# Calculate step 1\nx0, y0 = 0, 1\ndx = 0.5\n# slope = derivative(x0, y0)\n# y1 = y0 + slope * dx\n# x1 = x0 + dx\n# print(x1, y1) # Should be 0.5, 0.0"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Single-Variable Euler Estimator\nWrite a class `EulerEstimator`. It should take a derivative function $f(x, y)$ in its constructor.\nThe `calc_derivative_at_point` method simply calls the function.\nThe `step` method calculates the next point.\nThe `calc_estimated_points` method loops and generates a list of $(x, y)$ tuples up to a `target_x`."),
cell("code","class EulerEstimator:\n    def __init__(self, derivative_function):\n        self.f = derivative_function\n        \n    def calc_derivative_at_point(self, point):\n        # point is a tuple (x, y)\n        # YOUR CODE HERE\n        pass\n        \n    def step(self, point, step_size):\n        # Calculate slope, then calculate new_x and new_y\n        # YOUR CODE HERE\n        pass\n        \n    def calc_estimated_points(self, point, step_size, target_x):\n        # Keep stepping until current_x >= target_x\n        # Return a list of all points (including the starting point)\n        points = [point]\n        # YOUR CODE HERE\n        return points"),
cell("markdown","### Step 2: Multivariable Euler Estimator\nNow upgrade it! A state is no longer $(x, y)$, but $(t, a, b, c, \\dots)$.\nRepresent a point as a tuple `(t, state_tuple)`. \nThe derivative function will now return a tuple of derivatives, one for each state variable."),
cell("code","class MultiEulerEstimator:\n    def __init__(self, derivative_functions):\n        # derivative_functions is a LIST of functions, one for each state variable\n        self.functions = derivative_functions\n        \n    def calc_derivatives_at_point(self, point):\n        t, state = point\n        # Loop through self.functions, evaluate each one at (t, state), and return a tuple of slopes\n        # YOUR CODE HERE\n        pass\n        \n    def step(self, point, step_size):\n        t, state = point\n        slopes = self.calc_derivatives_at_point(point)\n        \n        # new_t = t + step_size\n        # new_state = tuple( s + slope * step_size for s, slope in zip(state, slopes) )\n        # YOUR CODE HERE\n        pass\n        \n    def calc_estimated_points(self, point, step_size, num_steps):\n        # Similar to before, but take exactly `num_steps` steps\n        # YOUR CODE HERE\n        pass"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Visualizing the Single-Variable System\nLet's plot solutions to $\\frac{dy}{dx} = x - 2$ on the interval $[0, 5]$.\nWe'll plot 5 curves, starting at $y(0) = -2, -1, 0, 1, 2$."),
cell("code","estimator = EulerEstimator(lambda x, y: x - 2)\nstep_size = 0.1\ntarget_x = 5\n\n# For initial_y in [-2, -1, 0, 1, 2]:\n#     pts = estimator.calc_estimated_points((0, initial_y), step_size, target_x)\n#     xs = [p[0] for p in pts]\n#     ys = [p[1] for p in pts]\n#     plt.plot(xs, ys, label=f\"y(0)={initial_y}\")\n    \n# plt.legend(); plt.grid(True)\n# plt.title(\"dy/dx = x - 2\")\n# plt.show()"),
cell("markdown","### Visualizing the Multivariable System\nSimulate this system:\n$a'(t) = a + 1$\n$b'(t) = a + b$\n$c'(t) = 2b + 3t$\nInitial state at $t = -0.4$ is $a = -0.45, b = -0.05, c = 0$. Step size $0.01$ for $100$ steps."),
cell("code","def da_dt(t, state): return state[0] + 1\ndef db_dt(t, state): return state[0] + state[1]\ndef dc_dt(t, state): return 2*state[1] + 3*t\n\nmulti_est = MultiEulerEstimator([da_dt, db_dt, dc_dt])\ninitial_point = (-0.4, (-0.45, -0.05, 0.0))\n\n# pts = multi_est.calc_estimated_points(initial_point, 0.01, 100)\n# ts = [p[0] for p in pts]\n# a_s = [p[1][0] for p in pts]\n# b_s = [p[1][1] for p in pts]\n# c_s = [p[1][2] for p in pts]\n\n# plt.plot(ts, a_s, label='a(t)')\n# plt.plot(ts, b_s, label='b(t)')\n# plt.plot(ts, c_s, label='c(t)')\n# plt.legend(); plt.grid(True); plt.show()"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Chalkboard Defense\nOur Euler estimator uses the formula $y_{n+1} = y_n + f'(x_n, y_n) \\cdot \\Delta x$. This uses the slope at the *beginning* of the interval.\nExplain why this \"forward\" Euler method systematically overestimates or underestimates curves that are concave up or concave down. How could we improve it?\n\n<details><summary>💡 Sketch</summary>\nIf a curve is bending upwards (concave up), its slope is constantly increasing. But forward Euler locks in the slope at the start of the interval, extending a straight line. Because the true curve bends up *away* from this line, Euler systematically underestimates the curve.\nA better approach is the Runge-Kutta (RK4) method, which calculates the slope at the beginning, midpoint, and end of the interval, and takes a weighted average to predict the curve's bend!\n</details>\n\n---\n📚 **Next:** Algorithms 19 (SIR Epidemic Model)")
    ]

def algo_19():
    return [
cell("markdown","# Algorithms 19: SIR Model For the Spread of Disease\n\n**Learning Objectives:**\n1. Formulate the SIR (Susceptible, Infected, Recovered) ODE equations\n2. Understand population dynamics and transmission rates\n3. Simulate an epidemic outbreak using Multivariable Euler Estimation\n\n**Prerequisites:** Algorithms 18\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 19"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The SIR Compartmental Model\n> 📖 *From Algorithms Ch. 19:* The SIR model assumes three sub-populations: Susceptible ($S$), Infected ($I$), and Recovered ($R$).\n\nLet's model the rate of change of each group over time $t$ (days):\n\n**1. Susceptible Population ($S$)**\nSusceptible people decrease as they catch the disease from infected people. The number of meetings between the groups is proportional to $S \\times I$.\n$\\frac{dS}{dt} = - \\text{transmission\\_rate} \\times \\text{meeting\\_factor} \\times S \\times I$\n\n**2. Infected Population ($I$)**\nInfected people increase when susceptible people catch the disease, and decrease when infected people recover.\n$\\frac{dI}{dt} = (\\text{transmission\\_rate} \\times \\text{meeting\\_factor} \\times S \\times I) - (\\text{recovery\\_rate} \\times I)$\n\n**3. Recovered Population ($R$)**\nRecovered people increase as infected people recover.\n$\\frac{dR}{dt} = \\text{recovery\\_rate} \\times I$"),
cell("markdown","### Comprehension Check ✅\n1. What happens mathematically to $\\frac{dS}{dt}$ if the number of Infected people ($I$) reaches 0?\n2. What is the sum of $\\frac{dS}{dt} + \\frac{dI}{dt} + \\frac{dR}{dt}$ at any given moment, and what does this mean physically?\n\n<details><summary>💡 Answers</summary>\n\n1. It becomes 0. The disease is eradicated, so no one else can catch it. Susceptible population remains constant.\n2. The sum is exactly 0. This means the total population $N = S + I + R$ is strictly conserved. No one dies or is born in this simplified model; they just move between the three buckets.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Translating Word Problems to Code\nGiven:\n- Initial state: $S = 1000, I = 1, R = 0$.\n- Meeting factor: $0.01$\n- Transmission rate: $3\\%$ ($0.03$)\n- Recovery rate: $2\\%$ ($0.02$)\n\nDefine the constants, then calculate $\\frac{dS}{dt}$, $\\frac{dI}{dt}$, and $\\frac{dR}{dt}$ at $t=0$."),
cell("code","S = 1000\nI = 1\nR = 0\n\nmeeting_factor = 0.01\ntransmission_rate = 0.03\nrecovery_rate = 0.02\n\n# dS_dt = - transmission_rate * meeting_factor * S * I\n# dI_dt = (transmission_rate * meeting_factor * S * I) - (recovery_rate * I)\n# dR_dt = recovery_rate * I\n\n# print(f\"dS/dt = {dS_dt}\") # Should be -0.3\n# print(f\"dI/dt = {dI_dt}\") # Should be  0.28\n# print(f\"dR/dt = {dR_dt}\") # Should be  0.02"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Defining the Differential Equation Functions\nBring over your `MultiEulerEstimator` class from the previous notebook. \nThen, define the three derivative functions: `dS_dt(t, state)`, `dI_dt(t, state)`, `dR_dt(t, state)` where `state` is the tuple `(S, I, R)`."),
cell("code","# PASTE MultiEulerEstimator HERE\nclass MultiEulerEstimator:\n    def __init__(self, funcs):\n        self.functions = funcs\n    def calc_derivatives_at_point(self, point):\n        t, state = point\n        return tuple(f(t, state) for f in self.functions)\n    def step(self, point, step_size):\n        t, state = point\n        slopes = self.calc_derivatives_at_point(point)\n        new_state = tuple(s + sl*step_size for s, sl in zip(state, slopes))\n        return (t + step_size, new_state)\n    def calc_estimated_points(self, point, step_size, target_time):\n        points = [point]\n        curr = point\n        while curr[0] < target_time:\n            curr = self.step(curr, step_size)\n            points.append(curr)\n        return points\n\n# DEFINE THE DIFFERENTIAL EQUATIONS HERE\n# def dS_dt(t, state):\n#     S, I, R = state\n#     return -0.03 * 0.01 * S * I\n\n# def dI_dt(t, state):\n#     # YOUR CODE HERE\n#     pass\n\n# def dR_dt(t, state):\n#     # YOUR CODE HERE\n#     pass"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Simulating the Outbreak\nInitialize your estimator. Start at `t = 0` with state `(1000, 1, 0)`. \nUse a step size of `0.1` and target time of `60` days. Plot $S$, $I$, and $R$ over time."),
cell("code","# multi_est = MultiEulerEstimator([dS_dt, dI_dt, dR_dt])\n# pts = multi_est.calc_estimated_points((0.0, (1000.0, 1.0, 0.0)), step_size=0.1, target_time=60)\n\n# ts = [p[0] for p in pts]\n# s_vals = [p[1][0] for p in pts]\n# i_vals = [p[1][1] for p in pts]\n# r_vals = [p[1][2] for p in pts]\n\n# plt.plot(ts, s_vals, label=\"Susceptible (S)\", color='blue')\n# plt.plot(ts, i_vals, label=\"Infected (I)\", color='red')\n# plt.plot(ts, r_vals, label=\"Recovered (R)\", color='green')\n# plt.legend(); plt.grid(True)\n# plt.title(\"SIR Epidemic Simulation\")\n# plt.xlabel(\"Days\"); plt.ylabel(\"Population\")\n# plt.show()"),
cell("markdown","### 🔍 Reflection\nLook at your plot. At what day does the infection \"peak\"? \nNotice that the pandemic ends *not* because the virus magically vanishes, but because the Susceptible pool shrinks so low that the virus cannot find new hosts fast enough to outpace the recovery rate. This is the definition of **Herd Immunity**!"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Flattening the Curve\nWhat happens if we introduce social distancing? Modify the `meeting_factor` from `0.01` to `0.005`.\nRe-run the simulation. You will notice the red peak is much lower and delayed! But notice the tradeoff: the pandemic lasts much longer.\n*(Try modifying your functions and plotting the two I(t) curves on top of each other!)*"),
cell("code","# YOUR CODE HERE\npass"),
cell("markdown","### Chalkboard Defense\nOur SIR model assumes that once you recover, you have permanent immunity (you join bucket $R$ and stay there forever). \nIf the disease mutates and immunity only lasts 30 days, how would you change the differential equations to make this an **SIRS model**?\n\n<details><summary>💡 Sketch</summary>\nYou would add a term that drains population from $R$ and puts it back into $S$ after a delay, or at a constant rate. \n$\\frac{dS}{dt} = -(\\dots) + \\text{immunity\\_loss\\_rate} \\times R$\n$\\frac{dR}{dt} = \\text{recovery\\_rate} \\times I - \\text{immunity\\_loss\\_rate} \\times R$\nThis causes the disease to become *endemic*, creating a constant wave of infections that never permanently dies out.\n</details>\n\n---\n📚 **Next:** Algorithms 20 (Hodgkin-Huxley Model)")
    ]

def algo_20():
    return [
cell("markdown","# Algorithms 20: Hodgkin-Huxley Model of Action Potentials\n\n**Learning Objectives:**\n1. Translate massive systems of biological ODEs into Python code\n2. Handle time-dependent stimulus functions $s(t)$\n3. Simulate a neuron firing an Action Potential (Spike)\n\n**Prerequisites:** Algorithms 18\n**Estimated time:** 120 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 20"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### The Biophysics of a Neuron\n> 📖 *From Algorithms Ch. 20:* In 1952, Alan Hodgkin and Andrew Huxley published a differential equation model of “action potentials” in the voltage of neurons, winning a Nobel Prize.\n\nThe current $I$ entering a neuron consists of:\n- $s(t)$: External stimulus (like an electrode)\n- $I_{Na}$: Sodium channel flux (increases voltage)\n- $I_{K}$: Potassium channel flux (decreases voltage)\n- $I_{L}$: Leakage current\n\nThe voltage equation is: $\\frac{dV}{dt} = \\frac{1}{C}[s(t) - I_{Na} - I_{K} - I_{L}]$\n\nThe channel currents depend on gating variables $n$ (potassium activation), $m$ (sodium activation), and $h$ (sodium inactivation), which themselves are governed by their own differential equations:\n$\\frac{dn}{dt} = \\alpha_n(V)(1 - n) - \\beta_n(V)n$\n\nThe $\\alpha$ and $\\beta$ functions are complex exponentials derived experimentally.\nThis is a 4-variable nonlinear system: State is $(V, n, m, h)$!"),
cell("markdown","### Comprehension Check ✅\n1. Why are $n$, $m$, and $h$ restricted between 0 and 1?\n2. Notice that the external stimulus is a function of time, $s(t)$. If $s(t) = 0$, what should the neuron's voltage do?\n\n<details><summary>💡 Answers</summary>\n\n1. They represent the *probability* that a certain ion channel gate is open. $0 = 0\\%$ open, $1 = 100\\%$ open.\n2. It should stay at its resting potential ($V=0$ in our shifted coordinate system). If bumped slightly, the leakage current $I_L$ will drag it back to 0.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: The $\\alpha$ and $\\beta$ Functions\nLet's write out the mathematical functions for the Potassium ($n$) gate.\n$\\alpha_n(V) = 0.01(10 - V) / (\\exp(0.1(10 - V)) - 1)$\n$\\beta_n(V) = 0.125 \\exp(-V / 80)$\n\n*(Careful! If $V=10$, $\\alpha_n$ divides by zero! Use `V = 10.0001` or L'Hopital's limit in your code)*"),
cell("code","import math\n\ndef alpha_n(V):\n    if abs(10 - V) < 1e-6: V += 1e-6 # prevent division by zero\n    return 0.01 * (10 - V) / (math.exp(0.1 * (10 - V)) - 1)\n\ndef beta_n(V):\n    return 0.125 * math.exp(-V / 80)\n\n# print(alpha_n(0), beta_n(0))"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: Implementing the rest of the constants\nWrite the $\\alpha$ and $\\beta$ functions for $m$ and $h$, and define the constants.\n\n$\\alpha_m(V) = 0.1(25 - V) / (\\exp(0.1(25 - V)) - 1)$\n$\\beta_m(V) = 4 \\exp(-V / 18)$\n\n$\\alpha_h(V) = 0.07 \\exp(-V / 20)$\n$\\beta_h(V) = 1 / (\\exp(0.1(30 - V)) + 1)$"),
cell("code","# CONSTANTS\nC = 1.0\nV_Na = 115\nV_K = -12\nV_L = 10.6\n\ng_Na_bar = 120\ng_K_bar = 36\ng_L_bar = 0.3\n\n# YOUR CODE HERE to define alpha_m, beta_m, alpha_h, beta_h\npass"),
cell("markdown","### Step 2: The Time-Dependent Stimulus\nWe will inject current pulses at specific time intervals to trigger spikes. \nWrite $s(t)$ which returns 150 if $t$ is inside certain intervals, and 0 otherwise.\nThe intervals are: `[10, 11], [20, 21], [30, 40], [50, 51], [53, 54], [56, 57], [59, 60], [62, 63], [65, 66]`."),
cell("code","def s_t(t):\n    intervals = [(10,11), (20,21), (30,40), (50,51), (53,54), (56,57), (59,60), (62,63), (65,66)]\n    for start, end in intervals:\n        if start <= t <= end:\n            return 150.0\n    return 0.0"),
cell("markdown","### Step 3: The 4 Differential Equations\nState is `(V, n, m, h)`. Write `dV_dt`, `dn_dt`, `dm_dt`, `dh_dt`.\nRecall:\n$I_{Na} = g_{Na} \\cdot m^3 h \\cdot (V - V_{Na})$\n$I_{K} = g_{K} \\cdot n^4 \\cdot (V - V_{K})$\n$I_{L} = g_{L} \\cdot (V - V_{L})$\n$dV/dt = (s(t) - I_{Na} - I_{K} - I_{L}) / C$"),
cell("code","# def dV_dt(t, state):\n#     V, n, m, h = state\n#     I_Na = g_Na_bar * (m**3) * h * (V - V_Na)\n#     I_K = g_K_bar * (n**4) * (V - V_K)\n#     I_L = g_L_bar * (V - V_L)\n#     return (s_t(t) - I_Na - I_K - I_L) / C\n\n# def dn_dt(t, state):\n#     V, n, m, h = state\n#     return alpha_n(V)*(1 - n) - beta_n(V)*n\n\n# WRITE dm_dt and dh_dt\n# YOUR CODE HERE"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Firing the Neuron\nBring over `MultiEulerEstimator`. \nInitial state at $t=0$ is $V = 0$, and the asymptotic limits for $n, m, h$: \n$n_0 = \\alpha_n(0) / (\\alpha_n(0) + \\beta_n(0))$\nStep from 0 to 80 ms with $\\Delta t = 0.01$ ms. Plot $V(t)$."),
cell("code","# PASTE MultiEulerEstimator HERE\n\n# Calculate initial state\n# n0 = alpha_n(0) / (alpha_n(0) + beta_n(0))\n# m0 = alpha_m(0) / (alpha_m(0) + beta_m(0))\n# h0 = alpha_h(0) / (alpha_h(0) + beta_h(0))\n# initial_state = (0.0, n0, m0, h0)\n\n# multi_est = MultiEulerEstimator([dV_dt, dn_dt, dm_dt, dh_dt])\n# pts = multi_est.calc_estimated_points((0.0, initial_state), 0.01, 80.0)\n\n# ts = [p[0] for p in pts]\n# Vs = [p[1][0] for p in pts]\n\n# plt.plot(ts, Vs, color='black')\n# plt.title(\"Hodgkin-Huxley Action Potentials\")\n# plt.xlabel(\"Time (ms)\"); plt.ylabel(\"Voltage (mV)\"); plt.grid(True)\n# plt.show()"),
cell("markdown","### 🔍 Reflection\nNotice the long stimulus from $t=30$ to $40$ causes a train of multiple rapid spikes! This is how your nervous system encodes high-intensity stimuli: not by larger spikes (spikes are all-or-nothing), but by a higher *frequency* of spikes.\n\n---\n📚 **Next:** Algorithms 21 (Hash Tables)")
    ]

def algo_21():
    return [
cell("markdown","# Algorithms 21: Hash Tables\n\n**Learning Objectives:**\n1. Understand how Dictionaries/Maps are implemented under the hood\n2. Design a Hash Function\n3. Implement a Hash Table with Buckets to handle collisions\n\n**Prerequisites:** Algorithms 01\n**Estimated time:** 60 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 21"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Dictionaries are Hash Tables\n> 📖 *From Algorithms Ch. 21:* Under the hood, dictionaries are hash tables. The most elementary (and inefficient) version of a dictionary is just a list of `(key, value)` tuples.\n\nIf we have 1 million tuples, looking up a key requires $O(N)$ time. We must scan the whole list.\n\n### The Solution: Buckets and Hash Functions\nInstead of 1 giant list, what if we have 100 separate lists (\"buckets\")? \nWe use a **Hash Function** that takes the string key, does some math on it, and spits out an integer from $0$ to $99$. \nNow, when we insert `(\"apple\", 5)`, the hash function says `hash(\"apple\") = 42`. We instantly go to bucket 42 and append it there.\nWhen we want to look up `\"apple\"`, we hash it, get 42, go to bucket 42, and search that tiny list. Time complexity drops to $O(1)$!"),
cell("markdown","### Comprehension Check ✅\n1. What is a \"Collision\" in a hash table?\n2. What happens if our Hash Function is terribly designed and always outputs `0` regardless of the string?\n\n<details><summary>💡 Answers</summary>\n\n1. A collision happens when two completely different keys (e.g. \"apple\" and \"banana\") happen to yield the exact same hash integer, and thus end up in the exact same bucket.\n2. Every single key gets put into Bucket 0. The other 99 buckets remain empty. You essentially regress back to a single giant list, and performance drops to $O(N)$. This is why uniform hashing is critical!\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: A Simple Hash Function\nLet our hash function take a string, sum up the alphabetical index of each character (`A`=1, `B`=2... ignore case, skip non-letters), and then take the result modulo `num_buckets`.\nWrite this function."),
cell("code","def simple_hash(key_string, num_buckets):\n    total = 0\n    for char in key_string.lower():\n        if 'a' <= char <= 'z':\n            total += ord(char) - ord('a') + 1\n    return total % num_buckets\n\n# assert simple_hash(\"cab\", 10) == 6 # (3 + 1 + 2) % 10 = 6\n# print('Phase 0 passed ✅')"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The Hash Table Core\nImplement a `HashTable` class. It initializes `self.buckets` as a list of empty lists. (e.g., `[ [], [], [], ... ]`)."),
cell("code","class HashTable:\n    def __init__(self, num_buckets):\n        self.num_buckets = num_buckets\n        # Create a list containing `num_buckets` empty lists.\n        # IMPORTANT: Use list comprehension! self.buckets = [[]] * num_buckets creates references to the SAME list!\n        self.buckets = [[] for _ in range(num_buckets)]\n        \n    def get_hash(self, key):\n        return simple_hash(key, self.num_buckets)"),
cell("markdown","### Step 2: Insert / Update\nImplement the `put(key, value)` method.\n1. Hash the key to find the correct bucket.\n2. Scan the bucket. If the key already exists, *update* its value.\n3. If it doesn't exist, append the `(key, value)` tuple to the bucket."),
cell("code","# Add this to your HashTable class:\n# def put(self, key, value):\n#     bucket_idx = self.get_hash(key)\n#     bucket = self.buckets[bucket_idx]\n#     \n#     # Check if key exists in bucket\n#     for i in range(len(bucket)):\n#         if bucket[i][0] == key:\n#             bucket[i] = (key, value) # Tuples are immutable, must replace\n#             return\n#             \n#     # If not found, append\n#     bucket.append((key, value))"),
cell("markdown","### Step 3: Retrieval\nImplement the `get(key)` method. Return the value if found, or `None` if not found."),
cell("code","# Add this to your HashTable class:\n# def get(self, key):\n#     bucket_idx = self.get_hash(key)\n#     # Scan the bucket for the key and return value\n#     # YOUR CODE HERE\n#     return None"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Testing Collisions\n\"cab\" and \"abc\" have the same letters, so our `simple_hash` will give them the exact same hash (Collision!). Let's make sure our Hash Table handles this gracefully."),
cell("code","# table = HashTable(10)\n# table.put(\"cab\", 5)\n# table.put(\"abc\", 9)\n\n# print(\"Value for cab:\", table.get(\"cab\")) # Should be 5\n# print(\"Value for abc:\", table.get(\"abc\")) # Should be 9\n# print(\"Bucket array:\", table.buckets) \n# Notice that the bucket at index 6 contains BOTH tuples!"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Dynamic Resizing\nIf we put 10,000 items into a HashTable with 10 buckets, each bucket has 1,000 items, destroying performance.\nReal dictionaries **resize** themselves. If the ratio of items to buckets exceeds a `load_factor` (e.g. 0.75), they create a new bucket array twice the size, and *re-hash* every single item into the new array.\nWrite a `resize()` method!"),
cell("code","# YOUR CODE HERE\npass"),
cell("markdown","### Chalkboard Defense\nExplain why Python's built-in `hash()` function for strings is randomized per session (a security feature). What \"attack\" does this prevent?\n\n<details><summary>💡 Sketch</summary>\nIf the hash algorithm is deterministic and public, a malicious user could intentionally generate 100,000 different string keys that *all* collide to Bucket 0. If they send a JSON payload with these keys to a web server, the server's Hash Table degrades to $O(N^2)$ insertion time, causing the server's CPU to max out and crash. This is a \"Hash Collision Denial of Service (DoS)\" attack! Randomizing the hash seed prevents attackers from pre-computing collisions.\n</details>\n\n---\n📚 **Next:** Algorithms 22 (Simplex Method)")
    ]

def algo_22():
    return [
cell("markdown","# Algorithms 22: Simplex Method\n\n**Learning Objectives:**\n1. Understand Linear Programming and Optimization under Constraints\n2. Introduce Slack Variables to convert inequalities to equations\n3. Implement the Simplex Tableau pivoting algorithm\n\n**Prerequisites:** Algorithms 15\n**Estimated time:** 120 minutes\n**Textbook:** *Justin Skycak — Intro to Algorithms & Machine Learning* Chapter 22"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Maximizing Profit Under Constraints\n> 📖 *From Algorithms Ch. 22:* The simplex method maximizes linear expressions subject to linear constraints. e.g., A business determines the most profitable inventory of products to produce given limited raw materials.\n\nMaximize: $M = x_1 + 2x_2 + x_3$\nSubject to:\n$2x_1 + x_2 + x_3 \\le 14$\n$4x_1 + 2x_2 + 3x_3 \\le 28$\n$2x_1 + 5x_2 + 5x_3 \\le 30$\n\n### Step 1: Slack Variables\nConvert inequalities into equations by adding non-negative \"slack variables\" ($x_4, x_5, x_6$) representing leftover raw materials.\n$x_4 = 14 - 2x_1 - x_2 - x_3$\n$x_5 = 28 - 4x_1 - 2x_2 - 3x_3$\n$x_6 = 30 - 2x_1 - 5x_2 - 5x_3$\n\n### Step 2: Basic vs Non-Basic\nThe variables on the RHS ($x_1, x_2, x_3$) are **non-basic**. We set them to 0. \nThe LHS variables ($x_4, x_5, x_6$) are **basic**. Their values are simply the constants ($14, 28, 30$).\nIf we set $x_1=x_2=x_3=0$, the Profit is 0. We can do better.\n\n### Step 3: Pivoting\n1. Pick the non-basic variable in the Profit equation with the largest positive coefficient ($x_2$ has coefficient 2). We want to increase $x_2$!\n2. How much can we increase $x_2$? Look at the constraints:\n   - $x_4 = 14 - x_2 \\implies x_2 \\le 14$\n   - $x_5 = 28 - 2x_2 \\implies x_2 \\le 14$\n   - $x_6 = 30 - 5x_2 \\implies x_2 \\le 6$ (The strictest constraint!)\n3. Since $x_6$ is the bottleneck, we **trade** $x_2$ for $x_6$. We solve the $x_6$ equation for $x_2$, and substitute that expression into *all* other equations (including the Profit equation). \n4. Repeat until the Profit equation has no positive coefficients left!"),
cell("markdown","### Comprehension Check ✅\nWhy do we stop when all coefficients in the objective (Profit) equation are negative?\n\n<details><summary>💡 Answer</summary>\nBecause the non-basic variables are locked at 0 (and can never be negative). If the Profit equation is $M = 50 - 2x_1 - 3x_4$, increasing $x_1$ or $x_4$ will only *decrease* the profit from 50. Therefore, 50 is the absolute mathematical maximum.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Algebraic Substitution\nEquation 1: $x_6 = 30 - 2x_1 - 5x_2 - 5x_3$\nSolve this algebraically for $x_2$. \n*(Work it out on paper)*\n\n<details><summary>💡 Solution</summary>\n$5x_2 = 30 - 2x_1 - 5x_3 - x_6$\n$x_2 = 6 - 0.4x_1 - 1x_3 - 0.2x_6$\n</details>"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\n### Step 1: The Tableau Representation\nWriting variables is tedious. We use a Tableau (a 2D array or Dictionary). \nInstead of strings, we can represent equations as dictionaries mapping variable indices to coefficients. \nLet's build a `Simplex` class."),
cell("code","class Simplex:\n    def __init__(self, objective, constraints):\n        # objective is a dict mapping var_idx -> coefficient, e.g. {1: 1, 2: 2, 3: 1}\n        # constraints is a list of tuples (constant, dict_of_coeffs)\n        # e.g. (14, {1: -2, 2: -1, 3: -1}) representing x4 = 14 - 2x1 - x2 - x3\n        \n        self.obj = objective\n        self.eqs = {}\n        \n        # Create slack variables\n        slack_idx = max(self.obj.keys()) + 1\n        for constant, coeffs in constraints:\n            self.eqs[slack_idx] = {'const': constant, 'coeffs': coeffs}\n            slack_idx += 1\n            \n    def get_entering_variable(self):\n        # Find the var_idx in self.obj with the maximum positive coefficient\n        # Return None if no positive coefficients remain\n        best_var = None\n        max_coeff = 0\n        # YOUR CODE HERE\n        return best_var"),
cell("markdown","### Step 2: Finding the Leaving Variable (The Bottleneck)\nFor the chosen entering variable, figure out which basic variable's equation places the strictest limit on it."),
cell("code","# Add to Simplex class:\n# def get_leaving_variable(self, enter_var):\n#     # Look at all equations in self.eqs.\n#     # If the coefficient of enter_var is negative, it places an upper bound.\n#     # bound = const / abs(coeff)\n#     # Find the eq_idx with the smallest non-negative bound.\n#     best_eq_idx = None\n#     min_bound = float('inf')\n#     # YOUR CODE HERE\n#     return best_eq_idx"),
cell("markdown","### Step 3: Pivoting\nExecute the algebra! \n1. Isolate the entering variable in the leaving equation.\n2. Substitute this new expression into the Objective function, and into *all other* constraint equations."),
cell("code","# Add to Simplex class:\n# def pivot(self, enter_var, leave_var):\n#     # YOUR CODE HERE\n#     # (This requires careful dictionary manipulation!)\n#     pass\n\n# def solve(self):\n#     while True:\n#         enter_var = self.get_entering_variable()\n#         if enter_var is None: break # Optimal!\n#         leave_var = self.get_leaving_variable(enter_var)\n#         self.pivot(enter_var, leave_var)\n#     return self.obj.get('const', 0) # Maximum profit"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Solving the Widget Factory\nLet's run the example from Phase -1 through your solver. (If you haven't fully coded the `pivot` logic, try doing the dictionary substitutions manually!)"),
cell("code","# obj = {1: 1, 2: 2, 3: 1}\n# c1 = (14, {1: -2, 2: -1, 3: -1})\n# c2 = (28, {1: -4, 2: -2, 3: -3})\n# c3 = (30, {1: -2, 2: -5, 3: -5})\n\n# s = Simplex(obj, [c1, c2, c3])\n# max_profit = s.solve()\n# print(\"Maximum Profit:\", max_profit) # Should be 12.0!"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Matrix Representation\nThe dictionary approach is slow. Professional Simplex solvers use a giant 2D matrix (the Simplex Tableau), and perform pivots using exact same logic as your **Reduced Row Echelon Form** (RREF) from Algorithms 15!\nCombine your RREF matrix skills to implement `MatrixSimplex`.\n\n### Chalkboard Defense\nLinear Programming is solvable in Polynomial Time. Integer Linear Programming (where you can only produce *whole* quantities of objects, e.g. you can't build 0.5 of a car) is NP-Hard. Why does restricting the variables to integers make the problem exponentially harder to solve?\n\n<details><summary>💡 Sketch</summary>\nThe Simplex method glides perfectly along the edges and vertices of a continuous geometric shape (a polytope). If variables must be integers, the geometric vertices are no longer guaranteed to be valid answers! The optimal integer answer might be trapped somewhere deep inside the shape. You essentially have to start brute-forcing integer coordinates near the continuous maximum, leading to exponential branching (Branch and Bound algorithms).\n</details>\n\n---\n📚 **Next:** Algorithms 23 (Introduction to Regression)")
    ]

if __name__=="__main__":
    save(algo_18(),os.path.join(OUT,"18_euler_estimation.ipynb"))
    save(algo_19(),os.path.join(OUT,"19_sir_model.ipynb"))
    save(algo_20(),os.path.join(OUT,"20_hodgkin_huxley.ipynb"))
    save(algo_21(),os.path.join(OUT,"21_hash_tables.ipynb"))
    save(algo_22(),os.path.join(OUT,"22_simplex_method.ipynb"))
    print("Notebooks 18, 19, 20, 21, 22 done. Batch 3 is complete!")
