import json, uuid, os
def cell(t,s):
    c={"cell_type":t,"id":uuid.uuid4().hex[:8],"metadata":{},"source":s.rstrip("\n").split("\n")}
    if t=="code":c["execution_count"]=None;c["outputs"]=[]
    return c
def save(cells,path):
    nb={"cells":cells,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.0"}},"nbformat":4,"nbformat_minor":5}
    with open(path,"w",encoding="utf-8") as f:json.dump(nb,f,indent=1,ensure_ascii=False)
    print(f"  OK {path} ({os.path.getsize(path)//1024}KB)")

OUT=os.path.dirname(os.path.abspath(__file__))
COLAB=cell("code","# Google Colab Setup\n!pip install -q sympy matplotlib plotly ipywidgets\nimport sympy as sp; sp.init_printing()\nimport numpy as np, matplotlib.pyplot as plt\nprint('Ready ✅')")

def math_06():
    return [
cell("markdown","# Math 06: Linear Algebra — Matrices\n\n**Learning Objectives:**\n1. Define matrices and their dimensions\n2. Multiply a matrix by a vector to perform a linear transformation\n3. Multiply two matrices together\n4. Understand the geometric intuition behind matrices\n5. Implement matrix multiplication computationally from scratch\n\n**Prerequisites:** Math 05 (Vectors)\n**Estimated time:** 90 minutes\n**Textbook:** *Justin Skycak — Linear Algebra* §3.1-3.4"),
COLAB,
cell("markdown","---\n## Phase −1 — Theoretical Foundation\n\n### Matrices as Transformations\n> 📖 *From Linear Algebra §3.1:* Matrices can be thought of as objects that transform vectors.\n\nA matrix is a grid of numbers. An $m \\times n$ matrix has $m$ rows and $n$ columns.\nIf we multiply an $m \\times n$ matrix by an $n$-dimensional vector, we get an $m$-dimensional vector.\n\n$$\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix} \\begin{bmatrix} x \\\\ y \\end{bmatrix} = x \\begin{bmatrix} a \\\\ c \\end{bmatrix} + y \\begin{bmatrix} b \\\\ d \\end{bmatrix} = \\begin{bmatrix} ax + by \\\\ cx + dy \\end{bmatrix}$$\n\nNotice that the columns of the matrix dictate where the basis vectors $\\langle 1, 0 \\rangle$ and $\\langle 0, 1 \\rangle$ land!\n\n### Matrix Multiplication\n> 📖 *From Linear Algebra §3.2:* When multiplying two matrices $A$ and $B$, the result $AB$ represents applying transformation $B$ first, then transformation $A$.\n\nThe element in row $i$ and column $j$ of the product matrix $C = AB$ is the **dot product** of the $i$-th row of $A$ and the $j$-th column of $B$.\n\n$$C_{ij} = \\sum_{k=1}^n A_{ik} B_{kj}$$\n\n**Important:** Matrix multiplication is NOT commutative. $AB \\neq BA$ in general. Order matters!"),
cell("code","# Symbolic matrix multiplication\nimport sympy as sp\na, b, c, d, x, y, z, w = sp.symbols('a b c d x y z w')\nA = sp.Matrix([[a, b], [c, d]])\nB = sp.Matrix([[x, y], [z, w]])\n\nprint('AB =')\nsp.pprint(A * B)\nprint('\\nBA =')\nsp.pprint(B * A)\nprint('\\nNotice that AB != BA')"),
cell("markdown","### Comprehension Check ✅\n1. If $A$ is a $3 \\times 2$ matrix, and $B$ is a $2 \\times 4$ matrix, what are the dimensions of $AB$?\n2. Can you compute $BA$ in the previous example?\n3. What matrix leaves any 2D vector unchanged (the Identity matrix)?\n\n<details><summary>💡 Answers</summary>\n\n1. A $3 \\times 4$ matrix. The inner dimensions (2) must match, and the result has the outer dimensions.\n2. No. A $2 \\times 4$ matrix cannot be multiplied by a $3 \\times 2$ matrix because the inner dimensions ($4 \\neq 3$) do not match.\n3. $I = \\begin{bmatrix} 1 & 0 \\\\ 0 & 1 \\end{bmatrix}$.\n</details>"),
cell("markdown","---\n## Phase 0 — Math Foundation Practice\n\n### 🎯 Your Turn: Compute by Hand\n\nGiven $A = \\begin{bmatrix} 1 & 2 \\\\ 3 & 4 \\end{bmatrix}$ and $B = \\begin{bmatrix} 0 & 1 \\\\ -1 & 2 \\end{bmatrix}$:\n\n1. Compute $AB$\n2. Compute $BA$\n\nDo the math on paper, then write code to verify using nested lists."),
cell("code","def matrix_math_practice():\n    # A = [[1, 2], [3, 4]]\n    # B = [[0, 1], [-1, 2]]\n    # YOUR CODE HERE to return AB and BA as nested lists\n    pass\n\n# Test:\n# AB, BA = matrix_math_practice()\n# assert AB == [[-2, 5], [-4, 11]]\n# assert BA == [[3, 4], [5, 6]]\n# print('Phase 0 passed ✅')"),
cell("markdown","---\n## Phase 1 — Algorithm Construction\n\nWe will build a general matrix multiplication function from scratch.\n\n### Step 1: Matrix Dimensions\nWrite a function to return the `(rows, cols)` of a matrix represented as a list of lists."),
cell("code","def get_dims(M):\n    '''Return (num_rows, num_cols) for matrix M.'''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# assert get_dims([[1, 2, 3], [4, 5, 6]]) == (2, 3)\n# print('Step 1 passed ✅')"),
cell("markdown","### Step 2: Dot Product of Row and Column (Interleaved Practice from Math 05)\nTo multiply matrices, we need to dot a row of A with a column of B."),
cell("code","def get_column(M, j):\n    '''Return the j-th column of M as a list.'''\n    # YOUR CODE HERE\n    pass\n\ndef dot_product(u, v):\n    '''Return the dot product of two vectors (lists).'''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# M = [[1, 2], [3, 4]]\n# assert get_column(M, 1) == [2, 4]\n# assert dot_product([1, 2], [3, 4]) == 11\n# print('Step 2 passed ✅')"),
cell("markdown","### Step 3: Full Matrix Multiplication\nCombine the pieces to multiply $A$ and $B$. Raise a `ValueError` if dimensions are incompatible."),
cell("code","def matmul(A, B):\n    '''Multiply matrix A by matrix B.'''\n    # YOUR CODE HERE\n    pass\n\n# Test:\n# A = [[1, 2], [3, 4]]\n# B = [[0, 1], [-1, 2]]\n# assert matmul(A, B) == [[-2, 5], [-4, 11]]\n# print('Step 3 passed ✅')"),
cell("markdown","---\n## Phase 2 — Experimental Verification\n\n### Geometric Visualization\nLet's visualize how a matrix transforms the 2D plane (represented by a grid of points)."),
cell("code","import numpy as np, matplotlib.pyplot as plt\n\n# Create a grid of points\nx, y = np.meshgrid(np.linspace(-2, 2, 10), np.linspace(-2, 2, 10))\npoints = np.vstack([x.flatten(), y.flatten()])\n\n# Transformation Matrix (e.g., a shear)\nA = np.array([[1, 1], \n              [0, 1]])\n\ntransformed_points = A @ points  # numpy uses @ for matrix multiplication\n\nplt.figure(figsize=(10, 5))\nplt.subplot(1, 2, 1)\nplt.scatter(points[0], points[1], c=points[0], cmap='viridis')\nplt.title('Original Grid')\nplt.axis('equal'); plt.grid(True)\n\nplt.subplot(1, 2, 2)\nplt.scatter(transformed_points[0], transformed_points[1], c=points[0], cmap='viridis')\nplt.title('Transformed Grid')\nplt.axis('equal'); plt.grid(True)\nplt.tight_layout(); plt.show()"),
cell("markdown","### Pathological Case: Time Complexity\nHow does the time taken to multiply matrices grow as the matrices get larger?\nLet's test our `matmul` against Numpy's optimized version."),
cell("code","import time, numpy as np\n# We will test N x N matrices\nNs = [10, 50, 100, 200]\n\nfor N in Ns:\n    # Create random N x N matrices as lists\n    A = np.random.rand(N, N).tolist()\n    B = np.random.rand(N, N).tolist()\n    \n    start = time.time()\n    # C = matmul(A, B)  # Uncomment when implemented\n    t_custom = time.time() - start\n    \n    # Numpy version\n    A_np, B_np = np.array(A), np.array(B)\n    start = time.time()\n    C_np = A_np @ B_np\n    t_numpy = time.time() - start\n    \n    print(f'N={N:3d} | Custom: {t_custom:.4f}s | Numpy: {t_numpy:.4f}s')"),
cell("markdown","---\n## Phase 3 — Olympiad Extension\n\n### Challenge: Matrix Exponentiation (O(log n))\nIf you want to compute $A^k$, you could multiply $A$ by itself $k$ times ($O(k)$ operations).\nHowever, using **Exponentiation by Squaring**, you can do it in $O(\\log k)$ operations.\nFor example, $A^8 = ((A^2)^2)^2$.\n\nWrite an efficient matrix exponentiation function."),
cell("code","def mat_pow(A, k):\n    '''Compute A^k efficiently using exponentiation by squaring.'''\n    # YOUR CODE HERE\n    pass"),
cell("markdown","### Chalkboard Defense\n1. Explain the time complexity of standard matrix multiplication for two $N \\times N$ matrices.\n2. Why is Numpy so much faster than our pure Python implementation?\n3. Explain how Exponentiation by Squaring works and prove its time complexity.\n\n<details><summary>💡 Sketch</summary>\n\n1. $O(N^3)$. There are $N^2$ elements to compute, and each requires a dot product of $N$ elements.\n2. Numpy uses highly optimized C/Fortran libraries (BLAS) that utilize CPU vector instructions (SIMD) and cache-friendly memory layouts.\n3. $A^k = (A^{k/2})^2$ if $k$ is even, or $A \\cdot (A^{(k-1)/2})^2$ if $k$ is odd. The number of multiplications halves at each step, taking $\\approx \\log_2(k)$ steps.\n</details>\n\n---\n📚 **Next:** Math 07 (Calculus — Differential Equations)")
    ]

if __name__=="__main__":
    save(math_06(),os.path.join(OUT,"math_06_linear_algebra_matrices.ipynb"))
    print("Batch 1d done.")
